export default [
  ["abroad", "חו&quot;ל"],
  ["accomplices", "שותף לדבר עבירה"],
  ["acquitted", "זוכה מאשמה"],
  ["adhere", "לדבוק ב-, לדגול ב-"],
  ["advocate", "לייעץ"],
  ["advocate", "פרקליט"],
  ["align", "להסתדר בשורה"],
  ["allowance", "דמי כיס, הקצבה"],
  ["allusion", "אזכור, רמיזה"],
  ["ample", "מספיק, שופע, גדול"],
  ["amputation", "קטיעה"],
  ["amusement", "שעשוע"],
  ["anesthesia", "הרדמה"],
  ["annoy", "להציק"],
  ["appraise", "להעריך (שווי), לאמוד"],
  ["ark", "תיבה"],
  ["arrogant", "יהיר, שחצן"],
  ["artifact", "חפץ, פריט אומנות"],
  ["atrocity", "זוועה"],
  ["attire", "לבוש"],
  ["baffled", "מבולבל"],
  ["baggage", "מטען, מזוודה"],
  ["bandage", "תחבושת"],
  ["barrier", "מחסום"],
  ["bashful", "ביישן"],
  ["bent", "כופף"],
  ["blend", "לערבב"],
  ["blur", "טשטוש, לטשטש"],
  ["boil", "להרתיח"],
  ["bolster", "לתמוך"],
  ["boot", "מגף"],
  ["bore", "לשעמם, שעמום"],
  ["bore", "לקדוח (חור)"],
  ["bury", "לקבור"],
  ["cabin", "בקתה"],
  ["ceremony", "טקס, מסכת"],
  ["coal", "פחם"],
  ["command", "פקודה, לפקוד"],
  ["commute", "לנסוע בקביעות לעבודה"],
  ["commute", "להמתיק (עונש)"],
  ["commute", "להחליף, להמיר"],
  ["composed", "הלחין"],
  ["condense", "לדחוס"],
  ["condone", "לסלוח, למחול"],
  ["congenial", "נעים, ידידותי"],
  ["congenital", "מולד"],
  ["consolidate", "לאחד, לגבש"],
  ["container", "מיכל, קונטיינר"],
  ["contest", "תחרות"],
  ["contest", "למחות"],
  ["convict", "להרשיע"],
  ["convict", "אסיר"],
  ["cope", "להתמודד"],
  ["cord", "מיתר"],
  ["cornerstone", "אבן פינה"],
  ["crash", "להתנגש, התנגשות"],
  ["credibility", "אמינות, מהימנות"],
  ["crown", "כתר, להכתיר"],
  ["cultivate", "לעבד, לטפח"],
  ["curiosity", "סקרנות"],
  ["curious", "סקרן"],
  ["curve", "עקומה, פניה"],
  ["damp", "לח"],
  ["dampen", "לדכא"],
  ["dare", "להעיז, תעוזה"],
  ["dare", "אתגר"],
  ["daydream", "לחלום בהקיץ"],
  ["deaf", "חרש"],
  ["defer", "לעכב, לדחות"],
  ["deflate", "להוציא אוויר מ-"],
  ["deform", "לעוות"],
  ["deformity", "מום, עיוות"],
  ["delicate", "עדין"],
  ["demean", "להנמיך, להשפיל"],
  ["department", "מחלקה"],
  ["department-store", "חנות כלבו"],
  ["deposit", "להפקיד, פיקדון"],
  ["depreciate", "להפחית"],
  ["despise", "לתעב"],
  ["dessert", "קינוח"],
  ["devoid", "חסר, נטול"],
  ["disdain", "זלזול, בוז"],
  ["disgrace", "בושה"],
  ["disguise", "תחפושת"],
  ["disloyal", "לא נאמן"],
  ["disparagement", "זלזול"],
  ["dispatch", "לשגר"],
  ["displacement", "עקירה"],
  ["disseminate", "להפיץ"],
  ["docile", "צייתן, כנוע, נח"],
  ["domestic", "ביתי"],
  ["donate", "לתרום"],
  ["donor", "תורם"],
  ["draw", "תיקו, שוויון"],
  ["draw", "לצייר"],
  ["draw (drew)", "לשלוף, שלף"],
  ["drawback", "חסרון, עיכוב"],
  ["drift", "זרם, סחף"],
  ["eager", "נחוש, נלהב"],
  ["embryo", "עוּבָּר"],
  ["engage", "להעסיק, ליצור מגע"],
  ["engagement", "התחייבות"],
  ["engagement", "אירוסין"],
  ["enlist", "להתגייס"],
  ["enrage", "להרגיז, להכעיס"],
  ["entertain", "לשעשע, לבדר"],
  ["entertainment", "בידור"],
  ["entitled", "זכאי"],
  ["entrance", "כניסה"],
  ["envision", "לחזות, לצפות"],
  ["esteemed", "מכובד"],
  ["exaggerate", "להגזים"],
  ["examination", "בחינה, בדיקה"],
  ["examine", "לבחון"],
  ["excitement", "התרגשות"],
  ["exert", "להפעיל"],
  ["exert", "להתאמץ"],
  ["exhaust", "פליטה, צינור מפלט"],
  ["exist", "קיים"],
  ["existence", "קיום"],
  ["expedite", "לזרז"],
  ["expend", "לגמור, לבזבז, לפזר"],
  ["expendable", "שניתן לוותר עליו"],
  ["eyesight", "ראייה, כוונת"],
  ["factory", "מפעל, בית חרושת"],
  ["familiar", "מוכר"],
  ["familiarize", "להתוודע"],
  ["fascinate", "לרתק"],
  ["fertile", "פורה"],
  ["fetus", "עובר (ברחם)"],
  ["fiber", "סיב"],
  ["figurative", "סמלי"],
  ["finalize", "לסכם, לגבש"],
  ["firm", "מוצק"],
  ["firm", "נחוש, תקיף"],
  ["firm", "חברה (פירמה)"],
  ["flagrant", "בוטה"],
  ["flexible", "גמיש"],
  ["fluctuation", "חוסר יציבות"],
  ["fluency", "שטף"],
  ["fluent", "שוטף"],
  ["fluid", "נוזל"],
  ["footprints", "עקבות, טביעות רגל"],
  ["foresee", "לצפות מראש"],
  ["fort", "מצודה, מבצר"],
  ["fortify", "לחזק, לבצר"],
  ["fragrance", "ניחוח"],
  ["freeze, froze", "להקפיא, הקפיא"],
  ["fruit", "פרי"],
  ["fulfill", "להגשים"],
  ["garment", "בגד, לבוש"],
  ["gasoline", "בנזין"],
  ["genre", "ז&#39;אנר, סוגה"],
  ["genus", "סוג, מין"],
  ["giant", "ענק"],
  ["goblet", "גביע"],
  ["greet", "לברך, לקבל פנים"],
  ["grief", "יגון, צער"],
  ["grievance", "טרוניה, התמרמרות"],
  ["growled", "נהם"],
  ["guarantee", "להבטיח, ערבות"],
  ["halve", "לחצות"],
  ["harass", "להציק"],
  ["hasten", "למהר, להחפז"],
  ["hasty", "מהיר, בהול"],
  ["hatch", "לבקוע (מביצה)"],
  ["hatch", "פתח, צוהר"],
  ["haul", "לגרור"],
  ["heed", "לשים לב"],
  ["hegemony", "הגמוניה"],
  ["height", "גובה"],
  ["heresy", "כפירה"],
  ["hibernate", "לישון שנת חורף"],
  ["hid from", "התחבא מ-"],
  ["hidden", "חבוי, נסתר"],
  ["highway", "כביש ראשי"],
  ["hinder", "לעכב"],
  ["hint", "רמז"],
  ["historian", "היסטוריון"],
  ["hive", "כוורת"],
  ["horrific", "אָיוֹם"],
  ["horror", "אימה"],
  ["hospitality", "הכנסת אורחים"],
  ["host", "מארח"],
  ["hostility", "עוינות"],
  ["hypocrisy", "צביעות"],
  ["idolize", "להעריץ"],
  ["ill", "חולה"],
  ["illuminate", "להאיר"],
  ["illusion", "אשליה"],
  ["imaginative", "דמיוני"],
  ["imitate", "לחקות"],
  ["implore", "להתחנן, להפציר"],
  ["imply", "לרמוז"],
  ["imprisonment", "מאסר, כליאה"],
  ["inadvertently", "בלי משים, בלי כוונה"],
  ["incline", "שיפוע"],
  ["incline", "להתאים"],
  ["indebted", "חייב ל-, אסיר תודה"],
  ["induce", "לגרום, לייצר"],
  ["infancy", "ינקות"],
  ["inherit", "לרשת"],
  ["inhibit", "לרסן"],
  ["inject", "להזריק"],
  ["injury", "פציעה"],
  ["insanity", "אי שפיות"],
  ["inspect", "לבחון, לבדוק"],
  ["insult", "עלבון"],
  ["insult", "להעליב"],
  ["integrate", "לשלב"],
  ["intelligence", "מודיעין"],
  ["intelligence", "אינטליגנציה"],
  ["interface", "ממשק"],
  ["interjection", "הערה, הפרעה לשיחה"],
  ["keystone", "אבן מפתח"],
  ["lackluster", "העדר ברק, העדר כוח"],
  ["leisure", "פנאי"],
  ["leisurely", "נינוח, רגוע"],
  ["lucrative", "ריווחי"],
  ["luggage", "מזוודות"],
  ["luminous", "זוהר, בוהק"],
  ["lurking", "אורב, מתגנב"],
  ["magnitude", "גודל, חשיבות"],
  ["malformation", "עיוות, פגם"],
  ["manner", "התנהגות, אופן"],
  ["manners", "נימוס"],
  ["marriage", "נישואין"],
  ["masculine", "גברי"],
  ["merit", "ערך, הישג"],
  ["metal", "מתכת, מתכתי"],
  ["meticulous", "קפדני"],
  ["migrate", "להגר"],
  ["mimic", "לחקות"],
  ["minister", "שר (בממשלה)"],
  ["monarch", "מלך"],
  ["morose", "קודר, עגמומי"],
  ["muscle", "שריר"],
  ["mutation", "מוטציה"],
  ["mystery", "תעלומה"],
  ["narcotic", "סם"],
  ["neighbor", "שכן"],
  ["neighborhood", "שכונה"],
  ["noise", "רעש"],
  ["nuisance", "מטרד"],
  ["nurse", "אחות"],
  ["nursery", "חדר ילדים"],
  ["nurture", "לטפח, להזין, לחנך"],
  ["obligation", "התחייבות"],
  ["oblige", "לחייב, להכריח"],
  ["ocean", "אוקיינוס"],
  ["offset", "לקזז"],
  ["overly", "יותר מידי"],
  ["oversee", "לפקח"],
  ["overwhelm", "מהמם"],
  ["package", "חפיסה, חבילה"],
  ["painter", "צייר"],
  ["painting", "ציור"],
  ["passion", "תשוקה"],
  ["path", "דרך, נתיב"],
  ["patience", "סבלנות"],
  ["patiently", "בסבלנות"],
  ["patients", "מטופלים"],
  ["peddler", "רוכל, סוחר"],
  ["penalty", "קנס"],
  ["people", "אנשים"],
  ["perpetuate", "להנציח"],
  ["pest", "מטרד, מזיק (חרקים)"],
  ["petroleum", "נפט"],
  ["plague", "מגפה"],
  ["plentiful", "מלא, שופע"],
  ["poet", "משורר"],
  ["polar", "קוטבי, הפוך לחלוטין"],
  ["pole", "מוט"],
  ["pole", "קוטב"],
  ["poor", "עני, מסכן"],
  ["poorly", "בצורה גרועה"],
  ["portrait", "דיוקן"],
  ["posterity", "הדורות הבאים"],
  ["pot", "סיר, קדרה"],
  ["potato", "תפוח אדמה"],
  ["potter", "קדר"],
  ["praise", "לשבח"],
  ["prepare", "התכונן"],
  ["preside", "לנהל"],
  ["prestigious", "יוקרתי"],
  ["pretend", "להעמיד פנים"],
  ["principal", "מנהל בית ספר"],
  ["principle", "עיקרון"],
  ["principle", "עיקרי"],
  ["probation", "תקופת מבחן"],
  ["proliferate", "התפשט במהירות"],
  ["prolific", "פורה, שופע"],
  ["prolong", "מתמשך"],
  ["prominent", "בולט, חשוב"],
  ["prone", "נוטה"],
  ["proof", "חסין, עמיד (סיומת)"],
  ["proof", "הוכחה, ראיה"],
  ["propel", "להניע, לדחוף"],
  ["proposal", "הצעה"],
  ["propose", "להציע"],
  ["propose", "להציע, להציע נישואין"],
  ["proposition", "הצעה"],
  ["prospective", "צפוי, עתידי"],
  ["punish", "להעניש"],
  ["readily", "ללא קושי"],
  ["readiness", "מוכנות"],
  ["realize", "הבין"],
  ["rearing", "גידול, טיפוח"],
  ["reassurance", "הבטחה, הרגעה"],
  ["reborn", "נולד מחדש"],
  ["recall", "להיזכר"],
  ["recall", "להחזיר, להשיב צלצול"],
  ["recruitment", "גיוס"],
  ["reliable", "אמין, שניתן לסמוך עליו"],
  ["relic", "שארית, שריד"],
  ["relieve", "להקהל"],
  ["remedy", "תרופה"],
  ["reorganize", "לארגן מחדש"],
  ["repelled", "דחה, הגעיל"],
  ["replica", "העתק מדויק"],
  ["represent", "לייצג, מייצג"],
  ["repressive", "מדכא"],
  ["reproduce", "להתרבות, לשכפל"],
  ["reputation", "שם, מוניטין"],
  ["resent", "להתנגד, להתרעם"],
  ["reservation", "שריון מקום"],
  ["reservation", "שמורה"],
  ["reserve", "לשמור"],
  ["reserve", "שמורה"],
  ["reserve", "עתודה, מילואים"],
  ["reservoir", "מאגר"],
  ["resigned", "התפטר"],
  ["respect", "כבוד, לכבד"],
  ["respectfully", "בכבוד"],
  ["respond", "להגיב, תגובה, תשובה"],
  ["responsibility", "אחריות"],
  ["responsible", "אחראי"],
  ["retirement", "פרישה"],
  ["retreat", "לסגת, נסיגה"],
  ["revise", "לתקן, לשפר"],
  ["revision", "בדיקה מחדש לצורך שיפור"],
  ["ridicule", "ללעוג"],
  ["ridiculous", "מגוחך"],
  ["rim", "שפה"],
  ["rope", "חבל"],
  ["rub", "לשפשף"],
  ["rumor", "שמועה"],
  ["salary", "שכר"],
  ["sanction", "קנס, עונש, עידוד"],
  ["saw", "מסור"],
  ["saw, see", "ראה, לראות"],
  ["seeds", "זרעים"],
  ["segment", "קטע, מקטע"],
  ["self-confidence", "בטחון-עצמי"],
  ["self-indulgence", "סיפוק-עצמי"],
  ["sequel", "המשך"],
  ["sequence", "רצף"],
  ["shatter", "לנפץ, להרוס, לקעקע"],
  ["shell", "קליפה, מעטפת"],
  ["shell", "פגז"],
  ["shelter", "מקלט"],
  ["shield", "מגן, להגן"],
  ["signature", "חתימה"],
  ["silent", "דומם, שקט"],
  ["silently", "בשקט"],
  ["slant", "אלכסון, נטייה"],
  ["slate", "להכניס מישהו לרשימה"],
  ["slate", "רעף, לוח"],
  ["slaughter", "לטבוח, לשחוט, טֶבַח"],
  ["slave", "עבד"],
  ["slavery", "עבדות"],
  ["slender", "רזה"],
  ["slope", "שיפוע, מדרון"],
  ["snicker", "גיחוך"],
  ["soldier", "חייל"],
  ["solitary", "מבודד"],
  ["solve", "לפתור"],
  ["soul", "נשמה"],
  ["sound", "קול"],
  ["sound", "בריא"],
  ["special", "מיוחד"],
  ["spike", "יתד"],
  ["splendor", "פאר"],
  ["spotlight", "זרקור"],
  ["stage", "במה, לביים"],
  ["starve", "לרעוב"],
  ["store", "חנות, לאחסן"],
  ["store", "לאחסן"],
  ["stress", "להדגיש"],
  ["stress", "מתח, לחץ, מצוקה"],
  ["strict", "נוקשה"],
  ["stubborn", "עקשן"],
  ["subsequent", "עוקב"],
  ["supplement", "תוסף"],
  ["supply", "אספקה"],
  ["susceptible", "רגישות"],
  ["suspend", "להשעות"],
  ["suspense", "השהיה, מתח"],
  ["tact", "טקט"],
  ["tension", "מתח"],
  ["testify", "להעיד"],
  ["texture", "מרקם, טקסטורה"],
  ["tie", "עניבה"],
  ["tie", "לקשור, קשר"],
  ["timber", "עץ"],
  ["tomb", "קבר"],
  ["trait", "תכונה"],
  ["tranquilize", "להרגיע, להרדים"],
  ["transaction", "עסקה"],
  ["transcend", "להתעלות"],
  ["transition", "מעבר, שינוי"],
  ["transparent", "שקוף"],
  ["transport", "הובלה"],
  ["transport", "להוביל"],
  ["transportation", "תחבורה"],
  ["unconventional", "לא שיגרתי"],
  ["underestimate", "הערכה נמוכה, לזלזל"],
  ["vacant", "פנוי, ריק"],
  ["veteran", "חייל משוחרר, יוצא צבא"],
  ["veteran", "ותיק"],
  ["virtue", "מעלה"],
  ["vital", "חיוני"],
  ["vivid", "חד, בהיר, ססגוני, שופע"],
  ["vulnerable", "פגיעות"],
  ["warn", "להזהיר"],
  ["warning", "אזהרה"],
  ["weaken", "להחליש"],
  ["withdraw", "לסגת, לפרוש"],
  ["witness", "עד, להעיד"],
  ["worry", "דאגה, לדאוג"],
  ["zoo", "גן חיות"]
] as const;
