export default [
  ["slaughterhouse", "בית מטבחיים"],
  ["readiness", "מוכנות"],
  ["falsehood", "שקר"],
  ["leniency", "חמלה, רחמים"],
  ["immersion", "שקיעה"],
  ["intrusive", "פולשני"],
  ["mathematician", "מתמטיקאי"],
  ["astonishment", "תדהמה, השתאות"],
  ["launder", "לכבס"],
  ["unholy", "לא קדוש, לא מוסרי"],
  ["vocation", "מקצוע"],
  ["tainted", "מוכתם, מזוהם"],
  ["convalesce", "להחלים"],
  ["furnish", "לרהט"],
  ["leisurely", "נינוח, רגוע"],
  ["flee, fled", "להימלט, נמלט"],
  ["insuperable", "שלא ניתן לגבור עליו"],
  ["presentation", "מצגת"],
  ["supposition", "הנחה, השערה"],
  ["malformation", "עיוות, פגם"],
  ["embitter", "גורם התמרמרות"],
  ["junkyard", "מגרש גרוטאות"],
  ["purification", "טיהור"],
  ["dictation", "תכתיב"],
  ["humiliate", "להשפיל"],
  ["cougar", "פומה, סוג של טורף"],
  ["hibernate", "לישון שנת חורף"],
  ["paddle", "משוט, דוושה, מחבט"],
  ["zealot", "קנאי, פנט"],
  ["expendable", "שניתן לוותר עליו"],
  ["restatement", "ניסוח מחדש"],
  ["extortion", "סחיטה"],
  ["assertively", "בביטחון, באופן החלטי"],
  ["beak", "מקור"],
  ["phobia", "פוביה, פחד כרוני"],
  ["enchant", "לכשף, להקסים"],
  ["freeze, froze", "להקפיא, הקפיא"],
  ["ostentatious", "ראוותני, יומרני, גנדרני"],
  ["defection", "עריקה"],
  ["transcend", "להתעלות"],
  ["insurrection", "התקוממות"],
  ["hilarious", "מצחיק"],
  ["finalize", "לסכם, לגבש"],
  ["exhibition", "תערוכה"],
  ["bamboozle", "לבלבל, לרמות"],
  ["steamship", "אוניית קיטור"],
  ["congregate", "לאסוף קהל, לאסוף"],
  ["cologne", "קולון, בושם (של גבר)"],
  ["frugal", "חסכני"],
  ["silkworm", "תולעת משי"],
  ["consonant", "עיצור (לשון)"],
  ["speck", "כתם"],
  ["rubbish", "שטויות, זבל"],
  ["uncountable", "אינספור"],
  ["segregation", "הפרדה"],
  ["rehabilitation", "שיקום"],
  ["exhale", "לנשוף"],
  ["quench", "לספק, להרוות"],
  ["deflate", "להוציא אוויר מ-"],
  ["spontaneous", "ללא מחשבה"],
  ["vociferous", "רעשני"],
  ["preparation for", "הכנות לקראת"],
  ["gracious", "חינני, אדיב, מקסים"],
  ["sarcophagus", "ארון קבורה קדום"],
  ["hospitalize", "לאשפז"],
  ["imaginative", "דמיוני"],
  ["dissection", "חיתוך, ביתור"],
  ["mouse (mice)", "עכבר (עכברים)"],
  ["concurred with", "להתרחש בו זמנית, להתאים"],
  ["coexistence", "דו-קיום"],
  ["uncritical", "לא ביקורתי"],
  ["repressive", "מדכא"],
  ["amputation", "קטיעה"],
  ["caviar", "קוויאר"],
  ["concurrence", "להתרחש בו זמנית"],
  ["heart-rending", "קורע לב"],
  ["conductor", "מנצח (תזמורת)"],
  ["complication", "סיבוך"],
  ["genial", "ידידותי"],
  ["old-fashioned", "מיושן"],
  ["excitement", "התרגשות"],
  ["unconcerned", "לא מודאג"],
  ["plaster", "טיח"],
  ["stereotype", "סטריאוטיפ"],
  ["accessibility", "נגישות"],
  ["accentuate", "להבליט, להדגיש"],
  ["commendably", "באופן ראוי לשבח"],
  ["recreation", "בילוי"],
  ["enfeeble", "להחליש"],
  ["ambivalence", "רגשות סותרים"],
  ["fragrance", "ניחוח"],
  ["staircase", "גרם מדרגות"],
  ["disturbance", "הפרעה"],
  ["drench", "להרטיב, להספיג"],
  ["deliberation", "דיון, הרהור"],
  ["citrus", "פרי הדר"],
  ["admittance", "הכנסה, הודאה"],
  ["wolf (wolves)", "זאב (זאבים)"],
  ["correspondence", "התאמה, התכתבות"],
  ["reciprocal", "מספר הופכי (במתמטיקה), הדדי"],
  ["nuisance", "מטרד"],
  ["inflate", "לנפח"],
  ["shrewdness", "פיקחות"],
  ["perch", "נח, ישב על ענף, ענף"],
  ["saturated", "רווי"],
  ["dispensable", "לא הכרחי, שניתן להסתדר בלעדיו, שאפשר לוותר עליו"],
  ["blaspheme", "לחלל (דבר קדוש)"],
  ["reincarnation", "גלגול נשמות"],
  ["contradiction", "ניגוד, סתירה"],
  ["glorify", "להאדיר"],
  ["disuse", "חוסר שימוש"],
  ["insulate", "לבודד"],
  ["croak", "קרקור"],
  ["loneliness", "בדידות"],
  ["subtraction", "חיסור (חשבון)"],
  ["fringes", "שוליים"],
  ["doorstep", "מפתן הדלת"],
  ["pathology", "פתולוגיה, ענף ברפואה"],
  ["intimidate", "להפחיד"],
  ["apathetic", "אדיש"],
  ["wasp", "צרעה"],
  ["imprisonment", "מאסר, כליאה"],
  ["intuition", "אינטואיציה"],
  ["self-indulgence", "סיפוק-עצמי"],
  ["intermission", "הפסקה"],
  ["leopard", "פנתר, נמר"],
  ["unwilling", "לא מוכן, ממאן"],
  ["ring, rang", "לצלצל, צלצל"],
  ["detrimental", "מזיק"],
  ["janitor", "שרת"],
  ["fraternal", "אחוותי, של אחים"],
  ["sentiments", "רגשות"],
  ["substance", "חומר, תוכן"],
  ["overhaul", "שיפוץ, אוברול"],
  ["flimsy", "עדין, שביר"],
  ["midair", "באוויר"],
  ["advantageous", "מועיל"],
  ["shelf (shelves)", "מדף (מדפים)"],
  ["vagueness", "עמימות, ערפול"],
  ["saturnine", "עצוב, קודר, זועף"],
  ["embalm", "לחנוט, לשמר"],
  ["goblet", "גביע"],
  ["unconventional", "לא שיגרתי"],
  ["revitalize", "להחיות"],
  ["misconception", "דעה מוטעית"],
  ["inspect", "לבחון, לבדוק, לפקח, לבדוק בדקדקנות"],
  ["morose", "קודר, עגמומי"],
  ["spewing", "להזרים"],
  ["butterfly", "פרפר"],
  ["advertisement", "פרסומת, פרסום, מודעה"],
  ["erudition", "השכלה עצומה"],
  ["mechanize", "למכן, להתקין מכונות"],
  ["incompetence", "חוסר יכולת"],
  ["narration", "קריינות"],
  ["perpetuate", "להנציח"],
  ["antler", "קרן"],
  ["dampen", "לדכא"],
  ["dissect", "לנתח, לבתר"],
  ["invariably", "ללא שינוי"],
  ["endurance", "כוח סבל"],
  ["unrealistic", "לא מציאותי"],
  ["indifference", "אדישות"],
  ["jagged", "משונן"],
  ["vertebrate", "בעל חוליות"],
  ["interjection", "הערה, הפרעה לשיחה"],
  ["rearing", "גידול, טיפוח"],
  ["envious", "קנאי"],
  ["glacier", "קרחון"],
  ["viper", "צפע"],
  ["snarl", "לרטון, לנחור"],
  ["staunch", "חזק, מוצק, לעצור, לחסום"],
  ["straighten", "ליישר"],
  ["disinfection", "חיטוי"],
  ["explosive", "חומר נפץ"],
  ["fairytale", "אגדה"],
  ["affluence", "שפע"],
  ["eulogize", "לפאר ולשבח"],
  ["fume", "אדים, עשן"],
  ["mountainside", "מדרון"],
  ["underestimate", "הערכה נמוכה, לזלזל"],
  ["congenial", "נעים, ידידותי"],
  ["reservation", "שמורה, שריון מקום"],
  ["quarrelsome", "וכחני"],
  ["garment", "בגד, לבוש"],
  ["peddler", "רוכל, סוחר"],
  ["Mediterranean", "ים תיכוני"],
  ["neighborhood", "שכונה"],
  ["grammatical", "דקדוקי"],
  ["obligation", "התחייבות"],
  ["sedative", "סם הרגעה, משכך"],
  ["folklore", "פולקלור"],
  ["rebellious", "סורר, מרדני"],
  ["consternation", "תדהמה, פחד"],
  ["culminate", "הגיע לשיא, להגיע לשיא"],
  ["fascinate", "לרתק, להקסים"],
  ["suffocation", "חנק"],
  ["courteous", "אדיב"],
  ["enclosing", "לסגור, להקיף"],
  ["[to] languish", "להיחלש"],
  ["idolize", "להעריץ"],
  ["marsupial", "חיית כיס"],
  ["stenographer", "קצרן"],
  ["confinement", "מאסר, ריתוק"],
  ["guillotine", "גיליוטינה"],
  ["erroneous", "שגוי"],
  ["czar", "צאר (שליט רוסי)"],
  ["malnutrition", "תת-תזונה"],
  ["accomplices", "שותף לדבר עבירה"],
  ["mountaintop", "פסגת הר"],
  ["swindler", "רמאי"],
  ["expansion", "התפתחות, התפשטות, התרחבות"],
  ["audacious", "נועז"],
  ["allusion", "אזכור, רמיזה"],
  ["derivation", "הוכחה (לוגית), הפקה, גזירה"],
  ["dwindle", "הידלדל, התמעט, להתמעט, להיעשות קטן ויותר, להתדלדל"],
  ["embarrass", "להביך"],
  ["mutation", "מוטציה"],
  ["glance", "מבט חטוף"],
  ["acquitted", "זוכה מאשמה"],
  ["proliferate", "התפשט במהירות"],
  ["fisherman", "דייג"],
  ["demented", "משוגע, מטורף"],
  ["yawn", "לפהק, פיהוק"],
  ["deterioration", "הדרדרות"],
  ["juxtapose", "להציב זה לצד זה"],
  ["inexpensive", "לא יקר, זול"],
  ["deform", "לעוות"],
  ["relegated", "הורד בדרגה"],
  ["disseminate", "להפיץ"],
  ["compost", "זבל אורגני"],
  ["savanna", "ערבה, סוואנה"],
  ["irresistible", "שלא ניתן לעמוד בפניו"],
  ["triggered", "גרם, עורר, הוביל ל-"],
  ["cripple", "להטיל מום"],
  ["swept away", "נסחף"],
  ["denominator", "מכנה (של שבר)"],
  ["compulsion", "כפייה"],
  ["growled", "נהם"],
  ["poisonous", "רעיל"],
  ["vowel", "תנועה (לשון)"],
  ["kettle", "קומקום"],
  ["installation", "התקנה"],
  ["resurgence", "תחייה"],
  ["[to] industrialize", "לתעש"],
  ["enrage", "להרגיז, להכעיס"],
  ["lucrative", "ריווחי"],
  ["depreciate", "להפחית"],
  ["inadvertently", "בלי משים, בלי כוונה"],
  ["limber", "גמיש"],
  ["fallacious", "מטעה"],
  ["filmmaker", "יוצר סרטים"],
  ["obstinate", "עקשן"],
  ["separation", "הפרדה"],
  ["accusation", "האשמה"],
  ["[to] horrify", "להפחיד"],
  ["cadaver", "גופה"],
  ["disparagement", "זלזול"],
  ["fabricate", "לבדות"],
  ["predominantly", "באופן ניכר"],
  ["shingles", "רעף"],
  ["magnitude", "חשיבות, משמעות, גודל או שיעור מסויים, גודל"],
  ["deformity", "מום, עיוות"],
  ["upholstery", "ריפוד"],
  ["salvation", "ישועה, גאולה"],
  ["punctuation", "ניקוד, פיסוק"],
  ["aspiration", "שאיפה, חלום"],
  ["reassurance", "הבטחה, הרגעה"],
  ["demean", "להנמיך, להשפיל"],
  ["nausea", "בחילה"],
  ["unpardonable", "בלתי נסלח"],
  ["prescribe", "לרשום מרשם"],
  ["appease", "לפייס"],
  ["respectfully", "בכבוד"],
  ["invertebrate", "חסר-חוליות"],
  ["physicist", "פיזיקאי"],
  ["amusement", "שעשוע"],
  ["deliberative", "שנעשה בכוונה תחילה, דיוני"],
  ["wickedness", "רוע, רשע"],
  ["memorize", "לשנן, לזכור בעל-פה"],
  ["grievance", "טרוניה, התמרמרות"],
  ["decorative", "קישוטי, דקורטיבי"],
  ["encroach", "להסיג גבול, לפלוש"],
  ["appraise", "להעריך (שווי), לאמוד"],
  ["allowance", "דמי כיס, קצבה, הקצבה"],
  ["teeth, tooth", "שיניים, שן"],
  ["meticulous", "קפדני"],
  ["prehistoric", "קדמון, פרה-היסטורי"],
  ["toad", "קרפדה"],
  ["brutishly", "בבהמיות, באכזריות"],
  ["tentative", "ניסיוני, טנטטיבי"],
  ["waterfall", "מפל"],
  ["twig", "ענף קטן, זרד"],
  ["lamentable", "מצער, מעציב"],
  ["uproar", "רעש, מהומה"],
  ["crossroad", "צומת"],
  ["implore", "להתחנן, להפציר"],
  ["exaggeration", "הגזמה"],
  ["forgettable", "שאפשר לשכוח אותו"],
  ["theoretically", "תיאורטית, לכאורה"],
  ["gland", "בלוטה"],
  ["outspread", "לפרוש לרווחה"],
  ["shapeless", "חסר צורה"],
  ["orchestrate", "לתאם, לתזמר"],
  ["intermediary", "מתווך, אמצעי"],
  ["poultry", "עוף"],
  ["abhor", "לשנוא, לתעב"],
  ["congenital", "מולד"],
  ["posterity", "הדורות הבאים"],
  ["thimble", "אצבעון (לתפירה)"],
  ["proverb", "פתגם, אמרה"],
  ["avaricious", "חמדן, תאב בצע"],
  ["numeric", "מספרי"],
  ["envision", "לחזות, לצפות"],
  ["redhead", "ג'ינג'י (סלנג)"],
  ["wholesale", "סיטונאות"],
  ["eccentric", "מוזר, אקסצנטרי"],
  ["fluctuation", "חוסר יציבות"],
  ["monument", "אנדרטה"],
  ["plentiful", "מלא, שופע"],
  ["deducible", "ניתן להסקה, ניתן להיקש"],
  ["frustration", "תסכול"],
  ["reinvigorate", "לרענן, להמריץ מחדש"],
  ["adorn", "לקשט"],
  ["overwhelm", "מהמם"],
  ["persuasion", "שכנוע"],
  ["adolescence", "נעורים' גיל ההתבגרות, גיל ההתבגרות"],
  ["complaisance", "אדיבות, נכונות לרצות אחרים"],
  ["commiserate", "להשתתף בצער"],
  ["intoxicate", "להרעיל, לשכר, להלהיב"],
  ["instantaneous", "מיידי"],
  ["cosmopolitan", "אוניברסלי"],
  ["unwanted", "לא רצוי"],
  ["agonize", "לענות, לייסר"],
  ["intersection", "צומת, הצטלבות"],
  ["loathe", "לתעב"],
  ["infraction", "עבירה"],
  ["rehearse", "לחזור, לתרגל"],
  ["sincerity", "כנות"],
  ["annihilate", "להשמיד"],
  ["disagreement", "חוסר הסכמה"],
  ["automobile", "כלי רכב, אוטו"],
  ["glaze", "זיגוג"],
  ["disapproving", "לא מאשר, לא מסכים, לא מרוצה"],
  ["leaf (leaves)", "עלה (עלים)"],
  ["credibility", "אמינות, מהימנות"],
  ["retroactive", "רטרואקטיבי, למפרע"],
  ["[to] valuate", "לאמוד"],
  ["repelled", "דחה, הגעיל"],
  ["misbehave", "להתנהג בצורה לא הולמת"],
  ["abbreviate", "לקצר"],
  ["rainstorm", "סערת גשמים"],
  ["cashier", "קופאי"],
  ["argumentative", "וכחן"],
  ["snicker", "גיחוך"],
  ["spinach", "תרד"],
  ["fraction", "חלק קטן, שבר"],
  ["reciprocate", "הדדי"],
  ["canvass", "לבדוק, לסקור"],
  ["symmetry", "סימטריה, התאמה"],
  ["figurative", "סמלי, מוחשי (ציור), ציורי (ספרות)"],
  ["conquistador", "כובש"],
  ["proposition", "הצעה"],
  ["syllable", "הברה"],
  ["extrapolate", "לאמוד על סמך מידע קיים"],
  ["housemaid", "עוזרת בית, מנקה"],
  ["erosion", "סחף, כרסום"],
  ["alertness", "עירנות, דריכות"],
  ["unorganized", "לא מאורגן"],
  ["invariable", "קבוע, שאינו משתנה"],
  ["sneeze", "להתעטש"],
  ["inject", "להזריק"],
  ["transportation", "תחבורה"],
  ["unattractive", "לא מושך"],
  ["abacus", "חשבונייה"],
  ["shroud", "תכריך, עטיפה"],
  ["howl", "יללה, לילל"],
  ["accompaniment", "ליווי"],
  ["docility", "כניעות, צייתנות"],
  ["pothole", "מהמורה, בור"],
  ["summits", "פסגות"],
  ["supplement", "תוסף"],
  ["devastated", "הרוס, מפורק"],
  ["footprints", "עקבות, טביעות רגל"],
  ["ingest", "להכניס משהו לגוף דרך הפה"],
  ["self-confidence", "בטחון-עצמי"],
  ["derision", "לעג"],
  ["epitomize", "לייצג, לאפיין"],
  ["cockroach", "מקק, ג'וק"],
  ["numerator", "מונה (של שבר)"],
  ["reprove", "לגעור"],
  ["formulate", "לנסח"],
  ["upheaval", "מהפך"],
  ["frightening", "מפחיד"],
  ["rehearsal", "חזרה"],
  ["recruitment", "גיוס"],
  ["disloyal", "לא נאמן"],
  ["agglomeration", "ערימה"],
  ["desperation", "ייאוש"],
  ["exaggerate", "להגזים"],
  ["familiarize", "להתוודע"],
  ["taint", "להכתים, להכפיש, לזהם"],
  ["caterpillar", "זחל"],
  ["dovecote", "שובך"],
  ["condense", "לדחוס"],
  ["valuate", "להעריך"],
  ["interminable", "נצחי"],
  ["alienation", "ניכור, הרחקה"],
  ["octopus", "תמנון"],
  ["simultaneous", "בו-זמנית, באותו הזמן"],
  ["insurmountable", "שאין להתגבר עליו"],
  ["convalescence", "החלמה"],
  ["disparage", "לזלזל, להמעיט בערך"],
  ["wart", "יבלת"],
  ["diurnal", "יומי"],
  ["communicative", "מוכן לתקשר"],
  ["accumulative", "מצטבר"],
  ["ensue", "נבע"],
  ["halve", "לחצות"],
  ["instill", "להחדיר, להשריש"],
  ["upbringing", "גידול, חינוך"],
  ["recollection", "זיכרון"],
  ["augment", "להרחיב"],
  ["smog", "ערפיח"],
  ["tranquilize", "להרגיע, להרדים"],
  ["disarmament", "פירוק מנשק"],
  ["bashful", "ביישן"],
  ["icicle", "נטיף קרח"],
  ["cucumber", "מלפפון"],
  ["heartbeat", "דופק, פעימות לב"],
  ["inflammation", "דלקת"],
  ["expatriate", "להגלות, לגרש"],
  ["scrutinize", "בדק, בחן, לבדוק, לחקור, לבחון בקפידה, לעיין"],
  ["punctuate", "הדגשה"],
  ["evocative", "מעורר, מעלה, מזכיר"],
  ["ornament", "קישוט"],
  ["puzzled", "מבולבל"],
  ["surveillance", "מעקב"],
  ["reorganize", "לארגן מחדש"],
  ["dislocate", "לפרוק, לנקוע"],
  ["air conditioner", "מזגן"],
  ["probation", "תקופת מבחן"],
  ["displacement", "עקירה"],
  ["contaminate", "לזהם"],
  ["vacation", "חופשה"],
  ["arable", "מתאים לעיבוד"],
  ["prowess", "מיומנות, יכולת"],
  ["lackluster", "העדר ברק, העדר כוח"],
  ["heroine", "גיבורה"],
  ["obsession", "קיבעון, אובססיה, דיבוק"],
  ["sanction", "קנס, עונש, עידוד"],
  ["gymnasium", "אולם ספורט"],
  ["unearth", "לחשוף, לחפור"]
] as const;
