[
  ["abandon", "לנטוש, לזנוח"],
  ["abduct", "חטיפה, לחטוף", "1"],
  ["abide", "לציית"],
  ["absence", "מחסור"],
  ["absent", "חסר, לא נוכח"],
  ["absorb", "לספוג"],
  ["abundance", "שפע"],
  ["abuse", "התעללות, ניצול"],
  ["abuse", "להתעלל, לנצל"],
  ["accumulate", "לצבור, לאסוף"],
  ["acquire", "לרכוש, להשיג"],
  ["acquisition", "רכישה"],
  ["adopt", "לאמץ"],
  ["adventure", "הרפתקה"],
  ["affect", "להשפיע"],
  ["affection", "חיבה"],
  ["affluence", "שפע"],
  ["affluent", "שופע, עשיר"],
  ["aid", "עזרה, לסייע"],
  ["airborne", "נישא באוויר"],
  ["airline", "חברת תעופה"],
  ["airplane", "אווירון, מטוס"],
  ["alike", "דומה"],
  ["allow", "להרשות"],
  ["ally (allies)", "בן-ברית (בנות-ברית)"],
  ["alter", "שינה ,לשנות"],
  ["alterations", "שינויים"],
  ["alternately", "לסירוגין"],
  ["amateur", "חובבן"],
  ["amend", "תיקון, שינוי לטובה"],
  ["analyze", "לנתח"],
  ["anticipate", "לצפות"],
  ["anxious", "להוט"],
  ["anxious", "חרד"],
  ["apparent", "גלוי"],
  ["apparently", "כנראה"],
  ["apply", "לפנות"],
  ["appreciate", "עליה בערך"],
  ["appreciation", "הערכה", "3"],
  ["appropriately", "בהתאם"],
  ["arise", "להופיע, לעלות"],
  ["arise, arose", "לקום, קם"],
  ["artificial", "מלאכותי"],
  ["aside", "במאמר מוסגר, מלבד"],
  ["aside", "הצידה"],
  ["assess", "להעריך, לאמוד"],
  ["asset", "נכס"],
  ["assign", "למנות, להקצות"],
  ["assignment", "משימה, מטלה"],
  ["attain", "להשיג, להגיע"],
  ["attend", "להשתתף, להיות נוכח"],
  ["attendant", "משרת, מטפל, מלווה"],
  ["authority", "סמכות"],
  ["authorize", "להרשות, להסמיך"],
  ["autumn", "סתיו"],
  ["await", "להמתין"],
  ["awareness", "מודעות"],
  ["bare", "חשוף, ריק, לחשוף"],
  ["behave", "להתנהג"],
  ["behavior", "התנהגות"],
  ["bounce", "לקפץ, ניתור"],
  ["brilliant", "מבריק"],
  ["burden", "עול"],
  ["bush", "שיח"],
  ["bush", "ערבה"],
  ["cable", "כבל"],
  ["calculate", "לחשב"],
  ["calculator", "מחשבון"],
  ["campaign", "מערכה, מסע"],
  ["candid", "כנה, ישיר"],
  ["candidate", "מועמד"],
  ["case", "מקרה, טיעון"],
  ["case", "תיבה"],
  ["categorize", "לקטלג, למיין, לסווג"],
  ["cautious", "זהיר"],
  ["century", "מאה שנים"],
  ["charge", "להאשים"],
  ["charge", "לחייב"],
  ["charge", "להסתער"],
  ["charge", "לגבות"],
  ["charge", "להאשים"],
  ["chart", "גיליון, תרשים"],
  ["claim", "טענה, טוען"],
  ["claim", "תביעה"],
  ["coincide", "להקביל, לחפוף"],
  ["colossal", "עצום"],
  ["commence", "להתחיל"],
  ["compress", "לדחוס"],
  ["comprise", "לכלול"],
  ["concept", "רעיון, מושג"],
  ["conception", "תפיסה"],
  ["confer", "להתייעץ"],
  ["confer", "להעניק, להסביר"],
  ["conference", "ועידה"],
  ["confide", "לשתף, לספר (סוד)"],
  ["confident", "בטוח בעצמו"],
  ["conflict", "עימות, סכסוך"],
  ["conjecture", "סברה, לשער"],
  ["connect", "לחבר"],
  ["consequence", "תוצאה"],
  ["consider", "לקחת בחשבון, לשקול"],
  ["considerable", "הרבה, רבות"],
  ["consume", "לצרוך"],
  ["consumers", "צרכנים"],
  ["contain", "להכיל, מכיל"],
  ["contemporary", "עכשווי"],
  ["convenient", "נוח"],
  ["conveniently", "באופן נח"],
  ["convention", "ועידה, כנס"],
  ["convention", "מוסכמה"],
  ["conventional", "שגרתי, קונבנציונאלי"],
  ["convert", "מומר"],
  ["convert", "להמיר"],
  ["convey", "למסור, להעביר"],
  ["courageous", "אמיץ"],
  ["create", "ליצור"],
  ["creator", "יוצר"],
  ["creature", "יצור"],
  ["currency", "מטבע"],
  ["custom", "מנהג"],
  ["custom", "מותאם אישית"],
  ["customer", "לקוח, צרכן"],
  ["customize", "להתאים באופן אישי"],
  ["damage", "נזק, לגרום נזק"],
  ["decade", "עשור"],
  ["defeat", "תבוסה"],
  ["defeated", "הובס"],
  ["defend", "להגן"],
  ["defense", "הגנה"],
  ["deficiency", "מחסור"],
  ["deliver", "לשלוח"],
  ["delivery", "משלוח"],
  ["demographic", "דמוגרפי"],
  ["demonstrate", "להפגין"],
  ["demonstrate", "להדגים"],
  ["destination", "יעד"],
  ["detach", "להתנתק"],
  ["deteriorate", "להידרדר"],
  ["diagnose", "לאבחן"],
  ["director", "מנהל"],
  ["director", "במאי"],
  ["discriminate", "להפלות"],
  ["dismiss", "לבטל, לפטר, לשחרר"],
  ["disposable", "חד-פעמי"],
  ["disrupt", "להפריע, לשבש"],
  ["distribute", "להפיץ"],
  ["distribution", "הפצה"],
  ["document", "לתעד"],
  ["document", "מסמך"],
  ["duty", "תפקיד, חובה"],
  ["earn", "להרוויח"],
  ["economy", "כלכלה"],
  ["edge", "קצה, חספוס"],
  ["elaborate", "לפרט, להרחיב"],
  ["elect", "לבחור"],
  ["emerge", "להגיח, להופיע"],
  ["emigrate", "להגר"],
  ["eminent", "בולט, בכיר"],
  ["enclose", "לצרף"],
  ["enlarge", "להגדיל"],
  ["ensure", "להבטיח"],
  ["environment", "סביבה"],
  ["epidemic", "מגיפה, אפידמיה"],
  ["equivalent", "מקבילה"],
  ["erase", "למחוק"],
  ["eraser", "מחק"],
  ["establish", "לייסד"],
  ["estimate", "להעריך, לאמוד"],
  ["ethical", "אתי, מוסרי"],
  ["evade", "התחמק"],
  ["evidence", "ראיה"],
  ["exception", "יוצא מהכלל"],
  ["execute", "להוציא לפועל"],
  ["execute", "להוציא להורג"],
  ["facility", "מתקן"],
  ["fail", "להיכשל"],
  ["failure", "כשלון"],
  ["faith", "אמון"],
  ["fall", "סתיו"],
  ["feature", "להציג"],
  ["feature", "סרט באורך מלא"],
  ["feature", "תכונה, מאפיין"],
  ["flourish", "לשגשג, לפרוח"],
  ["follow", "לעקוב, לציית"],
  ["for the sake of", "למען"],
  ["force", "לכפות"],
  ["force", "כוח"],
  ["forsake", "לזנוח"],
  ["found", "מצא, גילה"],
  ["found", "לייסד"],
  ["foundation", "יסוד"],
  ["function", "תפקוד, לתפקד"],
  ["future", "עתיד"],
  ["gather", "אסף"],
  ["global", "עולמי, גלובאלי"],
  ["goal", "מטרה"],
  ["goods", "סחורה, טובין"],
  ["grasp", "לתפוס, להבין"],
  ["grasp", "אחיזה"],
  ["group", "קבוצה, לקבץ"],
  ["hardly", "בקושי"],
  ["hesitate", "להסס"],
  ["hold back", "לעכב, למנוע"],
  ["homeland", "מולדת"],
  ["honest", "הגון"],
  ["honor", "לכבד, כבוד"],
  ["huge", "עצום, ענק"],
  ["idea", "רעיון"],
  ["identify", "לזהות"],
  ["illegal", "לא חוקי"],
  ["image", "דמות, תמונה"],
  ["imagination", "דמיון"],
  ["imagine", "לדמיין"],
  ["impair", "לפגום, להחליש"],
  ["impart", "להעביר, להקנות"],
  ["impartially", "באופן הוגן, ללא אפליה"],
  ["import", "לייבא"],
  ["impose", "לכפות"],
  ["impossible", "בלתי אפשר"],
  ["imprisoned", "כלוא"],
  ["improve", "לשפר"],
  ["improvise", "לאלתר"],
  ["in order", "תקין, מסודר"],
  ["increase", "להגדיל, להגביר"],
  ["incredible", "מדהים"],
  ["individual", "יחיד, אינדיבידואל"],
  ["industry", "תעשייה"],
  ["inferred", "נגזר, משתמע"],
  ["inform", "להודיע, לעדכן"],
  ["information", "מידע"],
  ["innovate", "לחדש, להמציא"],
  ["intention", "כוונה"],
  ["intentional", "מכוון"],
  ["interact", "לתקשר, להשפיע"],
  ["interest", "עניין"],
  ["interest", "ריבית"],
  ["internal", "פנימי"],
  ["interpretation", "פרשנות"],
  ["involve", "לערב"],
  ["isolate", "לבודד"],
  ["judgment", "שיפוט"],
  ["know, knew", "לדעת, ידע"],
  ["knowledge", "יֶדַע"],
  ["known", "ידוע"],
  ["laid", "מונח"],
  ["lane", "מסלול"],
  ["launch", "לשגר, להוציא לדרך"],
  ["launch", "להשיק, להתחיל"],
  ["limit", "גבול, לשים גבול, מוגבל"],
  ["limitation", "מגבלה"],
  ["lobby", "לובי, מבואה"],
  ["lobby", "לשדל"],
  ["mammal", "יונק"],
  ["moderate", "לתווך, לפשר"],
  ["moderate", "מתון"],
  ["modernize", "להפוך למודרני"],
  ["mold", "עובש"],
  ["mold", "לעצב"],
  ["motivate", "לדרבן"],
  ["negate", "לשלול"],
  ["neutral", "ניטרלי"],
  ["numerous", "מרובה"],
  ["nutrition", "תזונה"],
  ["object", "להתנגד"],
  ["object", "פריט, אובייקט"],
  ["obtain", "להשיג"],
  ["operate", "לנתח"],
  ["operate", "לפעול, להפעיל, לתפעל"],
  ["operation", "מבצע, פעולה"],
  ["operation", "ניתוח"],
  ["opposition", "אופוזיציה, התנגדות"],
  ["ordinary", "רגיל"],
  ["organ", "אורגן (כלי נגינה)"],
  ["organ", "איבר"],
  ["organization", "ארגון"],
  ["organize", "לארגן"],
  ["outbreak", "התפרצות"],
  ["overdo", "להפריז, להגזים"],
  ["overdue", "שעבר זמן ההגשה שלו"],
  ["pace", "קצב"],
  ["pair", "זוג"],
  ["parent", "הורה"],
  ["parenting", "הורות"],
  ["participate", "השתתף"],
  ["particular", "מיוחד, לא רגיל"],
  ["particulars", "פריטים"],
  ["pause", "הפסקה, להפסיק"],
  ["persist", "להתמיד, להתעקש"],
  ["person", "אדם"],
  ["personal", "אישי"],
  ["personality", "אישיות"],
  ["phase", "שלב, דרגה"],
  ["phenomenon", "תופעה"],
  ["pioneer", "חלוץ"],
  ["position", "מיקום, למקם"],
  ["position", "תנוחה"],
  ["position", "תפקיד, משרה"],
  ["possible", "אפשרי"],
  ["poverty", "עוני"],
  ["poverty-stricken", "מוכה עוני"],
  ["precedent", "תקדים"],
  ["preceding", "קודם"],
  ["predecessors", "קודמים"],
  ["predestined", "נקבע מראש"],
  ["predict", "לצפות מראש"],
  ["prediction", "חיזוי, ניבוי"],
  ["predictive", "נבואי"],
  ["premature", "מוקדם מדי"],
  ["private", "פרטי"],
  ["produce", "לייצר"],
  ["produce", "תוצר, ירקות ופירות"],
  ["product", "מוצר"],
  ["profession", "מקצוע"],
  ["professional", "מקצועי"],
  ["profound", "מעמיק"],
  ["profound", "מוחלט, מאוד"],
  ["profoundly", "עמוקות"],
  ["promise", "הבטחה, להבטיח"],
  ["property", "רכוש"],
  ["property", "תכונה"],
  ["protest", "למחות, הפגנה"],
  ["prove", "להוכיח"],
  ["public", "ציבורי"],
  ["race", "מרוץ"],
  ["race", "גזע"],
  ["rail", "מעקה, מסילה"],
  ["railroad", "מסילת רכבת"],
  ["random", "מקרי, אקראי"],
  ["randomly", "באקראיות"],
  ["reaction", "תגובה"],
  ["reasonable", "הגיוני"],
  ["reconstruct", "לשחזר"],
  ["refute", "להפריך"],
  ["regain", "להשיג מחדש"],
  ["regard", "להתייחס, להחשיב"],
  ["relate", "להתייחס, לקשר"],
  ["release", "לשחרר"],
  ["relevant", "רלוונטי, קשור"],
  ["relocate", "למקם מחדש"],
  ["reluctant", "מסויג, לא מעוניין"],
  ["rely", "להסתמך"],
  ["remote", "מרוחק"],
  ["report", "דיווח, לדווח"],
  ["reporter", "עיתונאי"],
  ["request", "בקשה, לבקש"],
  ["require", "לדרוש, דרישה"],
  ["restore", "לשקם, לשחזר"],
  ["resume", "להמשיך"],
  ["resumption", "חידוש"],
  ["rule", "כלל, חוק, שלטון"],
  ["rule", "לשלוט, לפסוק, להחליט"],
  ["ruler", "סרגל"],
  ["ruler", "מושל, שליט"],
  ["season", "לתבל"],
  ["season", "עונה"],
  ["secure", "להבטיח, לשמור, להגן"],
  ["selective", "סלקטיבי"],
  ["service", "שירות"],
  ["share", "מניה"],
  ["share", "לחלוק"],
  ["ship", "אוניה"],
  ["ship", "לשלוח"],
  ["shipment", "משלוח"],
  ["significance", "משמעות, חשיבות"],
  ["significant", "משמעותי"],
  ["simulate", "לדמות, לחקות"],
  ["size", "גודל"],
  ["soar", "להמריא"],
  ["soil", "לכלוך"],
  ["soil", "אדמה"],
  ["solicit", "לבקש/לחפש בתחינה"],
  ["solicit", "לשדל / להדיח"],
  ["solitude", "בדידות"],
  ["solution", "פתרון"],
  ["sort", "למיין"],
  ["source", "מקור"],
  ["span", "להימתח, להקיף"],
  ["span", "מרווח"],
  ["splendid", "נהדר, מהולל"],
  ["spring", "מעיין"],
  ["spring", "אביב"],
  ["spring, sprang", "קפיץ ; לקפוץ, קפץ"],
  ["stability", "יציבות"],
  ["stamina", "כושר עמידה, סיבולת"],
  ["standard", "רמה, תקן, מקובל"],
  ["state", "מצב"],
  ["state", "מדינה"],
  ["statement", "הצהרה"],
  ["steady", "קבוע, יציב"],
  ["stimulate", "לעורר, להמריץ"],
  ["stock", "מלאי"],
  ["stock", "לאחסן"],
  ["stock", "מניה"],
  ["strange", "מוזר"],
  ["strive", "לשאוף"],
  ["successor", "יורש"],
  ["summer", "קיץ"],
  ["superior", "עליון"],
  ["supervise", "לפקח"],
  ["support", "תמיכה, לתמוך"],
  ["supportive", "תומך"],
  ["survey", "לבחון, לסקור"],
  ["survey", "סקר"],
  ["survive", "לשרוד"],
  ["swift", "מהיר"],
  ["temporary", "זמני"],
  ["thick", "עבה"],
  ["thick", "סמיך"],
  ["thrive", "לשגשג"],
  ["tradition", "מסורת"],
  ["traffic", "תנועה"],
  ["traffic jam", "פקק תנועה"],
  ["transfer", "להעביר"],
  ["transfer", "העברה"],
  ["tribe", "שבט"],
  ["unaware", "לא מודע"],
  ["uncertain", "לא בטוח"],
  ["unclear", "לא ברור"],
  ["uncover", "לחשוף, לגלות"],
  ["unfold", "לפתוח קיפול"],
  ["unfold", "נפרש, נפתח, התגלה"],
  ["unit", "יחידה"],
  ["unstable", "לא יציב"],
  ["update", "עדכון, לעדכן"],
  ["upgrade", "לשדרג"],
  ["valid", "תקף"],
  ["validate", "אימת, נתן תוקף"],
  ["violence", "אלימות"],
  ["violent", "אלים"],
  ["widely", "בצורה נרחבת"],
  ["widen", "להרחיב"],
  ["winter", "חורף"]
]
