export default [
  ["10th - tenth", "עשירי"],
  ["1st - first", "ראשון"],
  ["2nd - second", "שני"],
  ["3rd - third", "שלישי"],
  ["4th - fourth", "רביעי"],
  ["5th - fifth", "חמישי"],
  ["6th - sixth", "שישי"],
  ["7th - seventh", "שביעי"],
  ["8th - eighth", "שמיני"],
  ["9th - ninth", "תשיעי"],
  ["about", "ליד, בערך"],
  ["about", "אודות"],
  ["above", "מעל"],
  ["above all", "מעל לכל"],
  ["absolutely", "לחלוטין"],
  ["according", "לפי"],
  ["accordingly", "בהתאם"],
  ["across", "בצד השני, לרוחב"],
  ["additionally", "בנוסף"],
  ["adjacent to", "ליד"],
  ["after", "אחרי"],
  ["after all", "אחרי הכל"],
  ["after all", "אחרי הכל"],
  ["afterwards", "לאחר מכן"],
  ["again", "שוב"],
  ["against", "כנגד, ממול"],
  ["ahead of", "לפני, לפנים"],
  ["albeit", "אף על פי"],
  ["all in all", "בסך הכל"],
  ["along", "לאורך"],
  ["along with", "יחד עם"],
  ["alongside", "לצד, במקביל"],
  ["also", "גם"],
  ["although", "למרות ש-"],
  ["altogether", "בסך הכל"],
  ["always", "תמיד"],
  ["amid", "בקרב, בין"],
  ["among", "בקרב, בין"],
  ["and", "ו-"],
  ["around", "מסביב"],
  ["as", "כאשר, כש-"],
  ["as", "כמו"],
  ["as a result", "כתוצאה"],
  ["as if", "כאילו"],
  ["as long as", "כל עוד"],
  ["as soon as", "כאשר, ברגע ש-"],
  ["as well as", "כמו גם"],
  ["aside from", "חוץ מ-"],
  ["at", "אצל, ב-"],
  ["at first", "בהתחלה"],
  ["at last", "סוף סוף"],
  ["backward", "לאחור"],
  ["based on", "מבוסס על"],
  ["because", "בגלל"],
  ["because of", "בגלל"],
  ["before", "לפני"],
  ["before", "לפני, מול"],
  ["behind", "מאחורי"],
  ["being that", "מכיוון ש-"],
  ["below", "מתחת"],
  ["beneath", "מתחת"],
  ["beside", "ליד"],
  ["besides", "בכל מקרה"],
  ["besides", "בנוסף על"],
  ["besides", "מלבד, חוץ מ-"],
  ["between", "בין"],
  ["beyond", "מעבר"],
  ["both", "שניהם"],
  ["both... and…", "גם... וגם..."],
  ["but", "אך, אבל"],
  ["but", "מלבד, חוץ מ-"],
  ["by", "ליד, בסמוך ל-"],
  ["by", "עד, לא יאוחר מ-"],
  ["certainly", "בהחלט, בוודאי"],
  ["chiefly", "בעיקר"],
  ["close", "קרוב"],
  ["comparatively", "באופן יחסי"],
  ["consequently", "כתוצאה מכך"],
  ["consistently", "בעקביות"],
  ["constantly", "באופן קבוע"],
  ["contradictory", "סותר"],
  ["contrary", "להפך, בניגוד ל-"],
  ["conversely", "לעומת זאת"],
  ["correspondingly", "בהתאמה"],
  ["coupled with", "יחד עם"],
  ["currently", "כרגע, נכון לעכשיו"],
  ["daily", "יומיומי"],
  ["despite", "למרות"],
  ["different from", "שונה מ-"],
  ["distant", "מרוחק"],
  ["down", "למטה"],
  ["due to", "בגלל, לאור"],
  ["during", "תוך כדי, במשך"],
  ["e.g.", "לדוגמה"],
  ["earlier", "קודם לכן"],
  ["either... or…", "או... או..."],
  ["elsewhere", "במקום אחר"],
  ["equally", "במידה שווה"],
  ["especially", "במיוחד"],
  ["essentially", "בעיקרו, במהותו"],
  ["even if", "גם אם"],
  ["even so", "אף על פי כן"],
  ["even though", "למרות ש-"],
  ["eventually", "לבסוף"],
  ["every day", "כל יום"],
  ["every now and then", "לפעמים"],
  ["except", "מלבד, חוץ מ-"],
  ["farther", "הלאה, יותר"],
  ["finally", "לבסוף, סוף סוף"],
  ["first of all", "ראשית"],
  ["for", "בגלל ש-"],
  ["for", "עבור"],
  ["for example", "לדוגמה"],
  ["for instance", "לדוגמה"],
  ["for the most part", "בדרך-כלל"],
  ["forever", "לנצח, לתמיד"],
  ["former", "קודם, לשעבר"],
  ["forward", "קדימה, לפנים"],
  ["frequently", "לעיתים קרובות"],
  ["from", "מ-"],
  ["from", "מ-"],
  ["from time to time", "מפעם לפעם"],
  ["further", "בהמשך"],
  ["further", "לקדם"],
  ["furthermore", "זאת ועוד"],
  ["given that", "בהתחשב בכך"],
  ["granted (that)", "בהנחה ש-, נתון ש-"],
  ["hardly ever", "כמעט אף פעם"],
  ["hence", "לפיכך, לכן"],
  ["here", "כאן"],
  ["how", "איך, כיצד"],
  ["however", "למרות זאת"],
  ["however", "בכל דרך"],
  ["i.e.", "כלומר, לדוגמה"],
  ["identically", "באופן זהה"],
  ["If", "אם"],
  ["immediately", "מיד"],
  ["in", "ב-, בתוך"],
  ["in a moment", "בעוד רגע"],
  ["in a word", "במילה אחת"],
  ["in addition", "בנוסף"],
  ["in case", "במקרה"],
  ["in comparison", "בהשוואה"],
  ["in conclusion", "לסיכום"],
  ["in contrast to", "בניגוד ל-"],
  ["in due time", "בבוא העת"],
  ["in fact", "למעשה"],
  ["in fact", "למעשה"],
  ["in front of", "בחזית של, מול"],
  ["in general", "באופן כללי"],
  ["in light of", "לאור"],
  ["in order to", "על-מנת, בכדי"],
  ["in other words", "במילים אחרות"],
  ["in particular", "במיוחד"],
  ["in spite of", "למרות"],
  ["in that case", "במקרה הזה"],
  ["in the same way", "באותו אופן"],
  ["incidentally", "דרך אגב"],
  ["including", "כולל"],
  ["indeed", "בהחלט"],
  ["initially", "בתחילה"],
  ["inside", "בתוך, פנים"],
  ["instantly", "מיד"],
  ["instead", "במקום"],
  ["instead of", "במקום"],
  ["into", "אל תוך"],
  ["just as", "בדיוק כמו"],
  ["just as… so…", "בדיוק כמו... גם"],
  ["last", "אחרון"],
  ["later", "מאוחר יותר"],
  ["latter", "שני, אחרון"],
  ["led to", "הוביל ל-"],
  ["left", "שמאלה"],
  ["like", "כמו"],
  ["likewise", "כמו-כן, באותו אופן"],
  ["mainly", "בעיקר"],
  ["markedly", "בצורה ניכרת"],
  ["meanwhile", "בינתיים"],
  ["moreover", "זאת ועוד"],
  ["mostly", "לרוב"],
  ["namely", "במיוחד, כלומר"],
  ["near", "קרוב"],
  ["nearby", "ליד, קרוב"],
  ["neither... nor…", "לא... ולא..."],
  ["never", "אף פעם"],
  ["nevertheless", "למרות זאת"],
  ["next", "הבא"],
  ["next to", "ליד"],
  ["nonetheless", "למרות זאת"],
  ["not only", "לא רק"],
  ["not only... but also…", "לא רק... אלא גם..."],
  ["not to mention", "שלא לדבר על"],
  ["not... but…", "לא... אבל..."],
  ["notably", "ראוי לציון"],
  ["now", "עכשיו"],
  ["occasionally", "מידי פעם"],
  ["of", "של, מ-"],
  ["of course", "כמובן, בוודאי"],
  ["of course… but…", "כמובן... אך..."],
  ["often", "לעיתים קרובות"],
  ["on", "על"],
  ["on one hand…on the other hand", "מצד אחד... מצד שני"],
  ["on the contrary", "בניגוד לכך"],
  ["on top of", "על, מעל"],
  ["once", "פעם (בעבר)"],
  ["once", "ברגע ש-"],
  ["once in a while", "מידי פעם"],
  ["only", "רק"],
  ["opposite", "מנוגד, ממול"],
  ["or", "או"],
  ["ordinarily", "בדרך-כלל"],
  ["otherwise", "אחרת"],
  ["outside", "חוץ"],
  ["outside", "בחוץ"],
  ["over", "על, מעל"],
  ["overall", "כולל, באופן כללי"],
  ["owing to", "הודות ל-"],
  ["particularly", "במיוחד, בפרט"],
  ["past", "עבר, שעבר"],
  ["permanently", "קבוע"],
  ["perpetually", "נצחי, לנצח"],
  ["presently", "כעת"],
  ["previously", "הקודם, לפני-כן"],
  ["primarily", "בעיקר"],
  ["prior to", "קודם ל-, לפני"],
  ["provided that", "בתנאי ש-"],
  ["rarely", "לעיתים נדירות"],
  ["rather", "עדיף"],
  ["rather than", "במקום, יותר מ-"],
  ["regardless", "למרות, ללא קשר"],
  ["regularly", "באופן קבוע"],
  ["right", "ימינה"],
  ["seldom", "לעיתים רחוקות"],
  ["shortly", "בקיצור, בקרוב"],
  ["sideways", "הצידה"],
  ["significantly", "באופן משמעותי"],
  ["similarly", "באופן דומה"],
  ["simultaneously", "בו זמנית"],
  ["since", "מאז"],
  ["since", "מכיוון ש-"],
  ["so", "אז, כך ש-, ולכן"],
  ["so long as", "כל עוד"],
  ["so that", "כך ש-"],
  ["sometimes", "לעיתים, לפעמים"],
  ["soon", "בהקדם, מוקדם"],
  ["specifically", "במיוחד"],
  ["still", "עדיין, למרות זאת"],
  ["subsequently", "כתוצאה מכך"],
  ["such as", "כמו למשל"],
  ["suddenly", "לפתע"],
  ["surely", "ללא ספק"],
  ["surprisingly", "במפתיע"],
  ["than", "מ-"],
  ["thanks to", "תודות ל-"],
  ["that", "ש-"],
  ["then", "אז"],
  ["then", "אז"],
  ["there", "שם"],
  ["therefore", "לכן"],
  ["though", "למרות זאת"],
  ["though", "למרות ש-"],
  ["thus", "לכן, כך ש-"],
  ["to begin with", "בתור התחלה"],
  ["to sum up", "כדי לסכם"],
  ["together with", "יחד עם"],
  ["too", "גם"],
  ["too", "יותר מידי"],
  ["toward", "אל, אל עבר"],
  ["truly", "באמת"],
  ["under", "מתחת"],
  ["underneath", "מתחת"],
  ["undoubtedly", "ללא ספק"],
  ["unless", "אלא אם כן"],
  ["unlike", "שלא כמו"],
  ["until", "עד ש-"],
  ["until now", "עד עתה"],
  ["up", "למעלה"],
  ["upon", "על"],
  ["upside down", "הפוך"],
  ["usually", "בדרך-כלל"],
  ["vice versa", "להיפך"],
  ["what", "מה, איזה"],
  ["when", "כאשר, כש-"],
  ["whenever", "כש-, מתישהו"],
  ["where", "היכן, איפה"],
  ["where", "בעוד ש-"],
  ["whereas", "בעוד ש-"],
  ["wherever", "בכל מקום, לא משנה היכן"],
  ["whether... or…", "בין אם... או..."],
  ["which", "איזה"],
  ["which", "אשר, ש-"],
  ["while", "כל עוד"],
  ["while", "בזמן ש-"],
  ["who", "מי, ש-"],
  ["whom", "מי"],
  ["whose", "אשר לו, אשר הוא"],
  ["why", "מדוע"],
  ["with", "באמצעות, עם"],
  ["within", "בתוך"],
  ["without", "מבלי, ללא"],
  ["yet", "עדיין, בכל זאת"],
  ["yet", "אך, אולם"]
] as const;
