export default [
  ["abrupt", "פתאומי"],
  ["absolute", "מוחלט"],
  ["accessible", "נגיש, זמין"],
  ["accomplish", "להשלים, להשיג"],
  ["accomplished", "מומחה, מעולה"],
  ["accomplishment", "הישג"],
  ["account", "להתחשב ב-, להתייחס ל-"],
  ["account", "חשבון"],
  ["accuracy", "דיוק"],
  ["accurate", "מדויק"],
  ["activist", "פעיל, אקטיביסט"],
  ["adapt", "להתאים"],
  ["adapt", "לעבד"],
  ["adapt", "להסתגל"],
  ["administer", "לנהל, לפקח"],
  ["administer", "לתת, לחלק"],
  ["administration", "מנהל"],
  ["admit", "להודות"],
  ["admit", "להכניס, לקבל לתוך קבוצה"],
  ["adult", "מבוגר"],
  ["adulthood", "בגרות"],
  ["advance", "מתקדם"],
  ["advancement", "התקדמות"],
  ["advancement", "מקדמה"],
  ["advantage", "יתרון"],
  ["advice", "עצה"],
  ["advise", "לייעץ"],
  ["advisor", "יועץ"],
  ["aesthetic", "אסתטיקה"],
  ["allocate", "להקצות"],
  ["announcement", "הכרזה"],
  ["annually", "שנתי"],
  ["appoint", "למנות"],
  ["approach", "גישה"],
  ["approximately", "בערך, בקירוב"],
  ["astronomy", "אסטרונומיה"],
  ["attention", "תשומת לב"],
  ["attribute", "לייחס, לקשר"],
  ["attribute", "תכונה, מאפיין"],
  ["aware", "מודע"],
  ["balance", "שיווי משקל"],
  ["balance", "איזון, לאזן"],
  ["ban", "חרם, איסור"],
  ["belief", "אמונה"],
  ["bend", "לכופף"],
  ["beware", "היזהר"],
  ["borrow", "להשאיל"],
  ["brief", "תדריך, תקציר"],
  ["briefly", "בקצרה"],
  ["bright", "בהיר, ברור"],
  ["by no means", "ללא ספק, בשום אופן"],
  ["by now", "עד עתה"],
  ["capable", "מסוגל, יכול"],
  ["capacity", "יכולת, סמכות, תפקיד"],
  ["capacity", "קיבולת"],
  ["capital", "עיר בירה"],
  ["capital", "ראשי, משמעותי"],
  ["capital", "הון"],
  ["capital", "אות גדולה"],
  ["capital punishment", "עונש מוות"],
  ["capitalize", "לנצל"],
  ["certain", "מסוים"],
  ["certain", "בטוח"],
  ["certainty", "וודאות"],
  ["character", "אות, תו"],
  ["character", "אופי"],
  ["character", "דמות"],
  ["characteristic", "מאפיין"],
  ["choice", "בחירה"],
  ["choose", "לבחור"],
  ["circumstance", "מצב, תנאי, נסיבות"],
  ["civil", "אזרחי"],
  ["civil", "אדיב"],
  ["class", "כיתה"],
  ["class", "מעמד"],
  ["class", "סוג"],
  ["classify", "לסווג, מסווג"],
  ["colony", "מושבה"],
  ["combine", "לצרף, לשלב"],
  ["common", "נפוץ, משותף"],
  ["communal", "משותף, ציבורי"],
  ["communicate", "לתקשר"],
  ["community", "קהילה"],
  ["company", "חברה"],
  ["comparable", "בר-השוואה"],
  ["compare", "להשוות"],
  ["comparison", "השוואה"],
  ["comprehend", "להבין"],
  ["comprehension", "הבנה"],
  ["concentrate", "להתרכז"],
  ["conclude", "לסיים"],
  ["conclude", "להסיק"],
  ["conclusion", "מסקנה"],
  ["conclusively", "סופית, באופן החלטי"],
  ["confirm", "לאשר, לאמת"],
  ["continuation", "המשך"],
  ["cooperation", "שיתוף פעולה"],
  ["core", "ליבה"],
  ["crisis", "משבר"],
  ["cure", "מרפא"],
  ["decide", "להחליט"],
  ["decline", "לרדת"],
  ["decline", "לדחות"],
  ["decline", "ירידה"],
  ["decrease", "ירידה, הפחתה"],
  ["decrease", "להפחית, לצמצם"],
  ["deduce", "להסיק"],
  ["demand", "לדרוש, דרישה"],
  ["deny", "לסרב"],
  ["deny", "להכחיש"],
  ["depart", "לעזוב"],
  ["derive", "לשאוב, להפיק, לגזור מ-"],
  ["descend", "ירד, הדרדר"],
  ["descendent", "צאצא"],
  ["deserve", "מגיע (לו)"],
  ["destiny", "גורל"],
  ["devote", "להקדיש"],
  ["direct", "לכוון"],
  ["direct", "לביים"],
  ["direct", "ישיר, כנה"],
  ["direction", "כיוון"],
  ["disadvantage", "חסרון"],
  ["disclose", "לגלות, לחשוף"],
  ["discover", "לגלות"],
  ["discoveries", "תגליות"],
  ["discuss", "לדון, להתווכח"],
  ["disprove", "להפריך"],
  ["distinct", "ברור, נפרד"],
  ["distress", "מצוקה"],
  ["diverge", "לסטות"],
  ["diversity", "מגוון"],
  ["divide", "לחלק"],
  ["doubt", "ספק, להטיל ספק"],
  ["edit", "לערוך"],
  ["edition", "מהדורה"],
  ["editor", "עורך"],
  ["emperor", "שליט, קיסר"],
  ["empire", "אימפריה"],
  ["enable", "לאפשר"],
  ["enormous", "עצום"],
  ["enough", "מספיק"],
  ["era", "עידן"],
  ["essential", "חיוני"],
  ["evaluate", "להעריך, לאמוד"],
  ["evaluation", "הערכה"],
  ["even", "אפילו"],
  ["even", "זוגי (מספר)"],
  ["even", "ליישר, להשוות"],
  ["evenly", "באופן שווה"],
  ["except for", "למעט"],
  ["exercise", "תרגיל"],
  ["exercise", "להתאמן"],
  ["exercise", "לממש, ליישם"],
  ["expect", "לצפות"],
  ["expectations", "ציפיות"],
  ["explain", "להסביר"],
  ["explanation", "הסבר"],
  ["express", "לבטא"],
  ["express", "מהיר"],
  ["expression", "ביטוי"],
  ["extreme", "קיצוני"],
  ["face", "פונה ל-, עם הפנים ל-"],
  ["face", "פנים"],
  ["facial", "שקשור בפנים"],
  ["financial", "כספי"],
  ["forbid", "לאסור"],
  ["form", "צורה"],
  ["form", "ליצור, להקים"],
  ["formal", "רשמי"],
  ["forth", "הלאה, קדימה"],
  ["general", "כללי"],
  ["General", "גנרל (דרגה צבאית)"],
  ["generally", "באופן כללי"],
  ["gross", "ענק, דוחה"],
  ["gross", "ברוטו, גלמי"],
  ["growth", "צמיחה, גדילה"],
  ["habit", "הרגל"],
  ["habitat", "סביבת מגורים"],
  ["health", "בריאות"],
  ["heavily", "מאוד, במידה רבה"],
  ["heavy", "כבד"],
  ["hope", "תקווה, לקוות"],
  ["human", "אנושי"],
  ["human being", "בן-אדם, אנוש"],
  ["identical", "זהה"],
  ["implicate", "לסבך, לערב"],
  ["implications", "השלכות, משמעות"],
  ["importance", "חשיבות"],
  ["important", "חשוב"],
  ["inadequate", "לקוי, לא מספיק"],
  ["income", "הכנסה"],
  ["incomprehensible", "לא מובן"],
  ["indicate", "להצביע על"],
  ["indication", "אינדיקציה, סימן ל-"],
  ["inhabit", "ליישב, לאכלס"],
  ["inhabitants", "תושבים"],
  ["initial", "התחלתי, ראשוני"],
  ["initial", "ראשי תיבות"],
  ["initiated", "יזם, התחיל, אִתְחֵל"],
  ["international", "בינלאומי"],
  ["island", "אי"],
  ["isle", "אי"],
  ["issue", "גיליון"],
  ["issue", "להוציא לאור, להפיץ"],
  ["issue", "נושא, עניין, סוגיה"],
  ["jewel", "תכשיט"],
  ["join", "להצטרף, לחבר"],
  ["joint", "משותף"],
  ["joint", "מפרק, חיבור"],
  ["judge", "לשפוט"],
  ["judge", "שופט"],
  ["lack", "מחסור"],
  ["language", "שפה"],
  ["large", "גדול"],
  ["largest", "הגדול ביותר"],
  ["law", "חוק"],
  ["lawyer", "עורך-דין"],
  ["legal", "משפטי"],
  ["legal", "חוקי"],
  ["legalize", "להפוך חוקי, לאשר"],
  ["less", "פחות"],
  ["lethal", "קטלני"],
  ["level", "רמה, דרגה, מפלס"],
  ["level", "לאזן, להשוות"],
  ["likely", "סביר"],
  ["local", "מקומי"],
  ["locate", "לאתר"],
  ["malfunction", "כשל, ליקוי"],
  ["massacre", "טֶבַח"],
  ["medicine", "רפואה, תרופה"],
  ["medieval", "מתקופת ימי הביניים"],
  ["merchandise", "מוצרים, סחורה"],
  ["mere", "רק, לא יותר מ-"],
  ["merely", "רק, לא יותר מ-"],
  ["middle", "אמצע"],
  ["mortal", "אנושי, בן תמותה"],
  ["mortal", "קטלני"],
  ["mortality", "תמותה"],
  ["most", "הכי"],
  ["most", "רוב"],
  ["mutually", "באופן שווה/הדדי"],
  ["nation", "אומה"],
  ["nationality", "לאום"],
  ["nationalize", "להלאים"],
  ["native", "יליד, מקומי, טבעי"],
  ["natural", "טבעי"],
  ["nature", "טבע"],
  ["need", "צריך, צורך"],
  ["negative", "שלילי"],
  ["network", "רשת"],
  ["new", "חדש"],
  ["newscaster", "מגיש חדשות"],
  ["newspaper", "עיתון"],
  ["note", "הערה, פתק"],
  ["note", "לציין"],
  ["noted", "ידוע, מפורסם"],
  ["obviously", "ברור"],
  ["occasion", "אירוע, סיבה, הזדמנות"],
  ["occasional", "מדי פעם, מקרי"],
  ["occasions", "הזדמנויות, מקרים"],
  ["occur", "קרה, התרחש"],
  ["offer", "הצעה, להציע"],
  ["official", "רשמי, מאושר"],
  ["officiate", "לכהן, לערוך"],
  ["oil", "נפט, שמן, לשמן"],
  ["ongoing", "מתמשך"],
  ["option", "אפשרות, אופציה"],
  ["order", "מסדר דתי"],
  ["order", "להזמין"],
  ["order", "לצוות"],
  ["orderly", "מסודר"],
  ["orientation", "התמצאות"],
  ["origin", "מקור, מוצא"],
  ["original", "מקורי"],
  ["originality", "מקוריות"],
  ["originate", "התחיל, התהווה"],
  ["outcome", "תוצאה"],
  ["overcome", "להתגבר"],
  ["part", "חלק"],
  ["partial", "חלקי"],
  ["patient", "סבלני"],
  ["patient", "חולה"],
  ["per", "לכל"],
  ["percent", "אחוז"],
  ["perfect", "מושלם"],
  ["perfect", "להשלים, לשפר"],
  ["pollution", "זיהום"],
  ["population", "אוכלוסייה"],
  ["possess", "להיות בעלים של, להחזיק ב-"],
  ["possession", "בעלות, חזקה"],
  ["precise", "מדויק"],
  ["precision", "דיוק"],
  ["presence", "נוכחות"],
  ["present", "להציג"],
  ["present", "מתנה"],
  ["present", "הווה, נוכח, קיים"],
  ["prime", "ראשוני, עיקרי, מובחר"],
  ["primitive", "קדום, חסר תרבות"],
  ["prior", "קודם"],
  ["priority", "עדיפות"],
  ["progress", "התקדמות, להתקדם"],
  ["progressive", "מתקדם ומתמשך"],
  ["proper", "מתאים, הולם"],
  ["properly", "כראוי"],
  ["protect", "להגן"],
  ["provide", "לספק"],
  ["provide", "לפרנס"],
  ["purpose", "כוונה, מטרה"],
  ["purposely", "בכוונה"],
  ["quiet", "שקט"],
  ["quite", "למדי"],
  ["quote", "ציטוט"],
  ["raise", "להעלות"],
  ["range", "מטווח"],
  ["range", "רכס"],
  ["range", "טווח"],
  ["rational", "הגיוני, רציונאלי"],
  ["rationalize", "להצדיק, להסביר"],
  ["reality", "מציאות"],
  ["reason", "סיבה"],
  ["reason", "הגיון"],
  ["recession", "מיתון"],
  ["recommend", "להמליץ"],
  ["recycle", "למחזר"],
  ["recycling", "מחזור"],
  ["reduce", "להפחית"],
  ["refer", "מתייחס"],
  ["reference", "התייחסות, הפניה"],
  ["refuse", "אשפה, זבל"],
  ["refuse", "לסרב"],
  ["regime", "שלטון, משטר"],
  ["regulation", "תקנה"],
  ["reign", "שלטון"],
  ["reigned", "משל, שלט"],
  ["relative", "יחסי"],
  ["relative", "קרוב-משפחה"],
  ["relatively", "בקרוב, באופן יחסי"],
  ["religion", "דת"],
  ["repeat", "לחזור"],
  ["repeat", "שידור/מאורע חוזר"],
  ["repetition", "חזרה"],
  ["reply", "להשיב"],
  ["research", "מחקר"],
  ["resist", "להתנגד"],
  ["resistance", "התנגדות, מחתרת"],
  ["resolve", "נחוש"],
  ["resolve", "לפתור"],
  ["result", "תוצאה"],
  ["result in", "הסתיים ב-"],
  ["reveal", "לחשוף"],
  ["review", "ביקורת"],
  ["review", "לסקור, סקירה"],
  ["rigid", "נוקשה, מחמיר"],
  ["rise", "עליה, לעלות"],
  ["rising", "עולה"],
  ["rising", "זריחה"],
  ["rocket", "טיל"],
  ["scene", "סצנה"],
  ["scene", "זירה"],
  ["scenery", "נוף"],
  ["science", "מדע"],
  ["scientist", "מדען"],
  ["section", "יחידה, חלק"],
  ["seem", "נראה כ-, דומה ל-"],
  ["sense", "היגיון, תודעה"],
  ["sense", "חוש, לחוש"],
  ["sensible", "נבון"],
  ["serious", "רציני, חמור"],
  ["shuttle", "מעבורת"],
  ["sign", "לחתום"],
  ["sign", "סימן, לסמן"],
  ["sign", "שֶׁלֶט"],
  ["signal", "אות, סימן, לאותת"],
  ["similar", "דומה"],
  ["simple", "פשוט"],
  ["simplify", "לפשט"],
  ["simply", "בפשטות"],
  ["social", "חברתי"],
  ["spacious", "מרווח"],
  ["square", "כיכר"],
  ["square", "ריבוע"],
  ["stand", "לעמוד"],
  ["standardize", "לתקנן"],
  ["subject", "נתון ל-, בכפוך ל-"],
  ["subject", "למסור, להעביר לבעלות אחר"],
  ["subject", "נתין, אזרח, אדם"],
  ["subject", "נושא"],
  ["subjective", "אישי, משוחד בדעתו"],
  ["suburban", "פרברי"],
  ["succeed", "הצליח"],
  ["success", "הצלחה"],
  ["sum", "סכום, סך, לסכם"],
  ["sum up", "לסכם"],
  ["summarize", "לסכם"],
  ["summary", "סיכום, תמצית"],
  ["surround", "להקיף"],
  ["surrounding", "מקיף, סובב"],
  ["task", "משימה"],
  ["territory", "תחום, שטח"],
  ["thereby", "ולכן, גרם ל-"],
  ["title", "כותרת"],
  ["touch", "מגע, לגעת"],
  ["trade", "להחליף"],
  ["trade", "לסחור, מסחר"],
  ["train", "להכשיר, לאמן"],
  ["train", "רכבת"],
  ["trial", "נסיון"],
  ["trial", "משפט"],
  ["turn", "לפנות, סיבוב"],
  ["uncharted", "לא מתועד"],
  ["uniform", "מדים"],
  ["uniform", "אחיד"],
  ["unify", "לאחד"],
  ["union", "איגוד, איחוד"],
  ["universe", "יקום"],
  ["uphold", "להחזיק, לתמוך, לדגול"],
  ["volume", "כרך"],
  ["volume", "עוצמת קול"],
  ["volume", "נפח"],
  ["war", "מלחמה"],
  ["warfare", "לוחמה"],
  ["warrior", "לוחם"],
  ["waste", "בזבוז, לבזבז"],
  ["waste", "הפסולת"],
  ["watch", "להסתכל, להשגיח"],
  ["watch", "שעון"],
  ["widespread", "נפוץ"],
  ["wild", "פראי, טבע"],
  ["wilderness", "ערבה, שממה"],
  ["wool", "צמר"]
] as const;
