export default [
  ["abstain", "להתנזר, להימנע ממשהו"],
  ["accentuate", "להבליט, להדגיש"],
  ["accusation", "האשמה"],
  ["acknowledge", "להכיר, לדעת"],
  ["adequate", "הולם"],
  ["advertise", "פרסום"],
  ["advertisement", "מודעה, פרסום"],
  ["affinity", "זיקה, קירבה"],
  ["affinity", "משיכה"],
  ["agitate", "להסעיר, לזעזע, לעצבן"],
  ["agonize", "לענות, לייסר"],
  ["agony", "ייסורים"],
  ["aisle", "מעבר"],
  ["alien", "חייזר"],
  ["alienation", "ניכור, הרחקה"],
  ["anchor", "עוגן"],
  ["annihilate", "להשמיד"],
  ["antique", "עתיק, ענתיקה"],
  ["apparatus", "מנגנון"],
  ["auction", "מכירה פומבית"],
  ["augment", "להרחיב"],
  ["autograph", "חתימה"],
  ["beg", "להתחנן"],
  ["burn", "לשרוף, להישרף"],
  ["cater", "לספק"],
  ["cathedral", "קתדרלה"],
  ["cattle", "בקר"],
  ["chariot", "מרכבה"],
  ["charity", "צדקה"],
  ["chase", "לרדוף, מרדף"],
  ["cheer", "לעודד"],
  ["cheerful", "עליז, שמח"],
  ["chemical", "כימיקל, כימי"],
  ["circuit", "מסלול, להקיף"],
  ["circuit", "מעגל חשמלי"],
  ["combat", "לתקוף"],
  ["combat", "קרב"],
  ["compete", "להתחרות, להתמודד"],
  ["competition", "תחרות"],
  ["components", "חלקים, מרכיבים"],
  ["compulsory", "מהווה חובה"],
  ["concise", "תמציתי, תכליתי"],
  ["concrete", "בטון"],
  ["concrete", "קונקרטי, מוחשי"],
  ["congregate", "לאסוף קהל, לאסוף"],
  ["conspicuous", "בולט"],
  ["conspiracy", "קשר, מזימה"],
  ["contagious", "מדבק"],
  ["contaminate", "לזהם"],
  ["correlate", "לתאם, לקשר"],
  ["corrupt", "להשחית, מושחת"],
  ["council", "מועצה"],
  ["counsel", "לייעץ, להדריך"],
  ["counsel", "פרקליט, יועץ"],
  ["counterpart", "בעל תפקיד מקביל, עמית, בן-זוג"],
  ["couple", "זוג, לצמד"],
  ["courage", "אומץ"],
  ["court", "מגרש (ספורט)"],
  ["court", "בית משפט"],
  ["courteous", "אדיב"],
  ["courtesy", "נימוס, אדיבות"],
  ["craft", "אומנות, מלאכה"],
  ["craft", "כלי טייס / כלי שייט"],
  ["craftsmen", "אומן, בעל מלאכה"],
  ["critique", "ביקורת"],
  ["cross", "לחצות"],
  ["cross", "צלב, להצליב"],
  ["crossroad", "צומת"],
  ["cruel", "אכזרי"],
  ["cult", "כת"],
  ["dawn", "שחר"],
  ["deal", "עסקה"],
  ["deal", "להתמודד"],
  ["dealt", "עסק ב, חולק (קלפים, ניירת)"],
  ["debt", "חוב"],
  ["decay", "ריקבון"],
  ["decipher", "לפענח"],
  ["delegate", "להאציל, להסמיך"],
  ["delinquent", "נזנח, נשכח"],
  ["delinquent", "עבריין"],
  ["depression", "דיכאון"],
  ["described", "מתואר"],
  ["description", "תיאור"],
  ["desirable", "נחשק"],
  ["desire", "תשוקה, חשק, לחפוץ"],
  ["despair", "להתייאש"],
  ["desperate", "נואש"],
  ["desperation", "ייאוש"],
  ["dimension", "מימד"],
  ["disagreement", "חוסר הסכמה"],
  ["disappear", "להעלם"],
  ["disappoint", "לאכזב"],
  ["disapproving", "לא מאשר, לא מסכים, לא מרוצה"],
  ["disciples", "תלמידים"],
  ["discipline", "תחום לימוד/מחקר"],
  ["discipline", "להעניש, לחנך, משמעת"],
  ["disciplined", "חינך, העניש"],
  ["disciplined", "ממושמע"],
  ["discontent", "חוסר שביעות רצון"],
  ["discourage", "לשכנע שלא לעשות משהו"],
  ["discrepancy", "סתירה, פער"],
  ["disease", "מחלה"],
  ["disinfection", "חיטוי"],
  ["dislocate", "לפרוק, לנקוע"],
  ["disparage", "לזלזל, להמעיט בערך"],
  ["dissent", "להתנגד, חילוקי דעות"],
  ["distinction", "מצוינות"],
  ["distinction", "הפרדה"],
  ["distinctive", "מיוחד"],
  ["distinguish", "להבדיל, להבחין"],
  ["disturb", "להפריע"],
  ["disturbance", "הפרעה"],
  ["dominate", "לשלוט"],
  ["dozen", "תריסר"],
  ["drought", "בצורת"],
  ["duel", "דו-קרב"],
  ["duplicate", "לשכפל"],
  ["durable", "יציב, מתמשך"],
  ["dynasty", "שושלת"],
  ["eliminate", "לחסל, לפסול"],
  ["eloquent", "רהוט"],
  ["elude", "לברוח, להתחמק"],
  ["embrace", "לחבק, לאמץ לקרבו"],
  ["emission", "פליטה"],
  ["employ", "להעסיק"],
  ["employer", "מעסיק, מעביד"],
  ["enclosing", "לסגור, להקיף"],
  ["enclosure", "סגירה, כיתור, שטח מגודר"],
  ["encounter", "מפגש"],
  ["endanger", "לסכן"],
  ["endangered", "בסכנת הכחדה"],
  ["endurance", "כוח סבל"],
  ["endure", "לסבול, להחזיק מעמד"],
  ["enforce", "לאכוף, לכפות"],
  ["Equator", "קו המשווה"],
  ["equip", "לצייד"],
  ["equipment", "ציוד"],
  ["erupt", "התפרץ"],
  ["estate", "אחוזה"],
  ["estate", "נכס"],
  ["expense", "הוצאות"],
  ["expensive", "יקר"],
  ["fabric", "בד"],
  ["fabricate", "לבדות"],
  ["family", "משפחה"],
  ["fatal", "סופני (פטלי)"],
  ["fate", "גורל, חרץ גורל"],
  ["fellow", "חבר, עמית"],
  ["fiction", "בדיון, לא אמיתי"],
  ["file", "תיק, קובץ"],
  ["fingerprint", "טביעת אצבע"],
  ["flame", "להבה"],
  ["flatter", "שטוח יותר"],
  ["flatter", "להחמיא"],
  ["flattery", "חנופה"],
  ["flock", "לנהור, עדר, המון"],
  ["flood", "שיטפון"],
  ["fragile", "עדין, שביר"],
  ["gauge", "למדוד, להעריך, מידה"],
  ["generous", "נדיב"],
  ["genes", "גנים"],
  ["gesture", "מחווה"],
  ["given", "נתון"],
  ["grade", "כיתה"],
  ["grade", "ציון, דרגה, מעמד"],
  ["grade", "שיפוע"],
  ["gradually", "בהדרגה"],
  ["graduate", "לסיים לימודים"],
  ["grand", "גדול, כולל, מרשים"],
  ["granddaughter", "נכדה"],
  ["grandfather", "סבא"],
  ["grandmother", "סבתא"],
  ["grandson", "נכד"],
  ["guess", "ניחוש, לנחש"],
  ["guidance", "הנחיה, הכוונה, הנהגה"],
  ["guide", "להדריך"],
  ["gunpowder", "אבק שריפה"],
  ["hail", "לשבח"],
  ["hail", "ברד"],
  ["hall", "מסדרון"],
  ["hall", "היכל"],
  ["harm", "לפגוע, להזיק"],
  ["harness", "לרתום"],
  ["herb", "עשב"],
  ["herd", "לאסוף"],
  ["herd", "עדר, לרעות"],
  ["heritage", "מורשת"],
  ["husband", "בעל"],
  ["illness", "מחלה"],
  ["illustrate", "להמחיש, להדגיש"],
  ["illustrator", "מאייר"],
  ["immersion", "שקיעה"],
  ["immoral", "לא מוסרי"],
  ["implement", "ליישם, להוציא לפועל"],
  ["implementation", "מימוש, יישום, ביצוע"],
  ["incident", "תקרית"],
  ["incompetence", "חוסר יכולת"],
  ["incorporate", "לכלול, לשתף, לאגד"],
  ["indefinitely", "ללא הגבלה"],
  ["independence", "עצמאות"],
  ["independent", "עצמאי"],
  ["inevitable", "בלתי נמנע"],
  ["infectious", "מדבק"],
  ["inferior", "נחות"],
  ["infiltrate", "להסתנן"],
  ["influence", "השפעה, להשפיע"],
  ["insight", "תובנה"],
  ["instrument", "כלי"],
  ["insurmountable", "שאין להתגבר עליו"],
  ["intellectual", "אינטלקטואלי"],
  ["interview", "לראיין, ראיון"],
  ["introduce", "להציג, לעשות היכרות"],
  ["introduction", "הקדמה, מבוא, היכרות"],
  ["invade", "לחדור, לפלוש"],
  ["invaders", "פולשים"],
  ["investigate", "לחקור"],
  ["invoke", "לעורר, לזמן"],
  ["irregular", "לא רגיל"],
  ["irresistible", "שלא ניתן לעמוד בפניו"],
  ["justify", "להצדיק"],
  ["knife (knives)", "סכין (סכינים)"],
  ["label", "תגית"],
  ["label", "לתייג"],
  ["labor", "להתאמץ"],
  ["labor", "עבודה, עמל, לעמול"],
  ["laboratory", "מעבדה"],
  ["laborer", "פועל"],
  ["layer", "שכבה"],
  ["lead, led", "להוביל, הוביל"],
  ["leader", "מנהיג"],
  ["leadership", "מנהיגות"],
  ["lie", "לשקר, שֶקֶר"],
  ["lie, lay", "לשכב, שכב"],
  ["listen", "להקשיב"],
  ["loosely", "באופן רפוי"],
  ["loud", "חזק"],
  ["loudspeaker", "רמקול"],
  ["luxury", "מותרות"],
  ["machine", "מכונה"],
  ["manufacture", "ייצר"],
  ["march", "לצעוד"],
  ["margin", "שוליים, מרווח"],
  ["martial", "צבאי, קרבי"],
  ["master", "להתמחות, לשלוט"],
  ["master", "אדון, שליט"],
  ["masterpiece", "יצירת מופת"],
  ["mastery", "מומחיות"],
  ["match", "גפרור"],
  ["match", "התאמה, להתאים"],
  ["melt", "להמיס"],
  ["mind", "שכל"],
  ["mind", "אכפת"],
  ["mind", "לשים לב, לשמור"],
  ["missile", "טיל"],
  ["mobilize", "לנייד, להניע"],
  ["mole", "חפרפרת"],
  ["mole", "שומה"],
  ["myriad", "רב, הרבה"],
  ["narrow", "צר"],
  ["navigate", "לנווט"],
  ["nervous", "עצבני, לחוץ, מתוח"],
  ["nobility", "אצולה"],
  ["noble", "אציל, אצילי"],
  ["notion", "רעיון, מושג, נטיה"],
  ["novel", "רומן, סיפור"],
  ["novel", "חדש"],
  ["observation", "אבחנה"],
  ["observe", "להתבונן, להבחין"],
  ["obstinate", "עקשן"],
  ["offend", "להעליב"],
  ["offender", "פושע, פוגע"],
  ["offensive", "מעליב, פוגעני"],
  ["oppressive", "אכזרי"],
  ["oppressive", "מדכא, מעיק"],
  ["ornament", "קישוט"],
  ["outdated", "מיושן"],
  ["outspoken", "מדבר גלויות, ישיר"],
  ["outstanding", "יוצא מן הכלל, מצוין"],
  ["overtake", "לעקוף, להשיג"],
  ["pain", "כאב, להכאיב"],
  ["passive", "סביל"],
  ["pervasive", "מתפשט, מחלחל"],
  ["petition", "עצומה, עתירה, לעתור"],
  ["picture", "תמונה, לצלם"],
  ["picture", "לדמיין"],
  ["play", "משחק, לשחק"],
  ["play", "מחזה"],
  ["playwright", "מחזאי"],
  ["policy", "מדיניות"],
  ["potent", "חזק, בעל כוח השפעה"],
  ["potential", "אפשרי, פוטנציאלי"],
  ["prejudice", "דעה קדומה"],
  ["prevalent", "נפוץ, שכיח, רווח"],
  ["pride", "גאווה"],
  ["prison", "כלא"],
  ["prophecy", "נבואה"],
  ["prosper", "לשגשג"],
  ["province", "מחוז, אזור"],
  ["provoke", "להתגרות, להסית"],
  ["punctuate", "הדגשה"],
  ["punctuation", "ניקוד, פיסוק"],
  ["pure", "טהור"],
  ["purification", "טיהור"],
  ["query", "שאלה, חקירה"],
  ["rapid", "מהיר"],
  ["rapid", "אֶשֶד, זרם מים מהיר בנהר"],
  ["rapidly", "במהירות"],
  ["reader", "קורא"],
  ["rebuttal", "הפרכה, סתירה"],
  ["recognize", "לזהות"],
  ["recollection", "זיכרון"],
  ["recordings", "הקלטות"],
  ["recruit", "לגייס"],
  ["recur", "קרה שוב"],
  ["recurring", "חוזר, נשנה"],
  ["refined", "מעודן, מלוטש"],
  ["reflect", "להרהר"],
  ["reflect", "לשקף, להחזיר אור"],
  ["reflection", "השתקפות"],
  ["refugee", "פליט"],
  ["reinforce", "לתגבר, לחזק"],
  ["relapse", "הדרדר, הישנות"],
  ["relating", "מתייחס"],
  ["relations", "יחסים"],
  ["remarkable", "ראוי לציון, יוצא דופן"],
  ["rival", "יריב"],
  ["rivalry", "יריבות"],
  ["rodent", "מכרסם"],
  ["role", "תפקיד"],
  ["rural", "כפרי"],
  ["satellite", "לווין"],
  ["satisfy", "לרצות, לספק"],
  ["scarce", "נדיר"],
  ["scholar", "אקדמאי, בעל מלגה, מלומד"],
  ["score", "לחתוך, לחרוץ"],
  ["score", "לזכות בניקוד"],
  ["score", "תוצאה"],
  ["secular", "חילוני"],
  ["senior", "בכיר"],
  ["senior", "זקן"],
  ["sensation", "תחושה"],
  ["sensations", "חדשות מרעישות"],
  ["set up", "להרכיב, לארגן, לסדר"],
  ["sheet", "דף"],
  ["sheet", "סדין"],
  ["sight", "ראייה, כוונת"],
  ["sighting", "תצפית, מראה"],
  ["silver", "כסף, כסוף"],
  ["sink", "כיור"],
  ["sink", "לשקוע"],
  ["skin", "עור"],
  ["skinned", "פשט עור"],
  ["slander", "השמצה, להשמיץ"],
  ["slight", "קל, מעט"],
  ["speak, spoke", "לדבר, דיבר"],
  ["speaker", "דובר"],
  ["spell", "כישוף, קסם"],
  ["spell", "איות, לאיית"],
  ["spend", "לבלות, להעביר"],
  ["spend", "לבזבז, לפזר"],
  ["spill", "לשפוך"],
  ["spot", "כתם"],
  ["spot", "לזהות"],
  ["sprang", "נבע"],
  ["stadium", "אצטדיון"],
  ["stark", "שומם, עזוב"],
  ["stark", "בוטה, מוחלט, גמור"],
  ["statue", "פסל"],
  ["steel", "פלדה"],
  ["stiff", "נוקשה"],
  ["storage", "אחסון"],
  ["strain", "מתח נפשי"],
  ["strain", "להתאמץ, למתוח, לנקוע"],
  ["strength", "חוזק"],
  ["strengthen", "לחזק"],
  ["struggle", "מאבק, מאמץ"],
  ["stuck", "תקוע"],
  ["suffer", "לסבול"],
  ["sundown", "שקיעה"],
  ["sunlight", "אור יום"],
  ["supreme", "עליון"],
  ["surprise", "הפתעה"],
  ["swing", "לנדנד, נדנדה"],
  ["switch", "מתג"],
  ["switch", "להחליף"],
  ["symptom", "סימפטום"],
  ["tempt", "לפתות"],
  ["tend", "נוטה"],
  ["tender", "רך"],
  ["threaten", "לאיים"],
  ["tilt", "להטות, שיפוע"],
  ["timid", "ביישן"],
  ["topic", "נושא"],
  ["tower", "מגדל"],
  ["toxic", "רעיל"],
  ["trace", "לעקוב, למצוא"],
  ["trace", "סימן, עִקְבָה"],
  ["track", "מסילה, מסלול,"],
  ["track", "לעקוב"],
  ["transform", "לשנות צורה"],
  ["translate", "לתרגם"],
  ["translator", "מתרגם"],
  ["transmit", "לשדר"],
  ["transmitter", "משדר"],
  ["transplant", "לשתול"],
  ["trap", "מלכודת"],
  ["triumph", "ניצחון"],
  ["tropical", "טרופי"],
  ["truth", "אמת"],
  ["tube", "צינור"],
  ["twist", "סיבוך, סיבוב"],
  ["unconscious", "מחוסר הכרה"],
  ["unjust", "לא צודק"],
  ["vagueness", "עמימות, ערפול"],
  ["vanish", "להיעלם"],
  ["vegetable", "ירק"],
  ["vegetarian", "צמחוני"],
  ["vehicle", "כלי רכב"],
  ["veracity", "יושר, הגינות"],
  ["verdict", "פסק דין, פסיקה"],
  ["voyage", "מסע"],
  ["want", "לרצות"],
  ["wanted", "מבוקש"],
  ["warmth", "חום"],
  ["wealth", "עושר"],
  ["welfare", "סעד"],
  ["wheat", "חיטה"],
  ["wildlife", "חיות בר"],
  ["wind", "למתוח"],
  ["wind", "רוח"],
  ["wing", "כנף"],
  ["withstand", "להתמודד, לעמוד ב-"]
] as const;
