export default [
  ["quake", "רעד"],
  ["nurture", "לטפח, לחנך, להזין"],
  ["hypocrisy", "צביעות"],
  ["disinfect", "לחטא"],
  ["conservation", "שימור"],
  ["empathy", "הזדהות, אמפתיה"],
  ["patience", "סבלנות"],
  ["sensation", "תחושה"],
  ["loudspeaker", "רמקול"],
  ["shatter", "לקעקע, לנפץ, להרוס"],
  ["disappointment", "אכזבה"],
  ["faulty", "לקוי, לא תקין"],
  ["transition", "מעבר, שינוי"],
  ["mock", "ללעוג"],
  ["hegemony", "הגמוניה"],
  ["civilize", "לתרבת"],
  ["authoritative", "מהימן, סמכותי"],
  ["harmony", "הרמוניה"],
  ["poignant", "חריף, נוקב"],
  ["engrave", "לחרוט"],
  ["robe", "חלוק"],
  ["brutish", "בהמי, אכזרי"],
  ["emission", "פליטה"],
  ["atrocity", "זוועה"],
  ["hostility", "עוינות"],
  ["perplexed", "לחוש בלבול ודאגה"],
  ["frog", "צפרדע"],
  ["fascination", "קסם, משיכה"],
  ["abstain", "להתנזר, להימנע ממשהו"],
  ["arousing", "מעורר"],
  ["diversion", "פעילות לשעות הפנאי, פעולת הסחה, הטיה"],
  ["recur", "קרה שוב"],
  ["slant", "אלכסון, נטייה"],
  ["oblige", "לחייב, להכריח"],
  ["casino", "קזינו"],
  ["impartially", "ללא אפליה, באופן הוגן"],
  ["discord", "צרימה, מחלוקת, סכסוך"],
  ["intervention", "התערבות"],
  ["tact", "טקט"],
  ["illuminate", "להאיר"],
  ["revision", "בדיקה מחדש לצורך שיפור"],
  ["nobility", "הטובות, אצולה, התכונות התרומיות"],
  ["sailor", "ימאי"],
  ["roast", "לקלות, צלי"],
  ["applaud", "למחוא כף, מחא כפיים, הריע, להריע"],
  ["awe inspiring", "מעורר יראת כבוד"],
  ["sculpture", "פסל"],
  ["seizure", "התקף"],
  ["emphasize", "להדגיש"],
  ["unofficial", "בלתי רשמי"],
  ["cloak", "מסווה, להסוות"],
  ["ridicule", "ללעוג, לעג"],
  ["civilization", "תרבות"],
  ["outgrowth", "תוצאה טבעית של משהו"],
  ["confession", "וידוי"],
  ["collision", "התנגשות"],
  ["syrup", "סירופ"],
  ["susceptible", "רגישות, פגיע, מועד, רגיש"],
  ["contradict", "לסתור"],
  ["astonish", "מדהים, להדהים"],
  ["tolerance", "סיבולת, סובלנות"],
  ["misty", "מעורפל"],
  ["responsibility", "אחריות"],
  ["conspicuous", "בולט"],
  ["confiscate", "להחרים"],
  ["tension", "מתח"],
  ["rainbow", "קשת"],
  ["astound", "להדהים"],
  ["heartthrob", "פעימת לב"],
  ["concerted", "מתואם"],
  ["prank", "מתיחה"],
  ["glove", "כפפה"],
  ["resumption", "חידוש"],
  ["sponsor", "נותן חסות"],
  ["monk", "נזיר"],
  ["expend", "לגמור, לבזבז, לפזר"],
  ["opportune", "משהו שקרה בעיתוי מוצלח"],
  ["restriction", "הגבלה"],
  ["tame", "לאלף, לבית"],
  ["unexplored", "לא נבדק, לא נחקר"],
  ["rebellion", "מרד"],
  ["delinquent", "עבריין, נשכח, נזנח"],
  ["deduction", "מסקנה, היקש (לוגי)"],
  ["sprang", "נבע"],
  ["docile", "כנוע, נח, קל לשליטה, צייתן"],
  ["lifestyle", "אורח חיים"],
  ["indebted", "חייב ל-, אסיר תודה"],
  ["accumulation", "הצטברות"],
  ["harness", "לרתום"],
  ["timeline", "ציר זמן"],
  ["cavity", "חור"],
  ["keystone", "אבן מפתח"],
  ["dwell", "להתגורר"],
  ["fracture", "לשבור, שבר"],
  ["impartiality", "הגינות, ניטרליות"],
  ["obedience", "משמעת, ציות, צייתנות"],
  ["plunge", "טבילה"],
  ["incidence", "כמות, הקרות (משהו שקורה)"],
  ["treatment", "טיפול"],
  ["surreptitiously", "באופן חשאי, סודי"],
  ["recipient", "נמען"],
  ["recuperate", "להחלים"],
  ["prick", "לדקור"],
  ["surpass", "לעלות על, להצטיין"],
  ["intelligence", "אינטליגנציה, מודיעין"],
  ["dictator", "דיקטטור, עריץ"],
  ["dwelling", "בית, משכן"],
  ["adherence", "דבקות, היצמדות, הידבקות"],
  ["outweigh", "שוקל יותר מ-, עולה על"],
  ["implementation", "יישום, מימוש, ביצוע"],
  ["existence", "קיום"],
  ["kite", "עפיפון"],
  ["reproduction", "שחזור"],
  ["vengeance", "נקמה"],
  ["dandy", "גנדרני"],
  ["artifact", "חפץ, פריט אומנות"],
  ["aura", "הילה"],
  ["devoid", "חסר, נטול"],
  ["implication", "להיות מעורב, רמז"],
  ["distortion", "עיוות, סילוף"],
  ["blindness", "עיוורון"],
  ["monkey", "קוף"],
  ["exotic", "מארץ זרה, אקזוטי"],
  ["maximize", "למקסם"],
  ["philosophy", "פילוסופיה"],
  ["elude", "לברוח, להתחמק"],
  ["portray", "לתאר, לצייר"],
  ["eel", "צלופח"],
  ["rainfall", "ירידת גשמים"],
  ["propaganda", "תעמולה"],
  ["contributory", "מסייע, תורם"],
  ["revolt", "מרד"],
  ["anesthesia", "הרדמה"],
  ["mischief", "מעשה קונדס, נזק"],
  ["pivot", "לסובב על ציר, ציר"],
  ["bolster", "לתמוך"],
  ["ironic", "אירוני"],
  ["illusion", "אשליה"],
  ["lineage", "שושלת, ייחוס"],
  ["imitate", "לחקות"],
  ["scorn", "לבוז, מנודה, לזלזל"],
  ["drawback", "עיכוב, חסרון"],
  ["impulsively", "ללא שיקול דעת"],
  ["insulation", "בידוד"],
  ["predestined", "נקבע מראש"],
  ["dental", "שקשור בשיניים"],
  ["esteemed", "מכובד"],
  ["emit", "להוציא, לפלוט"],
  ["knife (knives)", "סכין (סכינים)"],
  ["magnificent", "מדהים"],
  ["dagger", "פגיון"],
  ["peach", "אפרסק"],
  ["commends", "לציין לשבח"],
  ["consequential", "מכריע, חשוב"],
  ["reconstruct", "לשחזר"],
  ["pigeon", "יונה"],
  ["worm", "תולעת"],
  ["segment", "מקטע, קטע"],
  ["stalk", "להטריד, לעקוב"],
  ["iceberg", "קרחון"],
  ["spontaneously", "ללא תכנון"],
  ["usher", "סדרן"],
  ["villain", "נבל, רשע"],
  ["shave", "גילוח, לגלח"],
  ["grocery", "מכולת"],
  ["indefinitely", "ללא הגבלה"],
  ["butcher", "קצב, לשחוט"],
  ["enthusiasm", "התלהבות"],
  ["transcript", "פרוטוקול, תמליל"],
  ["humility", "ענוה"],
  ["demonstration", "הוכחה, הדגמה, הפגנה"],
  ["infectious", "מדבק"],
  ["entertainment", "בידור"],
  ["unforgettable", "בלתי נשכח"],
  ["moth", "עש"],
  ["stove", "תנור, כיריים"],
  ["divergence", "התפצלות, סטייה"],
  ["edible", "אכיל"],
  ["odor", "ניחוח, ריח"],
  ["insistence", "התעקשות, עקשנות"],
  ["laborer", "פועל"],
  ["absorption", "ספיגה"],
  ["incline", "שיפוע, לנטות, להתאים"],
  ["dilemma", "התלבטות בין שתי ברירות, בעיה, דילמה"],
  ["entwine", "לשלב, לקלוע, לשזור"],
  ["jog", "ג'וגינג, ריצה, לרוץ"],
  ["diffusion", "תערובת"],
  ["industrious", "שקדן, חרוץ"],
  ["discrepancy", "פער, העדר הסכמה, שוני, אי התאמה, סתירה"],
  ["pottery", "קדרות"],
  ["dwarf", "לגמד, גמד"],
  ["defamation", "הכפשה, השמצה"],
  ["immigrate", "להגר"],
  ["dentist", "רופא שיניים"],
  ["overrate", "להעריך יתר על המידה"],
  ["jungle", "ג'ונגל"],
  ["vinegar", "חומץ"],
  ["engagement", "העסקה, התחייבות, אירוסין"],
  ["hinder", "לעכב"],
  ["sighting", "תצפית, מראה"],
  ["reap", "לקצור"],
  ["cereal", "דגני בוקר"],
  ["opportunism", "ניצול כל הזדמנות לרווח"],
  ["excavation", "חפירה"],
  ["gunpowder", "אבק שריפה"],
  ["agitate", "לעצבן, להסעיר, לזעזע"],
  ["utilize", "השתמש"],
  ["reborn", "נולד מחדש"],
  ["temperament", "מזג, אופי"],
  ["illusive", "מתעתע, מטעה"],
  ["harass", "להציק"],
  ["ivory", "שנהב"],
  ["correlate", "לקשר, לתאם"],
  ["flattery", "חנופה"],
  ["mosquito", "יתוש"],
  ["minimize", "להקטין למינימום, למזער"],
  ["pharmacy", "בית מרקחת"],
  ["clarification", "טיהור, הבהרה"],
  ["bleak", "עגום"],
  ["enrich", "להעשיר"],
  ["gratify", "לרצות"],
  ["sequence", "רצף"],
  ["instrument", "כלי"],
  ["proponent", "תומך"],
  ["wickedly", "ברשעות"],
  ["inhibit", "לרסן"],
  ["saga", "סיפור, סאגה"],
  ["robbery", "שוד"],
  ["coordination", "תיאום, קואורדינציה"],
  ["underlies", "נמצא מתחת ל-, מונח ביסוד"],
  ["revived", "התחדש, קם לתחייה"],
  ["extraordinary", "בלתי רגיל"],
  ["stunned", "נדהם, היה המום"],
  ["situate", "למקם"],
  ["distinction", "אבחנה, הצטיינות, ייחוד, מצוינות, הפרדה"],
  ["onion", "בצל"],
  ["disgust", "להגעיל, גועל"],
  ["paradox", "פרדוקס, סתירה"],
  ["reconciliation", "פיוס"],
  ["livelihood", "מחיה"],
  ["bland", "תפל"],
  ["vocabulary", "אוצר מילים"],
  ["brightness", "בהירות"],
  ["weave", "לטוות, לארוג"],
  ["camel", "גמל"],
  ["superfluous", "מיותר, עודף"],
  ["plight", "סכנה, צרה"],
  ["ascribe", "לייחס, לשייך"],
  ["retirement", "פרישה"],
  ["revolution", "מהפכה"],
  ["eyesight", "ראייה, כוונת"],
  ["forgive", "לסלוח"],
  ["persecution", "רדיפה (דתית)"],
  ["unimaginable", "בלתי נתפס"],
  ["conscientious", "מודרך על יד מצפונו"],
  ["extinction", "הכחדה"],
  ["splendor", "פאר"],
  ["playwright", "מחזאי"],
  ["spring, sprang", "קפץ, קפיץ, לקפוץ"],
  ["contagious", "מדבק"],
  ["strenuous", "קשה, מאמץ"],
  ["assertion", "טענה תקיפה, טענה"],
  ["coffin", "ארון מתים"],
  ["eminence", "חשיבות"],
  ["foresee", "לחזות מראש, לצפות מראש"],
  ["envelope", "מעטפה"],
  ["infiltrate", "להסתנן"],
  ["vaccination", "חיסון"],
  ["outspoken", "מדבר גלויות, ישיר"],
  ["masculine", "גברי"],
  ["recurring", "נשנה, חוזר"],
  ["sticky", "דביק"],
  ["temptation", "פיתוי"],
  ["wrought", "מחושל, מעוצב"],
  ["equivocal", "שאינו חד משמעי"],
  ["emigration", "הגירה"],
  ["forerunner", "אות, מבשר, סימן מבשר באות, חלוץ, שליח"],
  ["bottomless", "ללא תחתית"],
  ["legible", "קריא"],
  ["slaughter", "טבח, לשחוט, לטבוח"],
  ["impregnable", "בלתי מנוצח, שאין להכניעו"],
  ["ceaseless", "ללא הפסק"],
  ["ecological", "אקולוגי"],
  ["cornerstone", "אבן פינה"],
  ["expel", "להשעות, להרחיק"],
  ["autograph", "חתימה"],
  ["preclude", "למנוע מאירוע להתקיים"],
  ["luminous", "מאיר, בוהק, זוהר"],
  ["rhyme", "חרוז"],
  ["patiently", "בסבלנות"],
  ["double standard", "מוסר כפול"],
  ["verifiable", "בר אימות, ניתן לבירור"],
  ["lurking", "אורב, מתגנב"],
  ["disdain", "בוז, זלזול"],
  ["[to] inspect", "לבדוק"],
  ["prejudicial", "גזעני"],
  ["pregnancy", "הריון"],
  ["granddaughter", "נכדה"],
  ["lame", "צולע"],
  ["enlist", "לגייס, להתגייס"],
  ["trim", "לגזום"],
  ["implement", "ליישם, להוציא לפועל"],
  ["marble", "גולה, שיש"],
  ["bead", "חרוז"],
  ["rebuttal", "הפרכה, סתירה"],
  ["fluency", "שטף"],
  ["ode", "שיר הלל"],
  ["purse", "ארנק"],
  ["rudimentary", "בסיסי, יסודי"],
  ["transaction", "עסקה"],
  ["embryo", "עובר"],
  ["dart", "חץ"],
  ["photograph", "לצלם, צילום"],
  ["[to] legislate", "לחוקק"],
  ["separately", "בנפרד"],
  ["numb", "חסר תחושה, רדום"],
  ["rotary", "נע על ציר סיבובי"],
  ["expedite", "לזרז"],
  ["eavesdrop", "לצותת"],
  ["injure", "לפצוע"],
  ["oppress", "לדכא"],
  ["grit", "לכלוך, גרגרים"],
  ["jug", "כד, קנקן"],
  ["prolong", "מתמשך"],
  ["algae", "אצות"],
  ["migrate", "להגר, לנדוד"],
  ["languor", "כבדות, חולשה, אפיסת כוחות"],
  ["modification", "תיקון, שינוי, השתנות"],
  ["linger", "להשתהות, להתעכב"],
  ["pepper", "פלפל"],
  ["coupon", "קופון"],
  ["integrate", "לשלב"],
  ["vest", "אפודה"],
  ["poacher", "מסיג גבול, צייד לא מורשה"],
  ["explode", "להתפוצץ"],
  ["insect", "חרק"],
  ["discontent", "חוסר שביעות רצון"],
  ["defer", "לעכב, לדחות"],
  ["unrest", "חוסר שקט"],
  ["shrink", "לכווץ, כיווץ"],
  ["transitory", "בר-חלוף"],
  ["prospective", "צפוי, עתידי"],
  ["tutor", "להדריך, מורה פרטי"],
  ["heredity", "תורשה"],
  ["horrify", "להפחיד"],
  ["resent", "להתרעם, להתנגד"],
  ["treasure", "אוצר, לנצור"],
  ["ingredients", "מרכיבים"],
  ["hasten", "למהר, להחפז"],
  ["instigate", "להסית"],
  ["bully", "בריון"],
  ["baffled", "מבולבל"],
  ["negligence", "רשלנות, הזנחה"],
  ["flagrant", "בוטה, מזעזע"],
  ["fingerprint", "טביעת אצבע"],
  ["glitch", "הפרעה, תקלה"],
  ["oppressive", "מדכא, אכזרי, מעיק"],
  ["nickname", "כינוי חיבה"],
  ["illustrator", "מאייר"],
  ["garlic", "שום"],
  ["suppression", "דיכוי"],
  ["bothersome", "מטריד, מרגיז"],
  ["gamble", "הימר"],
  ["apathy", "אדישות, אפאתיה"],
  ["reflection", "השתקפות"],
  ["cultivate", "לטפח, לעבד"],
  ["narcotic", "סם"],
  ["recommendation", "המלצה"],
  ["densely", "בצפיפות"],
  ["mourning", "אבל, מתאבל"],
  ["oscillate", "להתנודד, להיטלטל"],
  ["commensurate", "תואם"],
  ["fortify", "לבצר, לחזק"],
  ["orchestra", "תזמורת"],
  ["epilogue", "אחרית דבר"],
  ["burglar", "פורץ"],
  ["infancy", "ינקות"],
  ["stunt", "פעלול"],
  ["introduction", "היכרות, הקדמה, מבוא"],
  ["miracle", "נס, פלא"],
  ["consolation", "נחמה"],
  ["fastidious", "בררן, דקדקן, אנין טעם"],
  ["wander", "להסתובב, לשוטט"],
  ["elephant", "פיל"],
  ["repudiate", "לגנות, להתכחש, להתנער מ..."],
  ["propel", "להניע, לדחוף"],
  ["prestigious", "יוקרתי"],
  ["consolidate", "לאחד, לגבש"],
  ["resourceful", "בעל תושייה"],
  ["sensations", "חדשות מרעישות"],
  ["dawdle", "להתבטל"],
  ["reproduce", "להתרבות, לשכפל"],
  ["independence", "עצמאות"],
  ["daydream", "לחלום בהקיץ"],
  ["observation", "אבחנה"],
  ["decorate", "לקשט"],
  ["skyrocket", "להאמיר"],
  ["hospitable", "מסביר פנים"],
  ["whistle", "משרוקית, לשרוק"],
  ["lumber", "גזע עץ"],
  ["irrigation", "השקיה"],
  ["omission", "הזנחה, השמטה"],
  ["heresy", "כפירה"],
  ["allowable", "מותר, חוקי"],
  ["unfair", "לא הוגן"],
  ["situation", "מצב, סיטואציה"],
  ["indigenous", "מולד, ילידים"],
  ["absorbent", "בעל כושר ספיגה"],
  ["entertain", "לשעשע, לבדר"],
  ["joyous", "עליז, שמח"],
  ["shepherd", "רועה צאן"],
  ["preside", "לנהל"],
  ["blanket", "שמיכה"],
  ["pervasive", "מתפשט, מחלחל"],
  ["craftsmen", "אומן, בעל מלאכה"],
  ["pinch", "לצבוט"],
  ["printer", "מדפסת, דפס"],
  ["groom", "חתן, לטפח, לטפל"],
  ["bandage", "תחבושת"],
  ["corollary", "תולדה, תוספת"],
  ["veracity", "הגינות, יושר"],
  ["famine", "רעב קשה"],
  ["unbearable", "בלתי נסבל"],
  ["disciplined", "ממושמע, חינך, העניש"],
  ["drip", "לטפטף"],
  ["apposite", "מתאים מאד, הולם"],
  ["confrontation", "עימות"],
  ["inquire", "לתשאל"],
  ["surrender", "להיכנע"],
  ["fundamentalist", "מאמין בתורה שבכתב, בלי פרשנויות"],
  ["motif", "מוטיב"],
  ["fungus", "פטרת"],
  ["subconscious", "תת מודע"],
  ["seafood", "פירות ים"],
  ["examination", "בדיקה, בחינה"],
  ["benefactors", "תורמים, נדבנים"],
  ["dimension", "מידה, היקף, כמות, מימד"],
  ["sundown", "שקיעה"],
  ["elastic", "גמיש, גומיה, אלסטי"],
  ["prescription", "מרשם"],
  ["shrewdly", "בפיקחות"],
  ["condone", "לסלוח, למחול"],
  ["enroll", "להירשם"],
  ["reputation", "שם, מוניטין"],
  ["Gulf War", "מלחמת המפרץ"],
  ["languish", "הולך ונחלש, נוטה לאפיסת כוחות"],
  ["depict", "לתאר, לשרטט, לצייר, להציג"],
  ["coop", "לכלוא, לול"],
  ["handicap", "נכה"],
  ["toes", "בהונות"],
  ["grapes", "ענבים"],
  ["cigarette", "סיגריה"]
] as const;
