export default [
  ["slaughterhouse", "בית מטבחיים"],
  ["readiness", "מוכנות"],
  ["falsehood", "שקר"],
  ["leniency", "חמלה, רחמים"],
  ["immersion", "שקיעה"],
  ["intrusive", "פולשני"],
  ["mathematician", "מתמטיקאי"],
  ["astonishment", "תדהמה, השתאות"],
  ["launder", "לכבס"],
  ["unholy", "לא מוסרי, לא קדוש"],
  ["vocation", "מקצוע"],
  ["tainted", "מזוהם, מוכתם"],
  ["convalesce", "להחלים"],
  ["furnish", "לרהט"],
  ["leisurely", "נינוח, רגוע"],
  ["flee, fled", "להימלט, נמלט"],
  ["insuperable", "שלא ניתן לגבור עליו"],
  ["presentation", "מצגת"],
  ["supposition", "השערה, הנחה"],
  ["malformation", "פגם, עיוות"],
  ["embitter", "גורם התמרמרות"],
  ["junkyard", "מגרש גרוטאות"],
  ["purification", "טיהור"],
  ["dictation", "תכתיב"],
  ["humiliate", "להשפיל"],
  ["cougar", "סוג של טורף, פומה"],
  ["hibernate", "לישון שנת חורף"],
  ["paddle", "דוושה, מחבט, משוט"],
  ["zealot", "פנט, קנאי"],
  ["expendable", "שניתן לוותר עליו"],
  ["restatement", "ניסוח מחדש"],
  ["extortion", "סחיטה"],
  ["assertively", "בביטחון, באופן החלטי"],
  ["beak", "מקור"],
  ["phobia", "פוביה, פחד כרוני"],
  ["enchant", "לכשף, להקסים"],
  ["freeze, froze", "הקפיא, להקפיא"],
  ["ostentatious", "יומרני, גנדרני, ראוותני"],
  ["defection", "עריקה"],
  ["transcend", "להתעלות"],
  ["insurrection", "התקוממות"],
  ["hilarious", "מצחיק"],
  ["finalize", "לסכם, לגבש"],
  ["exhibition", "תערוכה"],
  ["bamboozle", "לבלבל, לרמות"],
  ["steamship", "אוניית קיטור"],
  ["congregate", "לאסוף, לאסוף קהל"],
  ["cologne", "בושם (של גבר), קולון"],
  ["frugal", "חסכני"],
  ["silkworm", "תולעת משי"],
  ["consonant", "עיצור (לשון)"],
  ["speck", "כתם"],
  ["rubbish", "זבל, שטויות"],
  ["uncountable", "אינספור"],
  ["segregation", "הפרדה"],
  ["rehabilitation", "שיקום"],
  ["exhale", "לנשוף"],
  ["quench", "להרוות, לספק"],
  ["deflate", "להוציא אוויר מ-"],
  ["spontaneous", "ללא מחשבה"],
  ["vociferous", "רעשני"],
  ["preparation for", "הכנות לקראת"],
  ["gracious", "אדיב, מקסים, חינני"],
  ["sarcophagus", "ארון קבורה קדום"],
  ["hospitalize", "לאשפז"],
  ["imaginative", "דמיוני"],
  ["dissection", "חיתוך, ביתור"],
  ["mouse (mice)", "עכבר (עכברים)"],
  ["concurred with", "להתאים, להתרחש בו זמנית"],
  ["coexistence", "דו-קיום"],
  ["uncritical", "לא ביקורתי"],
  ["repressive", "מדכא"],
  ["amputation", "קטיעה"],
  ["caviar", "קוויאר"],
  ["concurrence", "להתרחש בו זמנית"],
  ["heart-rending", "קורע לב"],
  ["conductor", "מנצח (תזמורת)"],
  ["complication", "סיבוך"],
  ["genial", "ידידותי"],
  ["old-fashioned", "מיושן"],
  ["excitement", "התרגשות"],
  ["unconcerned", "לא מודאג"],
  ["plaster", "טיח"],
  ["stereotype", "סטריאוטיפ"],
  ["accessibility", "נגישות"],
  ["accentuate", "להבליט, להדגיש"],
  ["commendably", "באופן ראוי לשבח"],
  ["recreation", "בילוי"],
  ["enfeeble", "להחליש"],
  ["ambivalence", "רגשות סותרים"],
  ["fragrance", "ניחוח"],
  ["staircase", "גרם מדרגות"],
  ["disturbance", "הפרעה"],
  ["drench", "להרטיב, להספיג"],
  ["deliberation", "הרהור, דיון"],
  ["citrus", "פרי הדר"],
  ["admittance", "הכנסה, הודאה"],
  ["wolf (wolves)", "זאב (זאבים)"],
  ["correspondence", "התאמה, התכתבות"],
  ["reciprocal", "מספר הופכי (במתמטיקה), הדדי"],
  ["nuisance", "מטרד"],
  ["inflate", "לנפח"],
  ["shrewdness", "פיקחות"],
  ["perch", "ענף, ישב על ענף, נח"],
  ["saturated", "רווי"],
  ["dispensable", "לא הכרחי, שאפשר לוותר עליו, שניתן להסתדר בלעדיו"],
  ["blaspheme", "לחלל (דבר קדוש)"],
  ["reincarnation", "גלגול נשמות"],
  ["contradiction", "ניגוד, סתירה"],
  ["glorify", "להאדיר"],
  ["disuse", "חוסר שימוש"],
  ["insulate", "לבודד"],
  ["croak", "קרקור"],
  ["loneliness", "בדידות"],
  ["subtraction", "חיסור (חשבון)"],
  ["fringes", "שוליים"],
  ["doorstep", "מפתן הדלת"],
  ["pathology", "פתולוגיה, ענף ברפואה"],
  ["intimidate", "להפחיד"],
  ["apathetic", "אדיש"],
  ["wasp", "צרעה"],
  ["imprisonment", "כליאה, מאסר"],
  ["intuition", "אינטואיציה"],
  ["self-indulgence", "סיפוק-עצמי"],
  ["intermission", "הפסקה"],
  ["leopard", "פנתר, נמר"],
  ["unwilling", "ממאן, לא מוכן"],
  ["ring, rang", "צלצל, לצלצל"],
  ["detrimental", "מזיק"],
  ["janitor", "שרת"],
  ["fraternal", "אחוותי, של אחים"],
  ["sentiments", "רגשות"],
  ["substance", "תוכן, חומר"],
  ["overhaul", "אוברול, שיפוץ"],
  ["flimsy", "עדין, שביר"],
  ["midair", "באוויר"],
  ["advantageous", "מועיל"],
  ["shelf (shelves)", "מדף (מדפים)"],
  ["vagueness", "עמימות, ערפול"],
  ["saturnine", "קודר, זועף, עצוב"],
  ["embalm", "לחנוט, לשמר"],
  ["goblet", "גביע"],
  ["unconventional", "לא שיגרתי"],
  ["revitalize", "להחיות"],
  ["misconception", "דעה מוטעית"],
  ["inspect", "לבדוק, לבחון, לפקח, לבדוק בדקדקנות"],
  ["morose", "קודר, עגמומי"],
  ["spewing", "להזרים"],
  ["butterfly", "פרפר"],
  ["advertisement", "מודעה, פרסום, פרסומת"],
  ["erudition", "השכלה עצומה"],
  ["mechanize", "להתקין מכונות, למכן"],
  ["incompetence", "חוסר יכולת"],
  ["narration", "קריינות"],
  ["perpetuate", "להנציח"],
  ["antler", "קרן"],
  ["dampen", "לדכא"],
  ["dissect", "לבתר, לנתח"],
  ["invariably", "ללא שינוי"],
  ["endurance", "כוח סבל"],
  ["unrealistic", "לא מציאותי"],
  ["indifference", "אדישות"],
  ["jagged", "משונן"],
  ["vertebrate", "בעל חוליות"],
  ["interjection", "הפרעה לשיחה, הערה"],
  ["rearing", "גידול, טיפוח"],
  ["envious", "קנאי"],
  ["glacier", "קרחון"],
  ["viper", "צפע"],
  ["snarl", "לנחור, לרטון"],
  ["staunch", "מוצק, חזק, לחסום, לעצור"],
  ["straighten", "ליישר"],
  ["disinfection", "חיטוי"],
  ["explosive", "חומר נפץ"],
  ["fairytale", "אגדה"],
  ["affluence", "שפע"],
  ["eulogize", "לפאר ולשבח"],
  ["fume", "עשן, אדים"],
  ["mountainside", "מדרון"],
  ["underestimate", "לזלזל, הערכה נמוכה"],
  ["congenial", "נעים, ידידותי"],
  ["reservation", "שמורה, שריון מקום"],
  ["quarrelsome", "וכחני"],
  ["garment", "לבוש, בגד"],
  ["peddler", "רוכל, סוחר"],
  ["Mediterranean", "ים תיכוני"],
  ["neighborhood", "שכונה"],
  ["grammatical", "דקדוקי"],
  ["obligation", "התחייבות"],
  ["sedative", "סם הרגעה, משכך"],
  ["folklore", "פולקלור"],
  ["rebellious", "מרדני, סורר"],
  ["consternation", "פחד, תדהמה"],
  ["culminate", "להגיע לשיא, הגיע לשיא"],
  ["fascinate", "לרתק, להקסים"],
  ["suffocation", "חנק"],
  ["courteous", "אדיב"],
  ["enclosing", "להקיף, לסגור"],
  ["[to] languish", "להיחלש"],
  ["idolize", "להעריץ"],
  ["marsupial", "חיית כיס"],
  ["stenographer", "קצרן"],
  ["confinement", "מאסר, ריתוק"],
  ["guillotine", "גיליוטינה"],
  ["erroneous", "שגוי"],
  ["czar", "צאר (שליט רוסי)"],
  ["malnutrition", "תת-תזונה"],
  ["accomplices", "שותף לדבר עבירה"],
  ["mountaintop", "פסגת הר"],
  ["swindler", "רמאי"],
  ["expansion", "התפשטות, התרחבות, התפתחות"],
  ["audacious", "נועז"],
  ["allusion", "רמיזה, אזכור"],
  ["derivation", "הפקה, גזירה, הוכחה (לוגית)"],
  ["dwindle", "להיעשות קטן ויותר, הידלדל, להתדלדל, התמעט, להתמעט"],
  ["embarrass", "להביך"],
  ["mutation", "מוטציה"],
  ["glance", "מבט חטוף"],
  ["acquitted", "זוכה מאשמה"],
  ["proliferate", "התפשט במהירות"],
  ["fisherman", "דייג"],
  ["demented", "מטורף, משוגע"],
  ["yawn", "לפהק, פיהוק"],
  ["deterioration", "הדרדרות"],
  ["juxtapose", "להציב זה לצד זה"],
  ["inexpensive", "לא יקר, זול"],
  ["deform", "לעוות"],
  ["relegated", "הורד בדרגה"],
  ["disseminate", "להפיץ"],
  ["compost", "זבל אורגני"],
  ["savanna", "סוואנה, ערבה"],
  ["irresistible", "שלא ניתן לעמוד בפניו"],
  ["triggered", "גרם, הוביל ל-, עורר"],
  ["cripple", "להטיל מום"],
  ["swept away", "נסחף"],
  ["denominator", "מכנה (של שבר)"],
  ["compulsion", "כפייה"],
  ["growled", "נהם"],
  ["poisonous", "רעיל"],
  ["vowel", "תנועה (לשון)"],
  ["kettle", "קומקום"],
  ["installation", "התקנה"],
  ["resurgence", "תחייה"],
  ["[to] industrialize", "לתעש"],
  ["enrage", "להרגיז, להכעיס"],
  ["lucrative", "ריווחי"],
  ["depreciate", "להפחית"],
  ["inadvertently", "בלי כוונה, בלי משים"],
  ["limber", "גמיש"],
  ["fallacious", "מטעה"],
  ["filmmaker", "יוצר סרטים"],
  ["obstinate", "עקשן"],
  ["separation", "הפרדה"],
  ["accusation", "האשמה"],
  ["[to] horrify", "להפחיד"],
  ["cadaver", "גופה"],
  ["disparagement", "זלזול"],
  ["fabricate", "לבדות"],
  ["predominantly", "באופן ניכר"],
  ["shingles", "רעף"],
  ["magnitude", "גודל, משמעות, חשיבות, גודל או שיעור מסויים"],
  ["deformity", "עיוות, מום"],
  ["upholstery", "ריפוד"],
  ["salvation", "גאולה, ישועה"],
  ["punctuation", "ניקוד, פיסוק"],
  ["aspiration", "שאיפה, חלום"],
  ["reassurance", "הרגעה, הבטחה"],
  ["demean", "להשפיל, להנמיך"],
  ["nausea", "בחילה"],
  ["unpardonable", "בלתי נסלח"],
  ["prescribe", "לרשום מרשם"],
  ["appease", "לפייס"],
  ["respectfully", "בכבוד"],
  ["invertebrate", "חסר-חוליות"],
  ["physicist", "פיזיקאי"],
  ["amusement", "שעשוע"],
  ["deliberative", "דיוני, שנעשה בכוונה תחילה"],
  ["wickedness", "רוע, רשע"],
  ["memorize", "לזכור בעל-פה, לשנן"],
  ["grievance", "טרוניה, התמרמרות"],
  ["decorative", "קישוטי, דקורטיבי"],
  ["encroach", "לפלוש, להסיג גבול"],
  ["appraise", "לאמוד, להעריך (שווי)"],
  ["allowance", "דמי כיס, הקצבה, קצבה"],
  ["teeth, tooth", "שן, שיניים"],
  ["meticulous", "קפדני"],
  ["prehistoric", "קדמון, פרה-היסטורי"],
  ["toad", "קרפדה"],
  ["brutishly", "באכזריות, בבהמיות"],
  ["tentative", "ניסיוני, טנטטיבי"],
  ["waterfall", "מפל"],
  ["twig", "זרד, ענף קטן"],
  ["lamentable", "מצער, מעציב"],
  ["uproar", "מהומה, רעש"],
  ["crossroad", "צומת"],
  ["implore", "להתחנן, להפציר"],
  ["exaggeration", "הגזמה"],
  ["forgettable", "שאפשר לשכוח אותו"],
  ["theoretically", "לכאורה, תיאורטית"],
  ["gland", "בלוטה"],
  ["outspread", "לפרוש לרווחה"],
  ["shapeless", "חסר צורה"],
  ["orchestrate", "לתזמר, לתאם"],
  ["intermediary", "אמצעי, מתווך"],
  ["poultry", "עוף"],
  ["abhor", "לתעב, לשנוא"],
  ["congenital", "מולד"],
  ["posterity", "הדורות הבאים"],
  ["thimble", "אצבעון (לתפירה)"],
  ["proverb", "אמרה, פתגם"],
  ["avaricious", "חמדן, תאב בצע"],
  ["numeric", "מספרי"],
  ["envision", "לצפות, לחזות"],
  ["redhead", "ג'ינג'י (סלנג)"],
  ["wholesale", "סיטונאות"],
  ["eccentric", "אקסצנטרי, מוזר"],
  ["fluctuation", "חוסר יציבות"],
  ["monument", "אנדרטה"],
  ["plentiful", "מלא, שופע"],
  ["deducible", "ניתן להסקה, ניתן להיקש"],
  ["frustration", "תסכול"],
  ["reinvigorate", "להמריץ מחדש, לרענן"],
  ["adorn", "לקשט"],
  ["overwhelm", "מהמם"],
  ["persuasion", "שכנוע"],
  ["adolescence", "נעורים, גיל ההתבגרות"],
  ["complaisance", "נכונות לרצות אחרים, אדיבות"],
  ["commiserate", "להשתתף בצער"],
  ["intoxicate", "להרעיל, להלהיב, לשכר"],
  ["instantaneous", "מיידי"],
  ["cosmopolitan", "אוניברסלי"],
  ["unwanted", "לא רצוי"],
  ["agonize", "לייסר, לענות"],
  ["intersection", "צומת, הצטלבות"],
  ["loathe", "לתעב"],
  ["infraction", "עבירה"],
  ["rehearse", "לחזור, לתרגל"],
  ["sincerity", "כנות"],
  ["annihilate", "להשמיד"],
  ["disagreement", "חוסר הסכמה"],
  ["automobile", "כלי רכב, אוטו"],
  ["glaze", "זיגוג"],
  ["disapproving", "לא מסכים, לא מאשר, לא מרוצה"],
  ["leaf (leaves)", "עלה (עלים)"],
  ["credibility", "אמינות, מהימנות"],
  ["retroactive", "רטרואקטיבי, למפרע"],
  ["[to] valuate", "לאמוד"],
  ["repelled", "דחה, הגעיל"],
  ["misbehave", "להתנהג בצורה לא הולמת"],
  ["abbreviate", "לקצר"],
  ["rainstorm", "סערת גשמים"],
  ["cashier", "קופאי"],
  ["argumentative", "וכחן"],
  ["snicker", "גיחוך"],
  ["spinach", "תרד"],
  ["fraction", "חלק קטן, שבר"],
  ["reciprocate", "הדדי"],
  ["canvass", "לבדוק, לסקור"],
  ["symmetry", "סימטריה, התאמה"],
  ["figurative", "סמלי, מוחשי (ציור), ציורי (ספרות)"],
  ["conquistador", "כובש"],
  ["proposition", "הצעה"],
  ["syllable", "הברה"],
  ["extrapolate", "לאמוד על סמך מידע קיים"],
  ["housemaid", "מנקה, עוזרת בית"],
  ["erosion", "כרסום, סחף"],
  ["alertness", "עירנות, דריכות"],
  ["unorganized", "לא מאורגן"],
  ["invariable", "שאינו משתנה, קבוע"],
  ["sneeze", "להתעטש"],
  ["inject", "להזריק"],
  ["transportation", "תחבורה"],
  ["unattractive", "לא מושך"],
  ["abacus", "חשבונייה"],
  ["shroud", "עטיפה, תכריך"],
  ["howl", "יללה, לילל"],
  ["accompaniment", "ליווי"],
  ["docility", "צייתנות, כניעות"],
  ["pothole", "מהמורה, בור"],
  ["summits", "פסגות"],
  ["supplement", "תוסף"],
  ["devastated", "הרוס, מפורק"],
  ["footprints", "עקבות, טביעות רגל"],
  ["ingest", "להכניס משהו לגוף דרך הפה"],
  ["self-confidence", "בטחון-עצמי"],
  ["derision", "לעג"],
  ["epitomize", "לייצג, לאפיין"],
  ["cockroach", "מקק, ג'וק"],
  ["numerator", "מונה (של שבר)"],
  ["reprove", "לגעור"],
  ["formulate", "לנסח"],
  ["upheaval", "מהפך"],
  ["frightening", "מפחיד"],
  ["rehearsal", "חזרה"],
  ["recruitment", "גיוס"],
  ["disloyal", "לא נאמן"],
  ["agglomeration", "ערימה"],
  ["desperation", "ייאוש"],
  ["exaggerate", "להגזים"],
  ["familiarize", "להתוודע"],
  ["taint", "להכפיש, לזהם, להכתים"],
  ["caterpillar", "זחל"],
  ["dovecote", "שובך"],
  ["condense", "לדחוס"],
  ["valuate", "להעריך"],
  ["interminable", "נצחי"],
  ["alienation", "הרחקה, ניכור"],
  ["octopus", "תמנון"],
  ["simultaneous", "בו-זמנית, באותו הזמן"],
  ["insurmountable", "שאין להתגבר עליו"],
  ["convalescence", "החלמה"],
  ["disparage", "להמעיט בערך, לזלזל"],
  ["wart", "יבלת"],
  ["diurnal", "יומי"],
  ["communicative", "מוכן לתקשר"],
  ["accumulative", "מצטבר"],
  ["ensue", "נבע"],
  ["halve", "לחצות"],
  ["instill", "להחדיר, להשריש"],
  ["upbringing", "חינוך, גידול"],
  ["recollection", "זיכרון"],
  ["augment", "להרחיב"],
  ["smog", "ערפיח"],
  ["tranquilize", "להרגיע, להרדים"],
  ["disarmament", "פירוק מנשק"],
  ["bashful", "ביישן"],
  ["icicle", "נטיף קרח"],
  ["cucumber", "מלפפון"],
  ["heartbeat", "פעימות לב, דופק"],
  ["inflammation", "דלקת"],
  ["expatriate", "להגלות, לגרש"],
  ["scrutinize", "לבחון בקפידה, בחן, בדק, לעיין, לחקור, לבדוק"],
  ["punctuate", "הדגשה"],
  ["evocative", "מעורר, מעלה, מזכיר"],
  ["ornament", "קישוט"],
  ["puzzled", "מבולבל"],
  ["surveillance", "מעקב"],
  ["reorganize", "לארגן מחדש"],
  ["dislocate", "לנקוע, לפרוק"],
  ["air conditioner", "מזגן"],
  ["probation", "תקופת מבחן"],
  ["displacement", "עקירה"],
  ["contaminate", "לזהם"],
  ["vacation", "חופשה"],
  ["arable", "מתאים לעיבוד"],
  ["prowess", "יכולת, מיומנות"],
  ["lackluster", "העדר ברק, העדר כוח"],
  ["heroine", "גיבורה"],
  ["obsession", "אובססיה, דיבוק, קיבעון"],
  ["sanction", "קנס, עידוד, עונש"],
  ["gymnasium", "אולם ספורט"],
  ["unearth", "לחפור, לחשוף"]
] as const;
