export default [
  ["absurd", "מגוחך, לא סביר"],
  ["accelerate", "להאיץ"],
  ["acclaim", "להריע, לשבח"],
  ["accommodate", "לאכסן, לשכן"],
  ["accompany", "ללוות"],
  ["accustomed", "מורגל"],
  ["aggressive", "תוקפני, אלים"],
  ["agriculture", "חקלאות"],
  ["allergic", "אלרגי"],
  ["amass", "לצבור, לערום"],
  ["amaze", "להדהים"],
  ["appeal", "לערער"],
  ["appeal", "מדבר אל, מושך"],
  ["appeal", "לבקש"],
  ["applicant", "מועמד"],
  ["arousing", "מעורר"],
  ["as many as", "רבים כמו (מספר גדול)"],
  ["ascertain", "לוודא"],
  ["aspiration", "שאיפה, חלום"],
  ["audit", "ביקורת"],
  ["award", "פרס, להעניק פרס"],
  ["bank", "לערום"],
  ["bank", "בנק"],
  ["bank", "גדה"],
  ["betray", "לבגוד"],
  ["blank", "ריק, רווח"],
  ["boost", "דחף, המריץ"],
  ["broadcast", "לשדר"],
  ["cage", "כלוב, לכלוא"],
  ["cancer", "סרטן (מחלה)"],
  ["capture", "ללכוד"],
  ["cargo", "מטען"],
  ["carve", "לחרוט"],
  ["cemetery", "בית קברות"],
  ["certify", "להצהיר, לאשר"],
  ["chapter", "פרק"],
  ["church", "כנסיה"],
  ["circulate", "לנוע במחזוריות"],
  ["circulate", "להפיץ"],
  ["colleague", "עמית, קולגה"],
  ["collect", "לאסוף"],
  ["collide", "להתנגש"],
  ["collision", "התנגשות"],
  ["commendably", "באופן ראוי לשבח"],
  ["commends", "לציין לשבח"],
  ["commentary", "פרשנות"],
  ["companion", "בן-זוג"],
  ["compatible", "מתאים, ראוי"],
  ["compel", "לאלץ, לחייב"],
  ["compensate", "לפצות"],
  ["compile", "לאסוף, לקבץ"],
  ["conceal", "להסתיר"],
  ["conceive", "להרהר"],
  ["conceive", "לעבר"],
  ["concerted", "מתואם"],
  ["concur", "להסכים"],
  ["concurrence", "להתרחש בו זמנית"],
  ["condemned", "לגנות"],
  ["condemned", "נידון ל-"],
  ["confess", "להודות"],
  ["confession", "וידוי"],
  ["confinement", "מאסר, ריתוק"],
  ["confiscate", "להחרים"],
  ["conform", "להתאים, להסתגל"],
  ["confuse", "לבלבל"],
  ["confusion", "בלבול"],
  ["conquer", "לכבוש"],
  ["conquest", "כיבוש"],
  ["conscious", "מודע"],
  ["conservation", "שימור"],
  ["conservative", "שמרני"],
  ["conserve", "לשמר"],
  ["contend", "להתמודד, לטעון, להיאבק"],
  ["content", "שביעות רצון"],
  ["content", "תוכן"],
  ["continent", "יבשת"],
  ["contrast", "להוות ניגוד"],
  ["contrast", "ניגוד"],
  ["contribute", "לתרום"],
  ["controversial", "שנוי במחלוקת"],
  ["controversy", "מחלוקת"],
  ["convene", "לכנס"],
  ["conversation", "שיחה"],
  ["convince", "לשכנע"],
  ["coordination", "קואורדינציה, תיאום"],
  ["coordinator", "מתאם"],
  ["correspond", "להתכתב"],
  ["correspond", "להתאים"],
  ["correspondence", "התכתבות"],
  ["crack", "סדק, לסדוק"],
  ["crave", "להשתוקק"],
  ["crime", "פשע"],
  ["crude", "וולגרי, גס"],
  ["crude", "גולמי"],
  ["cuisine", "מטבח, בישול"],
  ["curse", "קללה, לקלל"],
  ["darkness", "חשיכה"],
  ["debate", "ויכוח, דיון"],
  ["deceased", "נפטר"],
  ["deceive", "להונות"],
  ["deliberate", "מכוון"],
  ["deliberate", "לשקול, לבחון, לדון"],
  ["deliberation", "דיון"],
  ["delusions", "אשליות, הזיות"],
  ["denial", "הכחשה"],
  ["depend on", "תלוי ב-"],
  ["describe", "לתאר"],
  ["desolate", "הרוס"],
  ["desolate", "שומם, נטוש"],
  ["destroy", "להרוס"],
  ["destructive", "הרסני"],
  ["detract", "להפחית, לגרוע"],
  ["deviant", "סוטה"],
  ["device", "מכשיר"],
  ["devise", "לתכנן, להמציא"],
  ["dictate", "להכתיב, לפקד"],
  ["disorder", "הפרעה"],
  ["display", "להציג"],
  ["disregard", "להתעלם"],
  ["dissolve", "להתמוסס"],
  ["distract", "להסיח את הדעת"],
  ["district", "מחוז"],
  ["divine", "אלוהי"],
  ["divinity", "אלוהות"],
  ["downhill", "מדרון, מורד"],
  ["ease", "להקל, קלוּת"],
  ["easily", "בקלות"],
  ["effect", "תוצאה, אפקט"],
  ["effect", "רושם, השפעה"],
  ["emblem", "סמל"],
  ["encourage", "לעודד"],
  ["engrave", "לחרוט"],
  ["enhance", "להעצים"],
  ["entirely", "לחלוטין"],
  ["enzyme", "אנזים"],
  ["equality", "שוויון, במידה שווה"],
  ["equates", "להשוות, להתאים"],
  ["evoke", "לעורר, להעלות"],
  ["evolutionary", "התפתחותי"],
  ["evolved", "התפתח"],
  ["excessively", "בצורה מוגזמת"],
  ["exchange", "להחליף, חלופה"],
  ["exclude", "למנוע, לשלול, להרחיק, לגרש"],
  ["exclusive", "בלעדי"],
  ["exclusively", "באופן בלעדי, רק"],
  ["excuse", "לסלוח"],
  ["excuse", "תירוץ"],
  ["explicit", "מפורש, ברור, בוטה"],
  ["explore", "לחקור, ללמוד"],
  ["exposure", "חשיפה"],
  ["exquisite", "מצוין"],
  ["exquisite", "חד, מעודן, אנין"],
  ["extend", "להאריך, להרחיב"],
  ["extension", "שלוחה"],
  ["exterior", "חיצוני"],
  ["external", "חיצוני"],
  ["extinction", "הכחדה"],
  ["extract", "לתמצת, להפיק"],
  ["factor", "גורם"],
  ["favor", "טובה"],
  ["favor", "להעדיף"],
  ["favored", "מועדף"],
  ["fight, fought", "לריב, רב"],
  ["figure", "לחשב, להניח, להסיק"],
  ["figure", "גזרה, צורה"],
  ["figure", "ספרה, מספר"],
  ["figure", "דמות"],
  ["flat", "שטוח"],
  ["flat", "דירה"],
  ["flew", "עף"],
  ["fly", "לעוף"],
  ["fly", "זבוב"],
  ["foil", "לסכל"],
  ["forerunner", "אות, סימן מבשר באות"],
  ["forerunner", "שליח, חלוץ, מבשר"],
  ["fossil", "מאובן"],
  ["genius", "גאון"],
  ["gentle", "עדין"],
  ["genuine", "אמיתי, מקורי"],
  ["grant", "להעניק, מענק"],
  ["guard", "שומר, לשמור"],
  ["halt", "לעצור,להפסיק, עצירה"],
  ["handle", "להתמודד"],
  ["harder", "קשה יותר"],
  ["harmful", "מזיק"],
  ["harmless", "שאינו מזיק"],
  ["hazardous", "מסוכן"],
  ["hectic", "קדחתני"],
  ["heir", "יורש"],
  ["heredity", "תורשה"],
  ["hospital", "בית חולים"],
  ["hospitalize", "לאשפז"],
  ["hunger", "רעב"],
  ["ideal", "אידיאל, אידיאלי"],
  ["immense", "כביר, עצום"],
  ["immigrate", "להגר"],
  ["impulse", "דחף"],
  ["impulsively", "ללא שיקול דעת"],
  ["in favor of", "לטובת"],
  ["incentive", "תמריץ"],
  ["incidence", "כמות, הִקָּרוּת (משהו שקורה)"],
  ["indifference", "אדישות"],
  ["infinite", "אינסופי"],
  ["innate", "מולד"],
  ["inner", "פנימי"],
  ["inquire", "לתשאל"],
  ["inquiry", "חקירה"],
  ["insist", "להתעקש"],
  ["inspiration", "השראה"],
  ["inspiring", "נותן השראה"],
  ["interior", "פנימי"],
  ["interrupt", "להפריע"],
  ["intersection", "צומת, הצטלבות"],
  ["intervene", "להתערב"],
  ["intervention", "התערבות"],
  ["invent", "להמציא"],
  ["inventor", "ממציא"],
  ["inventory", "מצאי"],
  ["invisible", "בלתי נראה"],
  ["invite", "להזמין"],
  ["Jew", "יהודי"],
  ["kind", "סוג"],
  ["kind", "טוב לב, אדיב, נעים"],
  ["landmark", "אבן דרך"],
  ["landscape", "נוף"],
  ["lean", "להישען"],
  ["legible", "קריא"],
  ["lens", "עדשה"],
  ["license", "רישיון"],
  ["license", "לאשר, להתיר"],
  ["lifetime", "תקופת החיים, במשך החיים"],
  ["literary", "ספרותי"],
  ["literate", "משכיל, מלומד"],
  ["literature", "ספרות"],
  ["load", "להעמיס"],
  ["losing", "מפסיד"],
  ["mail", "דואר"],
  ["mailman", "דוור"],
  ["malnutrition", "תת-תזונה"],
  ["mate", "בן זוג, חבר"],
  ["mate", "להזדווג"],
  ["maturity", "בגרות"],
  ["mayor", "ראש עיר"],
  ["mediate", "לגשר, לתווך"],
  ["mediocre", "בינוני (במובן שלילי)"],
  ["miserable", "אומלל"],
  ["moist", "לחות"],
  ["moral", "מוסר"],
  ["morale", "מורל"],
  ["necessary", "הכרחי"],
  ["neglect", "להזניח, הזנחה"],
  ["negligence", "הזנחה, רשלנות"],
  ["nocturnal", "לילי"],
  ["noon", "צהריים (12:00)"],
  ["notable", "נכבד"],
  ["notice", "לשים לב"],
  ["notice", "התראה"],
  ["notify", "להודיע, ליידע"],
  ["obedience", "ציות"],
  ["obey", "לציית"],
  ["objective", "אוביקטיבי"],
  ["obstacle", "מכשול"],
  ["offshore", "חו&quot;ל"],
  ["orbit", "לחוג, להסתובב"],
  ["orient", "להתמצא"],
  ["oriented", "מכוון, מונחה"],
  ["outer", "חיצוני"],
  ["outline", "תוואי, מתאר, קווים כלליים"],
  ["overlooked", "העלים עין"],
  ["parallel", "מקביל"],
  ["party", "מפלגה"],
  ["party", "מסיבה"],
  ["pattern", "דוגמה"],
  ["penned", "כָּתַב"],
  ["perceive", "להבחין, לראות"],
  ["perform", "לבצע, להציג"],
  ["performance", "ביצוע"],
  ["performance", "הופעה"],
  ["performer", "מבצע, מציג"],
  ["permission", "רשות, היתר"],
  ["permit", "אישור, רישיון"],
  ["permit", "להרשות"],
  ["persuade", "לשכנע"],
  ["persuasion", "שכנוע"],
  ["piece", "יצירה"],
  ["piece", "חתיכה, חלק"],
  ["pipe", "צינור"],
  ["plausible", "סביר, מתקבל על הדעת"],
  ["plot", "להכין תרשים"],
  ["plot", "לזמום, לקשור קשר"],
  ["plot", "חלקה (חלקת אדמה)"],
  ["plot", "עלילה"],
  ["poacher", "מסיג גבול, צייד לא מורשה"],
  ["practical", "מעשי"],
  ["practice", "לתרגל, תרגול"],
  ["prescribe", "לרשום מרשם"],
  ["prescription", "מרשם"],
  ["preserve", "לשמר"],
  ["pretext", "אמתלה, תואנה"],
  ["prevent", "למנוע"],
  ["prevention", "מניעה"],
  ["previous", "קודם"],
  ["probable", "סביר, מתקבל על הדעת"],
  ["probably", "כנראה, קרוב לוודאי"],
  ["process", "לעכל, לעבד"],
  ["process", "תהליך"],
  ["prohibit", "לאסור, למנוע"],
  ["project", "לתכנן"],
  ["project", "פרוייקט, מיזם"],
  ["project", "להשליך, להקרין"],
  ["promote", "לקדם"],
  ["promotion", "קידום"],
  ["prompted", "הביא לידי"],
  ["proponent", "תומך"],
  ["proportion", "שיעור, מידה"],
  ["prosperity", "צמיחה, שגשוג"],
  ["prosperous", "משגשג, מצליח"],
  ["pump", "משאבה, לשאוב"],
  ["pursue", "לרדוף"],
  ["pursuit", "מרדף"],
  ["quantify", "לכמת"],
  ["quantity", "כמות"],
  ["radically", "באופן קיצוני"],
  ["rank", "דרגה"],
  ["ray", "קרן, אלומת אור"],
  ["razor", "סכין גילוח"],
  ["rear", "אחורי"],
  ["rear", "לטפח, לגדל"],
  ["reconcile", "להתפייס"],
  ["reform", "שינוי, רפורמה"],
  ["reinvigorate", "לרענן, להמריץ מחדש"],
  ["relationship", "מערכת יחסים"],
  ["religious", "דתי"],
  ["remainder", "שארית"],
  ["renovate", "לחדש, לשפץ"],
  ["respective", "שייך בהתאמה"],
  ["respectively", "בהתאמה"],
  ["restrict", "להגביל"],
  ["restriction", "הגבלה"],
  ["retire", "לפרוש"],
  ["revoke", "לבטל, לשלול"],
  ["reward", "פרס, לתגמל"],
  ["ritual", "טקס, פולחן"],
  ["rough", "קשה, מחוספס"],
  ["rudimentary", "יסודי, בסיסי"],
  ["sacred", "קדוש"],
  ["sacrifice", "להקריב, קורבן"],
  ["sake", "תועלת, עניין"],
  ["screen", "לסרוק"],
  ["screen", "מסך, צג, וילון"],
  ["screen", "לסנן"],
  ["seek", "לבקש"],
  ["seek, sought", "לחפש, חיפש"],
  ["seismic", "ססמי (קשור לרעידות אדמה)"],
  ["series", "סדרה"],
  ["settle", "להסדיר"],
  ["settle", "להתיישב"],
  ["severe", "חמור"],
  ["shape", "צורה, לעצב (צורה)"],
  ["shift", "משמרת"],
  ["shift", "להזיז"],
  ["shiny", "נוצץ, בוהק"],
  ["side effect", "תופעת לוואי"],
  ["simplicity", "פשטות"],
  ["sketch", "שרטוט, איור, סקיצה"],
  ["skyrocket", "להאמיר"],
  ["skyscraper", "גורד שחקים"],
  ["sorrow", "עצב, צער"],
  ["spark", "גיץ, ניצוץ"],
  ["spectacular", "מדהים"],
  ["spirit", "כוונה, רוח הדברים"],
  ["spirit", "רוח רפאים, נפש"],
  ["spiritual", "רוחני"],
  ["spontaneously", "ללא תכנון"],
  ["stabilize", "לייצב"],
  ["stable", "יציב"],
  ["steam", "אד, לאדות"],
  ["steamship", "אוניית קיטור"],
  ["straightforward", "ישיר"],
  ["stream", "לזרום, נחל, זרם"],
  ["stricken", "מוכה"],
  ["stride", "צעד, לצעוד"],
  ["strife", "מאבק, עימות"],
  ["strike", "הכה, התקיף"],
  ["strike", "שביתה"],
  ["stripes", "פסים"],
  ["structure", "מבנה, לבנות"],
  ["stumble", "למעוד"],
  ["substitute", "תחליף"],
  ["sufficient", "מספיק"],
  ["superfluous", "מיותר, עודף"],
  ["surface", "פני שטח"],
  ["suspect", "חשוד (מישהו)"],
  ["suspect", "לחשוד"],
  ["suspicious", "חשוד (משהו)"],
  ["sympathetic", "אוהד"],
  ["team", "צוות"],
  ["tendency", "נטייה"],
  ["terminate", "לסיים, לחסל"],
  ["terrain", "שטח"],
  ["terrify", "להפחיד, להבעית"],
  ["theme", "נושא"],
  ["threat", "איום"],
  ["tight", "הדוק, לחוץ, צמוד"],
  ["tolerance", "סובלנות"],
  ["tolerate", "לסבול"],
  ["ultimate", "מוחלט, סופי"],
  ["unbearable", "בלתי נסבל"],
  ["uncountable", "אינספור"],
  ["undergo", "לעבור, להתנסות, לחוות"],
  ["unforgettable", "בלתי נשכח"],
  ["unsafe", "לא בטוח"],
  ["vain", "לשווא"],
  ["vain", "שחצן"],
  ["vary", "משתנה"],
  ["venture", "סיכון"],
  ["verify", "לוודא, לאמת"],
  ["versions", "גרסאות"],
  ["vessel", "כלי שיט"],
  ["village", "כפר"],
  ["virtual", "מדומה, וירטואלי"],
  ["virtually", "למעשה, בעצם"],
  ["visual", "חזותי"],
  ["visualize", "לדמיין"],
  ["wealthy", "עשיר"],
  ["weigh", "לשקול"],
  ["weight", "משקל"],
  ["wickedly", "ברשעות"],
  ["wisdom", "חכמה, בינה"]
] as const;
