export default [
  ["despise", "לתעב"],
  ["dessert", "קינוח"],
  ["preventive", "מניעתי, מונע"],
  ["rubber", "גומי"],
  ["transformation", "שינוי"],
  ["circumstance", "מצב, תנאי, נסיבות"],
  ["[to] anguish", "לסבול"],
  ["elderly", "זקן, מבוגר מ..."],
  ["fatigue", "לעייף, עייפות, תשישות"],
  ["syndrome", "תסמונת"],
  ["flatter", "להחמיא, שטוח יותר"],
  ["ambivalent", "בעל משמעויות סותרות"],
  ["tin", "בדיל, עשוי מפח"],
  ["dim", "לעמעמם"],
  ["consequent", "בא כתוצאה"],
  ["juice", "מיץ"],
  ["mention", "להזכיר, לאזכר"],
  ["skillful", "מיומן"],
  ["fetus", "עובר, עובר (ברחם)"],
  ["silk", "משי"],
  ["sweep", "לטאטא"],
  ["prevention", "מניעה"],
  ["accomplishment", "הישג, השלמה"],
  ["whale", "לוויתן"],
  ["compulsive", "כפייתי"],
  ["biblical", "תנ\"כי"],
  ["illusory", "מטעה, חמקמק"],
  ["invaders", "פולשים"],
  ["skimp", "להתקמצן"],
  ["tent", "אוהל"],
  ["norm", "נורמה, תקן"],
  ["courageous", "אמיץ"],
  ["heed", "לשים לב"],
  ["skyscraper", "גורד שחקים"],
  ["preferable", "עדיף"],
  ["chauffeur", "נהג"],
  ["conclusive", "מכריע"],
  ["align", "להסתדר בשורה"],
  ["silently", "בשקט"],
  ["objection", "התנגדות"],
  ["consciousness", "הכרה, מודעות"],
  ["descendent", "צאצא"],
  ["tempt", "לפתות"],
  ["suffocate", "להיחנק"],
  ["avert", "להסיט, להפנות, למנוע"],
  ["solitary", "מבודד"],
  ["translate", "לתרגם"],
  ["emergence", "הופעה הדרגתית, היווצרות"],
  ["diary", "יומן"],
  ["leadership", "מנהיגות"],
  ["clash", "התנגשות"],
  ["inherit", "לרשת"],
  ["vanish", "להיעלם"],
  ["visualize", "לדמיין"],
  ["radically", "באופן קיצוני"],
  ["slender", "רזה"],
  ["damp", "לח"],
  ["stuntman", "פעלולן (בסרטים)"],
  ["vacant", "פנוי, ריק"],
  ["contention", "מחלוקת"],
  ["agenda", "סדר יום"],
  ["theater", "בית קולנוע, תיאטרון"],
  ["coma", "תרדמת"],
  ["newscaster", "מגיש חדשות"],
  ["variation", "שינוי, וריאציה"],
  ["sober", "פיכח"],
  ["promotion", "קידום"],
  ["oppression", "דיכוי"],
  ["detection", "מלאכת האיתור, גילוי"],
  ["hasty", "מהיר, בהול"],
  ["evacuation", "פינוי"],
  ["enlightened", "נאור"],
  ["mobilize", "לנייד, להניע"],
  ["ascertain", "לברר, לוודא"],
  ["relic", "שארית, שריד"],
  ["admirable", "נערץ, ראוי להערצה"],
  ["bargain", "להתמקח, מציאה, עסקה"],
  ["disqualify", "לפסול, לשלול"],
  ["weapon", "נשק"],
  ["fairy", "פיה"],
  ["apparatus", "מנגנון"],
  ["petulant", "קצר רוח, חסר סבלנות"],
  ["enhance", "להעצים, להגביר"],
  ["candy", "ממתק"],
  ["buffoon", "ליצן"],
  ["confusion", "בלבול"],
  ["inclusion", "שיתוף"],
  ["fishing", "דיג"],
  ["spider", "עכביש"],
  ["vertebrae", "חוליות עמוד השדרה"],
  ["malfunction", "כשל, ליקוי"],
  ["illustrate", "להמחיש, להדגיש"],
  ["frivolous", "קל דעת, טפשי"],
  ["diversify", "לגוון"],
  ["curtain", "וילון"],
  ["radicalism", "קיצוניות"],
  ["desolate", "שומם, נטוש, הרוס"],
  ["shoulder", "כתף"],
  ["conceive", "לחשוב על..., להרות, לעבר, להרהר"],
  ["reinforce", "לתגבר, לחזק"],
  ["wedding", "חתונה"],
  ["torment", "לענות (בעינויים), להציק, לגרום סבל רב, סבל רב, עינוי"],
  ["illness", "מחלה"],
  ["hid from", "התחבא מ-"],
  ["exert", "להפעיל, להתאמץ"],
  ["convene", "לכנס"],
  ["disciples", "תלמידים"],
  ["utter", "לבטא, להגות"],
  ["myriad", "רב, הרבה"],
  ["formula", "נוסחה, פורמולה"],
  ["resigned", "התפטר"],
  ["bass", "בס (במוזיקה)"],
  ["spotlight", "זרקור"],
  ["transmitter", "משדר"],
  ["plead", "לעתור, להתחנן"],
  ["passion", "תשוקה"],
  ["equates", "להשוות, להתאים"],
  ["discourage", "לשכנע שלא לעשות משהו"],
  ["disguise", "תחפושת"],
  ["revert", "לחזור לשיטה הקודמת"],
  ["testify", "להעיד"],
  ["script", "תסריט"],
  ["cotton", "כותנה"],
  ["olive", "זית"],
  ["visibility", "ראות"],
  ["enclosure", "סגירה, כיתור, שטח מגודר"],
  ["vulnerable", "פגיע, רגיש, פגיעות"],
  ["desirable", "נחשק, רצוי"],
  ["refined", "מעודן, מלוטש"],
  ["immoral", "לא מוסרי"],
  ["divorce", "גירושין"],
  ["deceive", "להונות"],
  ["withstand", "לעמוד נגד לחץ, להתמודד, לעמוד ב-"],
  ["nut", "אגוז"],
  ["durable", "יציב, מתמשך, מחזיק מעמד, מאריך ימים"],
  ["clay", "חימר"],
  ["authenticity", "אותנטיות, אמיתיות"],
  ["shy", "ביישן"],
  ["outdated", "מיושן"],
  ["reconcile", "להתפייס, להשלים"],
  ["suspend", "להשעות, להשהות, לעכב"],
  ["construct", "לבנות"],
  ["barn", "אסם"],
  ["liver", "כבד"],
  ["assertive", "החלטי"],
  ["stabilize", "לייצב"],
  ["momentary", "רגעי, בכל רגע ורגע"],
  ["hospitality", "הכנסת אורחים"],
  ["limb", "גף, איבר, קצה"],
  ["recordings", "הקלטות"],
  ["tormented", "לייסר, לענות"],
  ["mimic", "לחקות"],
  ["decipher", "לפענח"],
  ["genesis", "בראשית, היווצרות, התהוות, ספר בראשית"],
  ["contentious", "מעורר מחלוקת"],
  ["awe", "יראת כבוד"],
  ["presume", "להניח"],
  ["duplicate", "לשכפל"],
  ["rhythm", "קצב, קֶצֶב"],
  ["plausible", "סביר, מתקבל על הדעת"],
  ["representation", "ייצוג"],
  ["exhibit", "להציג, מוצג"],
  ["prolific", "פורה, שופע"],
  ["intense", "ניכר, רב עצמה, מעמיק, עז, אינטנסיבי"],
  ["consideration", "התחשבות, עיון"],
  ["cheerful", "עליז, שמח"],
  ["[to] intrigue", "לסקרן"],
  ["faint", "להתעלף, קלוש"],
  ["masterpiece", "יצירת מופת"],
  ["fulfill", "להגשים, להשלים, להשיג מטרה"],
  ["[to] bridle", "לרסן"],
  ["witness", "עד, להעיד"],
  ["cancel", "לבטל"],
  ["wagon", "עגלה"],
  ["delusions", "אשליות, הזיות"],
  ["frequency", "שכיחות, תדירות, תדר"],
  ["[to] brighten", "להבהיר"],
  ["frustrate", "לתסכל"],
  ["vegetarian", "צמחוני"],
  ["thriller", "מותחן"],
  ["actress", "שחקנית (בהצגה או סרט)"],
  ["induce", "לגרום, לייצר"],
  ["loyalty", "נאמנות"],
  ["intellectual", "אינטלקטואלי"],
  ["distraction", "הסחת דעת, מסיח"],
  ["magical", "קסום"],
  ["skinned", "פשט עור"],
  ["incomprehensible", "לא מובן"],
  ["certify", "להצהיר, לאשר"],
  ["monarch", "מלך"],
  ["Dutch", "הולנדי"],
  ["appreciation", "הערכה"],
  ["insanity", "אי שפיות"],
  ["gratitude", "הכרת תודה"],
  ["buttress", "משען, תימוכין, לחזק, לתמוך"],
  ["conception", "תפיסה"],
  ["invention", "המצאה"],
  ["endanger", "לסכן"],
  ["cave", "מערה"],
  ["spice", "תבלין, לתבל"],
  ["endangered", "בסכנת הכחדה"],
  ["historian", "היסטוריון"],
  ["rat", "עכברוש"],
  ["maze", "מבוך"],
  ["continuation", "המשך"],
  ["chariot", "מרכבה"],
  ["department-store", "חנות כלבו"],
  ["spicy", "פיקנטי"],
  ["adaptable", "שאפשר להתאימו"],
  ["gasoline", "בנזין"],
  ["nowadays", "בימינו, כיום"],
  ["fancy", "מחבב, מגונדר"],
  ["lend", "להלוות, להשאיל"],
  ["dispatch", "לשגר"],
  ["inanimate", "דומם"],
  ["irregular", "לא רגיל"],
  ["dedication", "הקדשה"],
  ["evolutionary", "התפתחותי"],
  ["bald", "קרח"],
  ["description", "תיאור"],
  ["puzzle", "תצרף, חידה, פאזל"],
  ["swallow", "לבלוע"],
  ["satisfactory", "משביע רצון"],
  ["adaptation", "הסתגלות, התאמה"],
  ["mediate", "לגשר, לתווך"],
  ["overtake", "לעקוף, להשיג"],
  ["dye", "צבע, לצבוע"],
  ["singer", "זמר"],
  ["manners", "נימוס"],
  ["stratum", "שכבה, רובד"],
  ["snap", "במהירות (סלנג), להישבר"],
  ["differentiate", "להבדיל, להבחין"],
  ["lone", "בודד, יחיד"],
  ["[to] arouse", "לעורר"],
  ["pest", "מטרד, מזיק (חרקים), מפגע"],
  ["amass", "לצבור, לערום"],
  ["stain", "כתם"],
  ["blade", "להב"],
  ["occurrence", "התרחשות"],
  ["hobby", "תחביב"],
  ["establishment", "מוסד"],
  ["exclude", "למנוע, לשלול, להרחיק, לגרש"],
  ["dull", "עמום, משעמם, סתום"],
  ["flexibility", "גמישות"],
  ["propagate", "להתרבות"],
  ["terrify", "להפחיד, להבעית"],
  ["horrific", "אָיוֹם"],
  ["replica", "העתק מדויק"],
  ["timid", "ביישן"],
  ["inactivity", "חוסר פעילות"],
  ["compress", "לדחוס"],
  ["restaurant", "מסעדה"],
  ["unconscious", "מחוסר הכרה"],
  ["persevere", "להתמיד"],
  ["copper", "נחושת"],
  ["straightforward", "ישיר"],
  ["declaration", "הכרזה, הצהרה"],
  ["treaty", "אמנה, הסכם, חוזה"],
  ["celebrate", "לחגוג"],
  ["suspense", "השהיה, מתח"],
  ["dread", "לפחד, לחשוש, פחד, אימה"],
  ["ridiculous", "מגוחך"],
  ["[to] enlighten", "להסביר"],
  ["erupt", "להתפרץ (בעיקר הר געש), התפרץ"],
  ["container", "מיכל, קונטיינר"],
  ["ammunition", "תחמושת"],
  ["notion", "רעיון, מושג, נטיה, דעה"],
  ["reservoir", "מאגר"],
  ["conscience", "מצפון"],
  ["overlooked", "העלים עין"],
  ["dote", "לחבב יתר על המידה, \"לחנוק באהבה\""],
  ["scales", "קשקשים (של דג)"],
  ["echo", "הד"],
  ["verdict", "פסק דין, פסיקה"],
  ["rodent", "מכרסם"],
  ["incorporate", "לכלול, לשתף, לאגד"],
  ["avarice", "תאוות בצע"],
  ["renovate", "לחדש, לשפץ, לשפץ (בניין)"],
  ["scorch", "לצרוב, לחרוך"],
  ["undertaker", "קברן"],
  ["underline", "להדגיש"],
  ["intrigued", "מסוקרן"],
  ["satisfaction", "סיפוק, שביעות רצון"],
  ["brick", "לבנה"],
  ["correspond", "להתאים, להיות תואם, להתכתב"],
  ["comprehension", "הבנה"],
  ["prevalent", "נפוץ, שכיח, רווח"],
  ["entrance", "כניסה"],
  ["transparent", "שקוף"],
  ["reprimand", "לנזוף"],
  ["detract", "להפחית, לגרוע"],
  ["baggage", "מטען, מזוודה"],
  ["pledge", "להתחייב"],
  ["annoy", "להציק, להרגיז"],
  ["subscribe", "לעשות מנוי"],
  ["filter", "פילטר, מסנן"],
  ["invoke", "לעורר, לזמן"],
  ["wonderful", "נפלא"],
  ["prejudice", "דעה קדומה"],
  ["auction", "מכירה פומבית"],
  ["prosperous", "משגשג, מצליח, פורח"],
  ["Equator", "קו המשווה"],
  ["flexible", "גמיש"],
  ["blew", "נשב (רוח), ניפח, פוצץ"],
  ["provoke", "להתגרות, להסית"],
  ["fury", "זעם"],
  ["oven", "תנור בישול"],
  ["monster", "מפלצת"],
  ["significance", "משמעות, חשיבות"],
  ["excavate", "לחשוף באמצעות חפירה"],
  ["exile", "להגלות, לגרש"],
  ["pardon", "סליחה, לסלוח, מחילה, חנינה, לחון"],
  ["symbolize", "לסמל"],
  ["bee", "דבורה"],
  ["extension", "שלוחה, הרחבה, הארכה"],
  ["pad", "לרפד"],
  ["foreseeable", "צפוי מראש, שניתן לחזותו מראש"],
  ["prosper", "לשגשג"],
  ["luggage", "מזוודות"],
  ["hive", "כוורת"],
  ["guidance", "הנחיה, הכוונה, הנהגה"],
  ["revise", "לתקן, לשפר"],
  ["envy", "קנאה, לקנא"],
  ["eagle", "נשר"],
  ["fork", "מזלג"],
  ["exhaust", "פליטה, צינור מפלט, להתיש, לעייף, אגזוז"],
  ["collaboration", "שיתוף פעולה"],
  ["cough", "שיעול, להשתעל"],
  ["counterpart", "בעל תפקיד מקביל, עמית, בן-זוג"],
  ["unjust", "לא צודק"],
  ["inspiration", "השראה"],
  ["regulate", "לווסת"],
  ["negotiation", "משא ומתן"],
  ["circulate", "להפיץ, לנוע במחזוריות"],
  ["stagger", "ללכת לא יציב, להתנודד"],
  ["overly", "יותר מידי"],
  ["appetite", "תיאבון, רצון עז"],
  ["conversation", "שיחה"],
  ["signature", "חתימה"],
  ["expedition", "מסע, משלחת חקר"],
  ["urine", "שתן"],
  ["garbage", "זבל"],
  ["bridle", "רסן, לרסן, לשים רסן על..."],
  ["eruption", "התפרצות"],
  ["achievable", "ניתן להשגה"],
  ["publicized", "פורסם"],
  ["excessively", "בצורה מוגזמת"],
  ["fool", "טיפש, לשטות במישהו"],
  ["heartless", "אכזר, קשה לב"],
  ["deviant", "סוטה"],
  ["arrogant", "יהיר, שחצן"],
  ["inevitable", "בלתי נמנע"],
  ["remedy", "תרופה"],
  ["prey", "טרף, לטרוף"],
  ["starve", "לרעוב"],
  ["unavoidable", "בלתי נמנע"],
  ["blur", "טשטוש, לטשטש"],
  ["influence", "השפעה, להשפיע"],
  ["tongue", "לשון, שפה, ניב"],
  ["sword", "חרב"],
  ["disgrace", "בושה"],
  ["candidly", "בכנות"],
  ["pupil", "תלמיד"],
  ["convict", "אסיר, אסיר בכלא, להרשיע"],
  ["translator", "מתרגם"],
  ["polite", "מנומס"],
  ["precious", "יקר"],
  ["hazardous", "מסוכן"],
  ["folk", "עממי"],
  ["slander", "השמצה, להשמיץ"],
  ["nocturnal", "של הלילה, לילי"],
  ["[to] memorize", "לשנן"],
  ["commute", "להחליף, להמיר, נסיעה משותפת מפרברים לעבודה בעיר, להמתיק (עונש), לנסוע בקביעות לעבודה"],
  ["disappoint", "לאכזב"],
  ["defiance", "סירוב בתוקף, מרי"],
  ["distinctive", "מיוחד"],
  ["compulsory", "של חובה, מהווה חובה, חובה"],
  ["tale", "סיפור, אגדה, מעשייה"],
  ["relieve", "להקהל, לגרום הקלה, להקל"],
  ["catastrophic", "הרה אסון"],
  ["academic", "אקדמי"],
  ["insist", "להתעקש"],
  ["flavor", "לתבל, טעם"],
  ["shadow", "צל, להאפיל"],
  ["transplant", "לשתול"],
  ["distinguish", "להבחין, להפריד, להבדיל"],
  ["knot", "קשר"],
  ["vegetable", "ירק"],
  ["intact", "שלם, ללא פגע"],
  ["[to] broaden", "להרחיב"],
  ["triple", "פי 3"],
  ["blink", "למצמץ"],
  ["limitation", "מגבלה"],
  ["snake", "נחש"],
  ["adhere", "לדבוק ב-, לדגול ב-"],
  ["mailman", "דוור"],
  ["handicapped", "מוגבל, נכה"],
  ["berry", "גרגרי יער"],
  ["lip", "שפה"],
  ["probe", "לחטט, לברר, לגשש"],
  ["refund", "החזר"],
  ["depression", "דיכאון"],
  ["accustomed", "מורגל"],
  ["repugnant", "מבחיל"],
  ["thief", "גנב"],
  ["afflict", "לייסר"],
  ["pregnant", "הרה (בהריון)"],
  ["horn", "צופר, קרן (של בע\"ח)"],
  ["[to] ascertain", "לוודא"],
  ["carpet", "שטיח"],
  ["aggression", "תוקפנות"],
  ["twins", "תאומים"],
  ["assimilate", "לספוג, להיטמע"],
  ["fertile", "פורה"],
  ["relapse", "הדרדר, הישנות"],
  ["footage", "קטע צילום"],
  ["sperm", "זרע"],
  ["barrack", "לצעוק ולצחוק בגסות"],
  ["interface", "ממשק"],
  ["determination", "קביעה, נחישות"],
  ["contribution", "תרומה"],
  ["peek", "להציץ"],
  ["concise", "תמציתי, תכליתי"],
  ["mentor", "מדריך רוחני"],
  ["inn", "פונדק"],
  ["soccer", "כדורגל"],
  ["petition", "עצומה, עתירה, לעתור"],
  ["languid", "נרפה"],
  ["poverty-stricken", "מוכה עוני"],
  ["legislate", "לחוקק"],
  ["curiosity", "סקרנות"],
  ["ingenious", "גאוני"],
  ["weaken", "להחליש"],
  ["oversee", "לפקח"],
  ["petroleum", "נפט"],
  ["solely", "בלבד, רק"],
  ["eloquent", "רהוט"],
  ["attire", "לבוש"],
  ["stubborn", "עקשן"],
  ["proportion", "שיעור, מידה"],
  ["makeup", "איפור"],
  ["ignorance", "בורות"],
  ["verbal", "ורבלי, מילולי"],
  ["permeate", "להתפשט, לחדור"],
  ["trigger", "הדק, להפעיל, לעורר, דבר המעורר תגובה עזה"],
  ["bail", "ערבות, לשחרר בערבות"],
  ["[to] certify", "לאשר"],
  ["fluent", "שוטף"],
  ["stroke", "ליטוף, שבץ, אירוע מוחי, מכה"],
  ["hike", "הליכה, טיול"],
  ["nationalize", "להלאים"],
  ["advertise", "פרסום, לפרסם"]
] as const;
