[
  ["admirable", "נערץ, ראוי להערצה"],
  ["admire", "להעריץ"],
  ["adore", "העריץ, אהב"],
  ["adverse", "שלילי"],
  ["analog", "אנלוגי (ההיפך מדיגיטלי)"],
  ["analogy", "אנלוגיה, הקבלה"],
  ["ancestor", "אב קדמון"],
  ["ancestry", "מוצא"],
  ["ancient", "קדום, עתיק"],
  ["assemble", "להרכיב, להתאסף"],
  ["assist", "לעזור, לסייע"],
  ["astonishment", "תדהמה, השתאות"],
  ["astound", "להדהים"],
  ["at your disposal", "לרשותך"],
  ["author", "סופר, מחבר"],
  ["avert", "להסיט, להפנות, למנוע"],
  ["background", "רקע"],
  ["benefactors", "נדבנים, תורמים"],
  ["beneficial", "מועיל, רווחי"],
  ["bold", "אמיץ, חצוף"],
  ["bold", "מודגש"],
  ["botanist", "בוטנאי"],
  ["boundary", "גבול"],
  ["branch", "ענף, סניף"],
  ["broaden", "להרחיב"],
  ["canal", "תעלה"],
  ["cast", "להשליך, לגרש"],
  ["cast", "צוות שחקנים"],
  ["caste", "מעמד חברתי"],
  ["castle", "טירה"],
  ["casual", "אגבי, רגיל, יומיומי"],
  ["chief", "ראשי, בכיר, מנהיג"],
  ["chief", "צ&#39;יף"],
  ["citizen", "אזרחים"],
  ["clarify", "להבהיר"],
  ["climate", "אקלים"],
  ["coast", "חוף"],
  ["coastline", "קו/רצועת חוף"],
  ["coat", "מעיל"],
  ["coat", "שכבה (של צבע, בטון וכו&#39;)"],
  ["coexistence", "דו-קיום"],
  ["collaborate", "לשתף פעולה"],
  ["collapse", "להתמוטט"],
  ["column", "עמוד"],
  ["column", "טור"],
  ["comfort", "נחמה"],
  ["comfortable", "נוח"],
  ["commerce", "מסחר"],
  ["commercial", "מסחרי"],
  ["commercial", "סרטון פרסומת"],
  ["commit", "ביצוע/ לבצע"],
  ["commit", "להתחייב"],
  ["committee", "ועדה"],
  ["complex", "מסובך"],
  ["complication", "סיבוך"],
  ["comply", "להסכים, לציית"],
  ["compromise", "להתפשר"],
  ["concern", "דאגה, עניין"],
  ["condition", "תנאי, מצב, מעמד"],
  ["condition", "להכשיר, להתאים"],
  ["conduct", "לנהל, לקיים"],
  ["confront", "להתעמת, לעמת"],
  ["confrontation", "עימות"],
  ["consideration", "התחשבות"],
  ["considering", "מתחשב"],
  ["consistent", "עקבי"],
  ["constant", "קבוע, רצוף"],
  ["constitute", "להקים, לייסד"],
  ["constitute", "מהווים"],
  ["construct", "לבנות"],
  ["consult", "להתייעץ"],
  ["context", "הקשר"],
  ["contract", "ללקות, להידבק (במחלה)"],
  ["contract", "חוזה, הסכם"],
  ["contract", "להתכווץ"],
  ["contradiction", "סתירה"],
  ["convoy", "שיירה"],
  ["criteria", "אמת מידה, אבן בחן"],
  ["critic", "מבקר"],
  ["criticize", "לבקר"],
  ["declaration", "הכרזה, הצהרה"],
  ["declare", "להכריז"],
  ["dedicate", "להקדיש"],
  ["dedicated", "מוקדש ל-"],
  ["dedicated", "מסור"],
  ["degenerate", "להתנוון"],
  ["degree", "דרגה"],
  ["degree", "מעלה"],
  ["delay", "עיכוב, לאחר, לדחות"],
  ["delight", "תענוג"],
  ["design", "תכנית, דוגמה, תרשים"],
  ["design", "לתכנן, לעצב"],
  ["designer", "מעצב"],
  ["detect", "לאתר, לגלות"],
  ["determine", "לקבוע"],
  ["determined", "נחוש, נחרץ"],
  ["develop", "לפתח"],
  ["development", "התפתחות, פיתוח"],
  ["diagram", "תרשים, דיאגרמה"],
  ["dialect", "ניב"],
  ["difference", "הבדל"],
  ["differences", "חילוקי דעות"],
  ["different", "שונה"],
  ["differentiate", "להבדיל, להבחין"],
  ["diminish", "לצמצם"],
  ["disaster", "אסון"],
  ["disobey", "להפר, לא לציית"],
  ["dispose", "להיפטר"],
  ["distance", "מרחק"],
  ["drastic", "דרסטי"],
  ["effective", "יעיל, אפקטיבי"],
  ["efficient", "יעיל"],
  ["effort", "מאמץ"],
  ["electricity", "חשמל"],
  ["emotion", "רגש"],
  ["enact", "לחוקק"],
  ["episode", "פרק"],
  ["ethnic", "אתני"],
  ["excel", "להצטיין"],
  ["excellent", "מצוין"],
  ["exhausting", "מתיש, מעייף"],
  ["experience", "ניסיון, לחוות"],
  ["experiment", "ניסוי, להתנסות"],
  ["exploit", "פעולות, מעשים"],
  ["exploit", "לנצל, להפיק תועלת"],
  ["export", "ייצוא"],
  ["extensive", "נרחב"],
  ["facilitate", "לסייע, לעזור, להקל"],
  ["fall apart", "להתפרק"],
  ["fast", "צום"],
  ["fast", "מהיר"],
  ["fasten", "להדק"],
  ["feminine", "נשי"],
  ["fine", "קנס"],
  ["fine", "קטן, עדין, דקיק"],
  ["fine", "משביע רצון"],
  ["fine", "משובח, מצוין"],
  ["fit", "להתאים"],
  ["fit", "בכושר"],
  ["flight", "בריחה, מנוסה"],
  ["flight", "טיסה"],
  ["forceful", "חזק"],
  ["forecast", "תחזית"],
  ["foreign", "חוץ"],
  ["foreign", "זר, נוכרי"],
  ["forfeit", "לוותר, להפסיד"],
  ["fortunate", "בעל מזל"],
  ["fortune", "מזל"],
  ["fortune", "עושר"],
  ["frame", "מסגרת, למסגר"],
  ["fund", "קרן"],
  ["fund", "לממן"],
  ["fundamental", "בסיסי (פונדמנטלי)"],
  ["fundraiser", "מגייס כספים"],
  ["funds", "כסף, הון, מקור מימון"],
  ["gap", "פער"],
  ["generated", "יצר"],
  ["generation", "דור"],
  ["govern", "למשול"],
  ["government", "ממשל"],
  ["governor", "מושל"],
  ["gratify", "לרצות"],
  ["ground", "בסיס, אדמה"],
  ["grow", "לגדול, לגדל"],
  ["grow up", "להתבגר, לגדול"],
  ["guilty", "אשם"],
  ["harsh", "נוקשה, אכזרי"],
  ["hollow", "חלול"],
  ["hundred", "מאה"],
  ["hunt", "לצוד, ציד"],
  ["hunter", "צייד"],
  ["ignorance", "בורות"],
  ["ignorant", "בור, חסר השכלה"],
  ["ignore", "להתעלם"],
  ["illiterate", "בור, אנאלפבית"],
  ["impact", "התנגשות"],
  ["impact", "השפעה"],
  ["impatient", "חסר סבלנות"],
  ["impress", "להרשים"],
  ["impressive", "מרשים"],
  ["inactivity", "חוסר פעילות"],
  ["include", "לכלול"],
  ["inclusive", "כולל"],
  ["industrious", "חרוץ, שקדן"],
  ["infected", "הודבק"],
  ["infection", "זיהום"],
  ["innocent", "תמים"],
  ["innocent", "חף מפשע"],
  ["institute", "מוסד, מכון"],
  ["institute", "לכונן"],
  ["instruction", "הוראה, הדרכה"],
  ["insurance", "ביטוח"],
  ["insure", "להבטיח"],
  ["investing", "להשקיע"],
  ["investment", "השקעה"],
  ["investor", "משקיע"],
  ["irrigation", "השקיה"],
  ["lapse", "מעידה, פליטת פה"],
  ["lapse", "פרק זמן, פקיעה, סיום"],
  ["leather", "עור"],
  ["lecture", "הרצאה"],
  ["legislate", "לחוקק"],
  ["legislation", "חקיקה"],
  ["length", "אורך"],
  ["lower", "להנמיך"],
  ["lung", "ריאה"],
  ["maintain", "לשמר"],
  ["major", "מסלול לימודים"],
  ["major", "ראשי, עיקרי"],
  ["major", "סולם מז&#39;ור (במוזיקה)"],
  ["majority", "רוב"],
  ["male", "זכר"],
  ["manage", "לנהל"],
  ["management", "ניהול"],
  ["manuscript", "כתב יד"],
  ["marine", "ימי"],
  ["maritime", "ימי"],
  ["market", "שוק"],
  ["marketing", "שיווק, לשווק"],
  ["mass", "המון, המוני"],
  ["mass", "מסה"],
  ["material", "חומר, חומרני"],
  ["measure", "למדוד"],
  ["measure", "אמצעי"],
  ["merge", "למזג, לחבר"],
  ["merger", "מיזוג"],
  ["message", "הודעה"],
  ["method", "שיטה"],
  ["mild", "מתון, עדין"],
  ["military", "צבא, צבאי"],
  ["minor", "קטין"],
  ["minor", "קטן, שולי"],
  ["minor", "סולם מינור (במוזיקה)"],
  ["minority", "מיעוט"],
  ["misconception", "דעה מוטעית"],
  ["mission", "משימה"],
  ["mode", "אופנה, מודה"],
  ["mode", "מצב, אופן, צורה"],
  ["model", "דגם, מודל, דוגמן"],
  ["modest", "צנוע"],
  ["modify", "לשנות, להתאים"],
  ["monumental", "גדול, אדיר"],
  ["negotiate", "לשאת ולתת"],
  ["negotiation", "משא ומתן"],
  ["nominated", "מועמד"],
  ["nuclear", "גרעיני"],
  ["observer", "משקיף"],
  ["obsolete", "מיושן"],
  ["occupy", "לתפוס, לאכלס"],
  ["occupy", "להעסיק"],
  ["occurrence", "התרחשות"],
  ["odd", "מוזר"],
  ["odd", "אי זוגי"],
  ["omission", "השמטה, הזנחה"],
  ["omit", "להשמיט, להזניח"],
  ["opinion", "דעה"],
  ["opponent", "יריב, מתנגד"],
  ["opportunity", "הזדמנות"],
  ["organic", "אורגני"],
  ["overlaps", "חופף"],
  ["own", "משלו"],
  ["own", "בעלות על משהו"],
  ["owner", "בעלים"],
  ["paramount", "בעל חשיבות עליונה"],
  ["pass", "לוותר"],
  ["pass", "להעביר, למסור"],
  ["pedestrian", "הולך רגל"],
  ["perhaps", "אולי"],
  ["period", "משך זמן, מחזור"],
  ["period", "תקופה"],
  ["period", "נקודה"],
  ["permanent", "קבוע"],
  ["persecution", "רדיפה (דתית)"],
  ["planet", "כוכב לכת"],
  ["plant", "צמח, עציץ, לשתול"],
  ["poll", "סקר, הצבעה"],
  ["populous", "מאוכלס בצפיפות"],
  ["post", "לפרסם ; פרסום"],
  ["post", "לשלוח בדואר ; דואר"],
  ["post", "להציב, למנות ; עמדה, משרה, תפקיד"],
  ["post", "עמוד"],
  ["postage", "דבר דואר"],
  ["postpone", "לדחות"],
  ["powerful", "רב כוח"],
  ["preferable", "עדיף"],
  ["presume", "להניח"],
  ["priest", "כומר"],
  ["privilege", "זכות יתר, פריביליגיה"],
  ["profit", "רווח"],
  ["profitable", "רווחי"],
  ["publication", "הוצאה לאור"],
  ["publicized", "פורסם"],
  ["publish", "לפרסם, להוציא לאור"],
  ["publisher", "מוציא לאור"],
  ["qualify", "להיות מוסמך"],
  ["quality", "איכות"],
  ["quarter", "רבע"],
  ["radiation", "קרינה"],
  ["rare", "נדיר"],
  ["rare", "נא (בשר)"],
  ["raw", "חי, נא (בשר)"],
  ["raw", "גולמי, גס"],
  ["receive", "לקבל"],
  ["recent", "שארע לאחרונה"],
  ["recently", "לאחרונה"],
  ["recognition", "הכרה"],
  ["record", "להקליט"],
  ["record", "שיא"],
  ["record", "רשומה"],
  ["record", "לתעד"],
  ["recover", "להתאושש"],
  ["recreate", "לשחזר, ליצור מחדש"],
  ["relax", "להירגע"],
  ["reliance", "הסתמכות"],
  ["remains", "שרידים"],
  ["remains", "נשאר, עדיין"],
  ["remove", "להסיר"],
  ["renew", "לחדש"],
  ["renown", "ידוע"],
  ["repair", "לתקן"],
  ["replace", "להחליף"],
  ["replacement", "מחליף"],
  ["rescue", "להציל"],
  ["resemble", "דומה"],
  ["residence", "מגורים"],
  ["resident", "תושב קבע"],
  ["resource", "משאב"],
  ["resourceful", "בעל תושייה"],
  ["restrain", "לרסן"],
  ["retain", "להחזיק, לשמור"],
  ["retrieve", "להשיב"],
  ["revenue", "הכנסה, רווח"],
  ["route", "מסלול, דרך"],
  ["ruin", "להרוס"],
  ["ruins", "הריסות, עיי חורבות"],
  ["sample", "דוגמית"],
  ["satisfaction", "שביעות רצון"],
  ["scatter", "לפזר"],
  ["schedule", "לוח זמנים"],
  ["sensitive", "רגיש"],
  ["sensitivity", "רגישות"],
  ["sentence", "משפט"],
  ["sentence", "גזר דין"],
  ["servant", "משרת"],
  ["serve", "להגיש, לשרת"],
  ["serve", "לשרת"],
  ["serve", "לְרַצּוֹת (עונש)"],
  ["session", "מושב"],
  ["sharp", "חד"],
  ["sheer", "מוחלט, לחלוטין"],
  ["sheer", "שקוף"],
  ["sheer", "משופע, תלול"],
  ["single", "רווק"],
  ["single", "יחיד"],
  ["skepticism", "ספקנות"],
  ["skill", "יכולת, מיומנות"],
  ["sophisticated", "מתוחכם"],
  ["spare", "מיותר, עודף"],
  ["specialize", "להתמחות"],
  ["species", "מין, זן"],
  ["specify", "לפרט"],
  ["spectator", "צופה, משקיף"],
  ["speech", "דיבור"],
  ["spoil", "לבזוז, שלל"],
  ["spoil", "להרוס"],
  ["spoil", "לפנק"],
  ["spoil", "לקלקל"],
  ["stack", "ערמה"],
  ["staple", "להדק"],
  ["station", "תחנה"],
  ["station", "להציב"],
  ["stem", "גזע"],
  ["stomach", "בטן, קיבה"],
  ["strategy", "אסטרטגיה"],
  ["subdue", "להכניע"],
  ["submit", "להגיש"],
  ["submit", "להיכנע"],
  ["subtle", "מעודן"],
  ["suitable", "ראוי, מתאים, יאה"],
  ["superb", "מעולה (איכותי)"],
  ["superficial", "שטחי"],
  ["suppression", "דיכוי"],
  ["sustain", "סבל מ-"],
  ["sustain", "להמשיך באותה צורה"],
  ["sustain", "לתמוך"],
  ["symbol", "סמל"],
  ["symbolize", "לסמל"],
  ["take place", "התרחש"],
  ["temple", "מקדש"],
  ["terms", "תנאים"],
  ["terms", "מונחים"],
  ["thousand", "אלף"],
  ["tormented", "לייסר, לענות"],
  ["tour", "סיור"],
  ["tourist", "תייר"],
  ["trust", "אמון, לבטוח"],
  ["type", "להקליד"],
  ["type", "סוג"],
  ["typically", "אופייני"],
  ["unbelievable", "לא יאמן"],
  ["underlies", "מונח ביסוד, נמצא מתחת ל-"],
  ["undertake", "לקחת על עצמך"],
  ["unemployed", "מובטל"],
  ["unexplored", "לא נחקר, לא נבדק"],
  ["unfamiliar", "לא מוכר"],
  ["unfortunate", "מצער"],
  ["unfortunately", "למרבה הצער"],
  ["unimaginable", "בלתי נתפס"],
  ["unique", "מיוחד"],
  ["unite", "לאחד"],
  ["unlock", "לפתוח, לשחרר"],
  ["unnecessary", "לא הכרחי"],
  ["uprising", "התקוממות, מרד"],
  ["urban", "עירוני"],
  ["urge", "לעודד, לדחוף ; דחף, רצון, תשוקה"],
  ["urgent", "דחוף"],
  ["vaccine", "חיסון"],
  ["variable", "משתנה"],
  ["variation", "שינוי, וריאציה"],
  ["variety", "מבחר, מגוון"],
  ["various", "מגוון"],
  ["vast", "גדול"],
  ["vertical", "מאונך"],
  ["vigorously", "במרץ"],
  ["violate", "להפר, לחלל"],
  ["violation", "עבירה, הפרה"],
  ["volunteer", "להתנדב, מתנדב"],
  ["vote", "קול, הצבעה, להצביע"],
  ["wage", "לערוך, לנהל"],
  ["wage", "משכורת"],
  ["ward", "מחלקה"],
  ["wide", "רחב"],
  ["willing", "מוכן"],
  ["wise", "חכם, פיקח"],
  ["wish", "משאלה, לבקש"],
  ["withhold", "לעכב, לעצור, לא לתת"],
  ["worldwide", "כלל עולמי, בכל העולם"],
  ["worse", "גרוע יותר"],
  ["worthy", "ראוי"],
  ["yield", "להיכנע, לוותר, לסגת"],
  ["yield", "להניב, להפיק"],
  ["zone", "אזור"]
]
