export default [
  ["propose", "להציע (נישואין למשל), להציע נישואין, להציע"],
  ["gate", "שער"],
  ["prosperity", "צמיחה, שגשוג"],
  ["yearn", "לכמוה"],
  ["pretext", "אמתלה, תואנה"],
  ["encompass", "להקיף, לכלול"],
  ["sufficiently", "באופן שיספק"],
  ["fever", "חום (של מחלה)"],
  ["represent", "מייצג, לייצג, לסמל"],
  ["retreat", "נסיגה, לסגת"],
  ["permission", "היתר, רשות"],
  ["unbelievable", "לא יאמן"],
  ["joke", "בדיחה"],
  ["mercy", "רחמים"],
  ["dynasty", "שושלת"],
  ["astronomy", "אסטרונומיה"],
  ["[to] bestow", "להעניק"],
  ["duel", "דו-קרב"],
  ["scan", "סריקה, לסרוק"],
  ["slate", "רעף, לוח, להכניס מישהו לרשימה"],
  ["specialize", "להתמחות"],
  ["invade", "לחדור, לפלוש"],
  ["deliberate", "להרהר, לשקול אפשרויות, מכוון, לדון, לשקול, במכוון, לבחון"],
  ["dose", "מינון, מנה"],
  ["guarantee", "להבטיח, ערבות"],
  ["grandson", "נכד"],
  ["corresponding", "תואם"],
  ["critique", "ביקורת, מאמר ביקורת"],
  ["unnatural", "לא טבעי"],
  ["suture", "לבצע תפר רפואי"],
  ["instruction", "הדרכה, הוראה"],
  ["heretic", "כופר"],
  ["violation", "הפרה, עבירה"],
  ["standardize", "לתקנן"],
  ["quantify", "לכמת"],
  ["fraud", "מרמה, הונאה"],
  ["flip", "להפוך צד, סלטה, לזרוק, להעיף"],
  ["portrait", "דיוקן"],
  ["palm", "דקל, כף יד"],
  ["cord", "מיתר"],
  ["studio", "סטודיו"],
  ["particulars", "פריטים"],
  ["suspension", "השהייה, דחייה"],
  ["expand", "להתפשט, להתרחב, להרחיב"],
  ["imply", "לרמוז, לרמז"],
  ["grandmother", "סבתא"],
  ["confine", "להגביל"],
  ["equipment", "ציוד"],
  ["resort", "לנקוט באמצעים, אתר נופש"],
  ["betray", "לבגוד"],
  ["deficient", "נטול משהו, חסר"],
  ["prediction", "תחזית, ניבוי, חיזוי"],
  ["amiss", "לא כשורה"],
  ["endure", "להחזיק מעמד, לסבול"],
  ["steal", "לגנוב"],
  ["painter", "צייר"],
  ["impress", "להרשים"],
  ["symptom", "סימפטום"],
  ["subdue", "להכניע"],
  ["uncle", "דוד"],
  ["defective", "פגום"],
  ["rain", "גשם"],
  ["trait", "תכונה, תכונת אופי"],
  ["blend", "לערבב"],
  ["timber", "עץ"],
  ["applicant", "מועמד"],
  ["sugar", "סוכר"],
  ["consciously", "במודע"],
  ["adulthood", "בגרות"],
  ["capital punishment", "עונש מוות"],
  ["rebel", "מורד"],
  ["scarce", "נדיר"],
  ["cater", "לספק"],
  ["cheat", "לרמות, לבגוד"],
  ["donation", "מתנה, תרומה"],
  ["nest", "קן, לקונן"],
  ["persist", "להתמיד, להתעקש"],
  ["dissolve", "להתמוסס"],
  ["conveniently", "באופן נח"],
  ["tiny", "קטנטן"],
  ["raid", "פשיטה"],
  ["run, ran", "לרוץ, רץ"],
  ["pet", "חיית מחמד"],
  ["accelerate", "להאיץ"],
  ["inferior", "נחות"],
  ["exquisite", "מצוין, חד, אנין, מעודן"],
  ["institution", "מוסד \\ ארגון"],
  ["amaze", "להדהים"],
  ["strife", "מאבק, עימות"],
  ["interpreter", "פרשן, מתורגמן"],
  ["victim", "קורבן"],
  ["weekend", "סוף שבוע"],
  ["spray", "לפזר, לרסס"],
  ["respectable", "מכובד, מעורר כבוד"],
  ["impatient", "חסר סבלנות"],
  ["literate", "משכיל, מלומד"],
  ["miserable", "אומלל"],
  ["knees", "ברכיים"],
  ["constitution", "חוקה, הרכב"],
  ["enclose", "לצרף"],
  ["density", "צפיפות"],
  ["cathedral", "קתדרלה"],
  ["acknowledge", "להכיר, לדעת"],
  ["solitude", "בדידות"],
  ["deteriorate", "להדרדר, להידרדר, להחמיר"],
  ["mediocre", "בינוני (במובן שלילי)"],
  ["gradually", "בהדרגה"],
  ["virtue", "מעלה"],
  ["stench", "סירחון"],
  ["suggestion", "הצעה"],
  ["oxygen", "חמצן"],
  ["collide", "להתנגש"],
  ["thorax", "בית החזה, חזה"],
  ["texture", "מרקם, טקסטורה"],
  ["respect", "לכבד, כבוד"],
  ["transmit", "לשדר"],
  ["ambiguity", "דו משמעות, עמימות"],
  ["bell", "פעמון"],
  ["wrap", "מעטפת, לעטוף"],
  ["publication", "הוצאה לאור"],
  ["rivalry", "יריבות"],
  ["categorize", "למיין, לסווג, לקטלג"],
  ["forest", "יער"],
  ["municipality", "עירייה"],
  ["potent", "בעל כוח השפעה, חזק"],
  ["explosion", "פיצוץ"],
  ["monitor", "להשגיח, מוניטור"],
  ["petty", "קטנוני, חסר חשיבות, קטן"],
  ["compel", "לחייב, לאלץ"],
  ["evoke", "לעורר, להעלות"],
  ["regret", "חרטה, להתחרט"],
  ["smoke", "לעשן, עשן"],
  ["revoke", "לבטל, לשלול"],
  ["terminate", "לסיים, לחסל"],
  ["blasphemy", "חילול השם"],
  ["diminish", "לצמצם, להפחית"],
  ["recognition", "זיהוי, הכרה"],
  ["coastline", "קו, רצועת חוף"],
  ["predictive", "נבואי"],
  ["indifferent", "חסר עניין, אדיש"],
  ["priceless", "ללא מחיר, בעל ערך עצום"],
  ["shrewd", "פיקח, חכם"],
  ["[to] fracture", "להישבר"],
  ["experiment", "ניסוי, להתנסות"],
  ["snow", "שלג"],
  ["requirement", "דרישה, צורך"],
  ["exhausting", "מעייף, מתיש"],
  ["accompany", "ללוות, להתלוות"],
  ["draw (drew)", "שלף, לשלוף"],
  ["composed", "הלחין"],
  ["destruction", "הרס"],
  ["compile", "לקבץ, לאסוף"],
  ["superficial", "שטחי"],
  ["donor", "תורם"],
  ["grandfather", "סבא"],
  ["simplicity", "פשטות"],
  ["despair", "להתייאש"],
  ["dissent", "חילוקי דעות, להתנגד"],
  ["bury", "לקבור"],
  ["inspection", "בדיקה, פיקוח"],
  ["gym", "אולם ספורט"],
  ["navigate", "לנווט"],
  ["advocate", "לייעץ, לדגול ב..., פרקליט, לסנגר"],
  ["concur", "להסכים"],
  ["essence", "מהות"],
  ["poorly", "בצורה גרועה"],
  ["tiresome", "מעייף, מייגע"],
  ["harmless", "לא מזיק, שאינו מזיק"],
  ["probable", "מתקבל על הדעת, סביר"],
  ["mole", "שומה, חפרפרת"],
  ["cousin", "בן-דוד"],
  ["penned", "כתב"],
  ["suspicious", "חשוד (משהו)"],
  ["favored", "מועדף"],
  ["neighbor", "שכן"],
  ["polish", "פולני, להבריק, לצחצח"],
  ["hereditary", "תורשתי"],
  ["catastrophe", "אסון"],
  ["emergent", "מגיח, שזה עתה נוצר, ההולך ומתגבש"],
  ["disappear", "להעלם"],
  ["crop", "לקצץ, יבול"],
  ["secret", "סוד"],
  ["genus", "מין, סוג"],
  ["incentive", "תמריץ"],
  ["sequel", "המשך"],
  ["transform", "לשנות צורה, להפוך ל..., להשתנות"],
  ["wound", "מתוח, פצע, נמתח"],
  ["competition", "תחרות"],
  ["officiate", "לכהן, לערוך"],
  ["offensive", "פוגעני, מעליב"],
  ["potato", "תפוח אדמה"],
  ["compensate", "לפצות"],
  ["corruption", "שחיתות"],
  ["leisure", "פנאי"],
  ["interrupt", "להפריע"],
  ["dairy", "מחלבה"],
  ["tranquil", "רגוע, שקט"],
  ["instant", "בהרף עין, מיידי, רגע"],
  ["occupation", "תחום תעסוקה, מקצוע, תפיסת טריטוריה על ידי מדינה או צבא"],
  ["agony", "ייסורים"],
  ["skepticism", "ספקנות"],
  ["valve", "שסתום"],
  ["spike", "יתד"],
  ["vivid", "שופע, חד, בהיר, ססגוני"],
  ["evolution", "התפתחות"],
  ["conscious", "מודע, בעל הכרה"],
  ["fiction", "לא אמיתי, סיפורת, בדיון"],
  ["rice", "אורז"],
  ["admittedly", "לכל הדעות, מוסכם"],
  ["respective", "שייך בהתאמה"],
  ["donate", "לתרום"],
  ["bore", "לקדוח (חור), שעמום, לשעמם"],
  ["repetition", "חזרה"],
  ["entitled", "זכאי"],
  ["hitherto", "נכון לעכשיו, עד כה"],
  ["haul", "לגרור"],
  ["curious", "סקרן"],
  ["precede", "כאשר אירוע מקדים אירוע אחר"],
  ["embarrassing", "מביך"],
  ["infection", "זיהום"],
  ["orient", "להתמצא"],
  ["fortnight", "שבועיים"],
  ["reliance", "הסתמכות"],
  ["nursery", "חדר ילדים"],
  ["examine", "לבחון"],
  ["sophisticated", "מתוחכם"],
  ["controversial", "שנוי במחלוקת"],
  ["rage", "זעם"],
  ["disastrous", "נוראי"],
  ["destructive", "הרסני"],
  ["cumulative", "מצטבר"],
  ["crossroads", "צומת"],
  ["disobey", "להפר, לא לציית"],
  ["dominate", "להיות דומיננטי, לשלוט"],
  ["subsequent", "עוקב"],
  ["attendance", "נוכחות"],
  ["stamp", "בול, חותמת"],
  ["delegate", "להאציל, להסמיך"],
  ["acclaim", "להריע, לשבח"],
  ["degenerate", "להתנוון"],
  ["arrangement", "סידור"],
  ["[to] disturb", "להפריע"],
  ["stricken", "מוכה"],
  ["polar", "הפוך לחלוטין, קוטבי"],
  ["monumental", "גדול, אדיר"],
  ["southern", "דרומי"],
  ["implicate", "לסבך, לערב"],
  ["conceal", "להסתיר"],
  ["grain", "גרעין, תבואה, לטחון"],
  ["performer", "מבצע, מציג"],
  ["hectic", "קדחתני"],
  ["query", "חקירה, שאלה"],
  ["cede", "לוותר על"],
  ["eulogy", "הספד, יצירה שנועדה לפאר ולשבח"],
  ["sunlight", "אור יום"],
  ["malignant", "ממאיר"],
  ["detail", "לפרט, פרט"],
  ["awkward", "מביך, מוזר, מגושם"],
  ["veteran", "יוצא צבא, ותיק, חייל משוחרר"],
  ["offend", "להעליב"],
  ["procure", "להשיג משהו שקשה להשגה"],
  ["arouse", "לעורר"],
  ["affection", "חיבה"],
  ["rumor", "שמועה"],
  ["conclusively", "סופית, באופן החלטי"],
  ["noticeable", "שקל להבחין בו"],
  ["pool", "בריכה"],
  ["smother", "לכסות, לחנוק"],
  ["intriguing", "מעניין"],
  ["inspiring", "נותן השראה"],
  ["truck", "קרון משא, משאית"],
  ["sympathetic", "אוהד"],
  ["communication", "תקשורת"],
  ["imprison", "לכלוא"],
  ["remarkable", "יוצא דופן, ראוי לציון"],
  ["conviction", "הרשעה, שכנוע עצמי"],
  ["potter", "קדר"],
  ["spectator", "צופה, משקיף"],
  ["theory", "השערה, תיאוריה"],
  ["fashion", "אופנה, לעצב"],
  ["disregard", "להתעלם"],
  ["wring", "לסחוט"],
  ["ample", "גדול, מספיק, שופע"],
  ["owe", "להיות חייב"],
  ["breed", "להפרות, להרביע, גזע, מין"],
  ["conspiracy", "קשר, מזימה"],
  ["prominent", "בולט, חשוב"],
  ["achievement", "הישג"],
  ["golden", "מוזהב"],
  ["charm", "קסם"],
  ["punish", "להעניש"],
  ["offender", "פוגע, פושע"],
  ["bent", "כופף"],
  ["forceful", "חזק"],
  ["boil", "להרתיח"],
  ["modernize", "להפוך למודרני"],
  ["slope", "שיפוע, מדרון"],
  ["blame", "להאשים"],
  ["wave", "גל"],
  ["salt", "מלח"],
  ["hatch", "צוהר, לבקוע (מביצה), פתח"],
  ["heartfelt", "כן, רציני, יוצא מהלב"],
  ["devise", "להמציא, להגות תוכנית, לתכנן"],
  ["stride", "לצעוד, צעד"],
  ["greet", "לברך, לקבל פנים"],
  ["survival", "הישרדות"],
  ["warmth", "חום"],
  ["composition", "הרכב, חיבור"],
  ["pit", "בור"],
  ["compatible", "ראוי, הולם, תואם, מתאים"],
  ["abundance", "שפע"],
  ["deterrent", "מונע, מעכב"],
  ["replacement", "חלופה, מחליף"],
  ["loosely", "באופן רפוי"],
  ["confidential", "חסוי, סודי, חשאי"],
  ["immensely", "במידה רבה"],
  ["stumble", "למעוד"],
  ["spread", "התפשטות, להתפשט, פיזור, לפרוש, ממרח, למרוח"],
  ["barrier", "מחסום"],
  ["withdraw", "לפרוש, לסגת"],
  ["Dead Sea", "ים המלח"],
  ["noticeably", "באופן שקל להבחין בו"],
  ["conversion", "המרה, החלפה, חזרה בתשובה"],
  ["ticket", "כרטיס"],
  ["tilt", "להטות, שיפוע"],
  ["antique", "עתיק, ענתיקה"],
  ["reliable", "אמין, שניתן לסמוך עליו"],
  ["strengthen", "לחזק"],
  ["junction", "צומת"],
  ["distort", "לסלף, לעוות, לעקם"],
  ["encounter", "מפגש"],
  ["renown", "ידוע"],
  ["ice cream", "גלידה"],
  ["nutrition", "תזונה"],
  ["commence", "להתחיל"],
  ["prophecy", "נבואה"],
  ["windmill", "טחנת רוח"],
  ["deer", "צבי, צבאים, איל"],
  ["residence", "מגורים"],
  ["ark", "תיבה"],
  ["translation", "תרגום"],
  ["beast", "מפלצת, חיה"],
  ["tomb", "קבר"],
  ["discipline", "משמעת, מחקר, לחנך, להעניש, להשליט משמעת, תחום לימוד, למשמע, תחום (במדע), דיסציפלינה"],
  ["displace", "להחליף את מקומו, לעקור ממקומו"],
  ["frequent", "תכוף, תדיר, שכיח, לבקר (לעיתים קרובות)"],
  ["intervene", "להתערב"],
  ["basin", "אגן, גיגית, אגם מים, כיור, קערה"],
  ["pertinent", "רלוונטי, שייך לנושא"],
  ["gene", "גן (תורשתי)"],
  ["throughout", "בכל, במשך"],
  ["devotion", "התמסרות"],
  ["cliff", "צוק"],
  ["engineer", "מהנדס, להנדס"],
  ["youngster", "צעיר"],
  ["roof", "גג"],
  ["illiterate", "אנאלפבית, בור"],
  ["lunch", "ארוחת צהריים"],
  ["invisible", "בלתי נראה"],
  ["[to] evacuate", "לפנות"],
  ["responsible", "אחראי"],
  ["juncture", "הצטלבות (בזמן)"],
  ["camouflage", "הסוואה"],
  ["taxation", "מיסוי"],
  ["perception", "תפיסה, ראייה לעומק"],
  ["victory", "ניצחון"],
  ["pan", "מחבת"],
  ["affinity", "זיקה, משיכה, קירבה"],
  ["condemned", "לגנות, נידון ל-"],
  ["darkness", "חשיכה"],
  ["interpretation", "פרשנות"],
  ["vigorously", "במרץ"],
  ["delicate", "עדין"],
  ["index", "תוכן עניינים, אינדקס"],
  ["incidental", "מקרי"],
  ["foster", "מאומץ, אומן"],
  ["collaborate", "לשתף פעולה"],
  ["principle", "עיקרי, עיקרון"],
  ["genetic", "גנטי, תורשתי"],
  ["jester", "ליצן חצר"],
  ["prohibit", "למנוע, לאסור"],
  ["prone", "נוטה"],
  ["perceive", "לראות, להבחין"],
  ["passive", "סביל"],
  ["divinity", "אלוהות"],
  ["unanimous", "פה-אחד"],
  ["recipe", "מתכון"],
  ["loan", "הלוואה"],
  ["principal", "מנהל בי\"ס, מנהל בית ספר, עיקרי, חשוב"],
  ["wail", "בכי, לילל, זעקה"],
  ["extremist", "דוגל בצעדים קיצוניים"],
  ["dust", "לאבק, אבק"],
  ["mastery", "מומחיות"],
  ["overlaps", "חופף"],
  ["discriminate", "להפלות, להבחין"],
  ["formidable", "נאדר, חזק, מפחיד, מאיים"],
  ["mood", "מצב רוח"],
  ["beard", "זקן"],
  ["comparative", "השוואתי, יחסי"],
  ["fasten", "להדק"],
  ["innate", "מולד"],
  ["fragile", "עדין, שביר"],
  ["readily", "ללא קושי"],
  ["department", "מחלקה"],
  ["definitive", "סופי ומוחלט"],
  ["improvise", "לאלתר"],
  ["relationship", "מערכת יחסים"],
  ["ambition", "שאפתנות, שאיפה"],
  ["fur", "פרווה"],
  ["conservative", "שמרני"],
  ["spy", "מרגל, לרגל"],
  ["drag", "לגרור"],
  ["coordinator", "מתאם"],
  ["considerate", "מתחשב"],
  ["plague", "מגפה"],
  ["offset", "לקזז"],
  ["memorial", "מצבה, תזכיר"],
  ["warn", "להזהיר"],
  ["insult", "עלבון, להעליב"],
  ["deaf", "חרש"],
  ["slavery", "עבדות"],
  ["at your disposal", "לרשותך"],
  ["abduct", "חטיפה, לחטוף"],
  ["inferred", "נגזר, משתמע"],
  ["manufacture", "ייצר"],
  ["writer", "סופר"],
  ["conserve", "לשמר"],
  ["outdo", "לעשות טוב יותר, להאפיל"],
  ["loath", "לתעב"],
  ["uncharted", "לא מתועד"],
  ["predecessors", "קודמים"],
  ["lodge", "אכסנייה, להתאכסן"],
  ["botanist", "בוטנאי"],
  ["populous", "מאוכלס בצפיפות"],
  ["qualifications", "נתונים, כישורים"],
  ["consequence", "תוצאה"],
  ["eliminate", "לפסול, לחסל"],
  ["equip", "לצייד"],
  ["expectancy", "ציפייה"],
  ["outstanding", "מצוין, יוצא מן הכלל"],
  ["ugly", "מכוער"],
  ["naval", "ימי"],
  ["drift", "לסחוף, סחף, מגמה, להיסחף, זרם"],
  ["garden", "גן"],
  ["radiation", "קרינה"],
  ["adversary", "יריב"],
  ["cloud", "ענן"],
  ["fruitful", "נושא פרי, פורה"],
  ["mirror", "מראה"],
  ["pleasure", "תענוג, לענג"],
  ["dump", "לשפוך"],
  ["alternately", "לסירוגין"],
  ["disturb", "להפריע"]
] as const;
