export default [
  ["quake", "רעד"],
  ["nurture", "לטפח, להזין, לחנך"],
  ["hypocrisy", "צביעות"],
  ["disinfect", "לחטא"],
  ["conservation", "שימור"],
  ["empathy", "הזדהות, אמפתיה"],
  ["patience", "סבלנות"],
  ["sensation", "תחושה"],
  ["loudspeaker", "רמקול"],
  ["shatter", "לנפץ, להרוס, לקעקע"],
  ["disappointment", "אכזבה"],
  ["faulty", "לקוי, לא תקין"],
  ["transition", "מעבר, שינוי"],
  ["mock", "ללעוג"],
  ["hegemony", "הגמוניה"],
  ["civilize", "לתרבת"],
  ["authoritative", "סמכותי, מהימן"],
  ["harmony", "הרמוניה"],
  ["poignant", "חריף, נוקב"],
  ["engrave", "לחרוט"],
  ["robe", "חלוק"],
  ["brutish", "בהמי, אכזרי"],
  ["emission", "פליטה"],
  ["atrocity", "זוועה"],
  ["hostility", "עוינות"],
  ["perplexed", "לחוש בלבול ודאגה"],
  ["frog", "צפרדע"],
  ["fascination", "משיכה, קסם"],
  ["abstain", "להתנזר, להימנע ממשהו"],
  ["arousing", "מעורר"],
  ["diversion", "הטיה, פעילות לשעות הפנאי, פעולת הסחה"],
  ["recur", "קרה שוב"],
  ["slant", "אלכסון, נטייה"],
  ["oblige", "לחייב, להכריח"],
  ["casino", "קזינו"],
  ["impartially", "באופן הוגן, ללא אפליה"],
  ["discord", "סכסוך, מחלוקת, צרימה"],
  ["intervention", "התערבות"],
  ["tact", "טקט"],
  ["illuminate", "להאיר"],
  ["revision", "בדיקה מחדש לצורך שיפור"],
  ["nobility", "אצולה, התכונות התרומיות, הטובות"],
  ["sailor", "ימאי"],
  ["roast", "לקלות, צלי"],
  ["applaud", "להריע, למחוא כף, מחא כפיים, הריע"],
  ["awe inspiring", "מעורר יראת כבוד"],
  ["sculpture", "פסל"],
  ["seizure", "התקף"],
  ["emphasize", "להדגיש"],
  ["unofficial", "בלתי רשמי"],
  ["cloak", "מסווה, להסוות"],
  ["ridicule", "ללעוג, לעג"],
  ["civilization", "תרבות"],
  ["outgrowth", "תוצאה טבעית של משהו"],
  ["confession", "וידוי"],
  ["collision", "התנגשות"],
  ["syrup", "סירופ"],
  ["susceptible", "רגישות, רגיש, פגיע, מועד"],
  ["contradict", "לסתור"],
  ["astonish", "מדהים, להדהים"],
  ["tolerance", "סיבולת, סובלנות"],
  ["misty", "מעורפל"],
  ["responsibility", "אחריות"],
  ["conspicuous", "בולט"],
  ["confiscate", "להחרים"],
  ["tension", "מתח"],
  ["rainbow", "קשת"],
  ["astound", "להדהים"],
  ["heartthrob", "פעימת לב"],
  ["concerted", "מתואם"],
  ["prank", "מתיחה"],
  ["glove", "כפפה"],
  ["resumption", "חידוש"],
  ["sponsor", "נותן חסות"],
  ["monk", "נזיר"],
  ["expend", "לגמור, לבזבז, לפזר"],
  ["opportune", "משהו שקרה בעיתוי מוצלח"],
  ["restriction", "הגבלה"],
  ["tame", "לאלף, לבית"],
  ["unexplored", "לא נחקר, לא נבדק"],
  ["rebellion", "מרד"],
  ["delinquent", "נזנח, נשכח, עבריין"],
  ["deduction", "מסקנה, היקש (לוגי)"],
  ["sprang", "נבע"],
  ["docile", "קל לשליטה, צייתן, כנוע, נח"],
  ["lifestyle", "אורח חיים"],
  ["indebted", "חייב ל-, אסיר תודה"],
  ["accumulation", "הצטברות"],
  ["harness", "לרתום"],
  ["timeline", "ציר זמן"],
  ["cavity", "חור"],
  ["keystone", "אבן מפתח"],
  ["dwell", "להתגורר"],
  ["fracture", "לשבור, שבר"],
  ["impartiality", "ניטרליות, הגינות"],
  ["obedience", "ציות, משמעת, צייתנות"],
  ["plunge", "טבילה"],
  ["incidence", "כמות, הִקָּרוּת (משהו שקורה)"],
  ["treatment", "טיפול"],
  ["surreptitiously", "באופן חשאי, סודי"],
  ["recipient", "נמען"],
  ["recuperate", "להחלים"],
  ["prick", "לדקור"],
  ["surpass", "להצטיין, לעלות על"],
  ["intelligence", "מודיעין, אינטליגנציה"],
  ["dictator", "עריץ, דיקטטור"],
  ["dwelling", "משכן, בית"],
  ["adherence", "היצמדות, דבקות, הידבקות"],
  ["outweigh", "עולה על, שוקל יותר מ-"],
  ["implementation", "מימוש, יישום, ביצוע"],
  ["existence", "קיום"],
  ["kite", "עפיפון"],
  ["reproduction", "שחזור"],
  ["vengeance", "נקמה"],
  ["dandy", "גנדרני"],
  ["artifact", "חפץ, פריט אומנות"],
  ["aura", "הילה"],
  ["devoid", "חסר, נטול"],
  ["implication", "רמז, להיות מעורב"],
  ["distortion", "עיוות, סילוף"],
  ["blindness", "עיוורון"],
  ["monkey", "קוף"],
  ["exotic", "אקזוטי, מארץ זרה"],
  ["maximize", "למקסם"],
  ["philosophy", "פילוסופיה"],
  ["elude", "לברוח, להתחמק"],
  ["portray", "לתאר, לצייר"],
  ["eel", "צלופח"],
  ["rainfall", "ירידת גשמים"],
  ["propaganda", "תעמולה"],
  ["contributory", "תורם, מסייע"],
  ["revolt", "מרד"],
  ["anesthesia", "הרדמה"],
  ["mischief", "נזק, מעשה קונדס"],
  ["pivot", "ציר, לסובב על ציר"],
  ["bolster", "לתמוך"],
  ["ironic", "אירוני"],
  ["illusion", "אשליה"],
  ["lineage", "ייחוס, שושלת"],
  ["imitate", "לחקות"],
  ["scorn", "לבוז, לזלזל, מנודה"],
  ["drawback", "חסרון, עיכוב"],
  ["impulsively", "ללא שיקול דעת"],
  ["insulation", "בידוד"],
  ["predestined", "נקבע מראש"],
  ["dental", "שקשור בשיניים"],
  ["esteemed", "מכובד"],
  ["emit", "לפלוט, להוציא"],
  ["knife (knives)", "סכין (סכינים)"],
  ["magnificent", "מדהים"],
  ["dagger", "פגיון"],
  ["peach", "אפרסק"],
  ["commends", "לציין לשבח"],
  ["consequential", "חשוב, מכריע"],
  ["reconstruct", "לשחזר"],
  ["pigeon", "יונה"],
  ["worm", "תולעת"],
  ["segment", "קטע, מקטע"],
  ["stalk", "לעקוב, להטריד"],
  ["iceberg", "קרחון"],
  ["spontaneously", "ללא תכנון"],
  ["usher", "סדרן"],
  ["villain", "רשע, נבל"],
  ["shave", "גילוח, לגלח"],
  ["grocery", "מכולת"],
  ["indefinitely", "ללא הגבלה"],
  ["butcher", "קצב, לשחוט"],
  ["enthusiasm", "התלהבות"],
  ["transcript", "תמליל, פרוטוקול"],
  ["humility", "ענוה"],
  ["demonstration", "הוכחה, הפגנה, הדגמה"],
  ["infectious", "מדבק"],
  ["entertainment", "בידור"],
  ["unforgettable", "בלתי נשכח"],
  ["moth", "עש"],
  ["stove", "תנור, כיריים"],
  ["divergence", "התפצלות, סטייה"],
  ["edible", "אכיל"],
  ["odor", "ריח, ניחוח"],
  ["insistence", "התעקשות, עקשנות"],
  ["laborer", "פועל"],
  ["absorption", "ספיגה"],
  ["incline", "להתאים, לנטות, שיפוע"],
  ["dilemma", "דילמה, התלבטות בין שתי ברירות, בעיה"],
  ["entwine", "לשלב, לקלוע, לשזור"],
  ["jog", "ריצה, ג&#39, וגינג, לרוץ"],
  ["diffusion", "תערובת"],
  ["industrious", "חרוץ, שקדן"],
  ["discrepancy", "שוני, סתירה, פער, אי התאמה, העדר הסכמה"],
  ["pottery", "קדרות"],
  ["dwarf", "לגמד, גמד"],
  ["defamation", "השמצה, הכפשה"],
  ["immigrate", "להגר"],
  ["dentist", "רופא שיניים"],
  ["overrate", "להעריך יתר על המידה"],
  ["jungle", "ג&#39, ונגל"],
  ["vinegar", "חומץ"],
  ["engagement", "אירוסין, העסקה, התחייבות"],
  ["hinder", "לעכב"],
  ["sighting", "תצפית, מראה"],
  ["reap", "לקצור"],
  ["cereal", "דגני בוקר"],
  ["opportunism", "ניצול כל הזדמנות לרווח"],
  ["excavation", "חפירה"],
  ["gunpowder", "אבק שריפה"],
  ["agitate", "להסעיר, לזעזע, לעצבן"],
  ["utilize", "השתמש"],
  ["reborn", "נולד מחדש"],
  ["temperament", "מזג, אופי"],
  ["illusive", "מטעה, מתעתע"],
  ["harass", "להציק"],
  ["ivory", "שנהב"],
  ["correlate", "לתאם, לקשר"],
  ["flattery", "חנופה"],
  ["mosquito", "יתוש"],
  ["minimize", "להקטין למינימום, למזער"],
  ["pharmacy", "בית מרקחת"],
  ["clarification", "הבהרה, טיהור"],
  ["bleak", "עגום"],
  ["enrich", "להעשיר"],
  ["gratify", "לרצות"],
  ["sequence", "רצף"],
  ["instrument", "כלי"],
  ["proponent", "תומך"],
  ["wickedly", "ברשעות"],
  ["inhibit", "לרסן"],
  ["saga", "סיפור, סאגה"],
  ["robbery", "שוד"],
  ["coordination", "תיאום, קואורדינציה"],
  ["underlies", "מונח ביסוד, נמצא מתחת ל-"],
  ["revived", "קם לתחייה, התחדש"],
  ["extraordinary", "בלתי רגיל"],
  ["stunned", "נדהם, היה המום"],
  ["situate", "למקם"],
  ["distinction", "מצוינות, ייחוד, אבחנה, הצטיינות, הפרדה"],
  ["onion", "בצל"],
  ["disgust", "גועל, להגעיל"],
  ["paradox", "סתירה, פרדוקס"],
  ["reconciliation", "פיוס"],
  ["livelihood", "מחיה"],
  ["bland", "תפל"],
  ["vocabulary", "אוצר מילים"],
  ["brightness", "בהירות"],
  ["weave", "לטוות, לארוג"],
  ["camel", "גמל"],
  ["superfluous", "עודף, מיותר"],
  ["plight", "צרה, סכנה"],
  ["ascribe", "לייחס, לשייך"],
  ["retirement", "פרישה"],
  ["revolution", "מהפכה"],
  ["eyesight", "ראייה, כוונת"],
  ["forgive", "לסלוח"],
  ["persecution", "רדיפה (דתית)"],
  ["unimaginable", "בלתי נתפס"],
  ["conscientious", "מודרך על יד מצפונו"],
  ["extinction", "הכחדה"],
  ["splendor", "פאר"],
  ["playwright", "מחזאי"],
  ["spring, sprang", "קפיץ, לקפוץ, קפץ"],
  ["contagious", "מדבק"],
  ["strenuous", "מאמץ, קשה"],
  ["assertion", "טענה תקיפה, טענה"],
  ["coffin", "ארון מתים"],
  ["eminence", "חשיבות"],
  ["foresee", "לצפות מראש, לחזות מראש"],
  ["envelope", "מעטפה"],
  ["infiltrate", "להסתנן"],
  ["vaccination", "חיסון"],
  ["outspoken", "מדבר גלויות, ישיר"],
  ["masculine", "גברי"],
  ["recurring", "חוזר, נשנה"],
  ["sticky", "דביק"],
  ["temptation", "פיתוי"],
  ["wrought", "מעוצב, מחושל"],
  ["equivocal", "שאינו חד משמעי"],
  ["emigration", "הגירה"],
  ["forerunner", "שליח, חלוץ, מבשר, אות, סימן מבשר באות"],
  ["bottomless", "ללא תחתית"],
  ["legible", "קריא"],
  ["slaughter", "לטבוח, לשחוט, טֶבַח"],
  ["impregnable", "בלתי מנוצח, שאין להכניעו"],
  ["ceaseless", "ללא הפסק"],
  ["ecological", "אקולוגי"],
  ["cornerstone", "אבן פינה"],
  ["expel", "להשעות, להרחיק"],
  ["autograph", "חתימה"],
  ["preclude", "למנוע מאירוע להתקיים"],
  ["luminous", "זוהר, בוהק, מאיר"],
  ["rhyme", "חרוז"],
  ["patiently", "בסבלנות"],
  ["double standard", "מוסר כפול"],
  ["verifiable", "בר אימות, ניתן לבירור"],
  ["lurking", "אורב, מתגנב"],
  ["disdain", "זלזול, בוז"],
  ["[to] inspect", "לבדוק"],
  ["prejudicial", "גזעני"],
  ["pregnancy", "הריון"],
  ["granddaughter", "נכדה"],
  ["lame", "צולע"],
  ["enlist", "לגייס, להתגייס"],
  ["trim", "לגזום"],
  ["implement", "ליישם, להוציא לפועל"],
  ["marble", "גוּלָּה, שיש"],
  ["bead", "חרוז"],
  ["rebuttal", "הפרכה, סתירה"],
  ["fluency", "שטף"],
  ["ode", "שיר הלל"],
  ["purse", "ארנק"],
  ["rudimentary", "יסודי, בסיסי"],
  ["transaction", "עסקה"],
  ["embryo", "עוּבָּר"],
  ["dart", "חץ"],
  ["photograph", "צילום, לצלם"],
  ["[to] legislate", "לחוקק"],
  ["separately", "בנפרד"],
  ["numb", "רדום, חסר תחושה"],
  ["rotary", "נע על ציר סיבובי"],
  ["expedite", "לזרז"],
  ["eavesdrop", "לצותת"],
  ["injure", "לפצוע"],
  ["oppress", "לדכא"],
  ["grit", "גרגרים, לכלוך"],
  ["jug", "כד, קנקן"],
  ["prolong", "מתמשך"],
  ["algae", "אצות"],
  ["migrate", "לנדוד, להגר"],
  ["languor", "כבדות, חולשה, אפיסת כוחות"],
  ["modification", "תיקון, שינוי, השתנות"],
  ["linger", "להשתהות, להתעכב"],
  ["pepper", "פלפל"],
  ["coupon", "קופון"],
  ["integrate", "לשלב"],
  ["vest", "אפודה"],
  ["poacher", "מסיג גבול, צייד לא מורשה"],
  ["explode", "להתפוצץ"],
  ["insect", "חרק"],
  ["discontent", "חוסר שביעות רצון"],
  ["defer", "לעכב, לדחות"],
  ["unrest", "חוסר שקט"],
  ["shrink", "לכווץ, כיווץ"],
  ["transitory", "בר-חלוף"],
  ["prospective", "צפוי, עתידי"],
  ["tutor", "מורה פרטי, להדריך"],
  ["heredity", "תורשה"],
  ["horrify", "להפחיד"],
  ["resent", "להתנגד, להתרעם"],
  ["treasure", "אוצר, לנצור"],
  ["ingredients", "מרכיבים"],
  ["hasten", "למהר, להחפז"],
  ["instigate", "להסית"],
  ["bully", "בריון"],
  ["baffled", "מבולבל"],
  ["negligence", "רשלנות, הזנחה"],
  ["flagrant", "בוטה, מזעזע"],
  ["fingerprint", "טביעת אצבע"],
  ["glitch", "תקלה, הפרעה"],
  ["oppressive", "מדכא, מעיק, אכזרי"],
  ["nickname", "כינוי חיבה"],
  ["illustrator", "מאייר"],
  ["garlic", "שום"],
  ["suppression", "דיכוי"],
  ["bothersome", "מטריד, מרגיז"],
  ["gamble", "הימר"],
  ["apathy", "אפאתיה, אדישות"],
  ["reflection", "השתקפות"],
  ["cultivate", "לעבד, לטפח"],
  ["narcotic", "סם"],
  ["recommendation", "המלצה"],
  ["densely", "בצפיפות"],
  ["mourning", "אבל, מתאבל"],
  ["oscillate", "להיטלטל, להתנודד"],
  ["commensurate", "תואם"],
  ["fortify", "לחזק, לבצר"],
  ["orchestra", "תזמורת"],
  ["epilogue", "אחרית דבר"],
  ["burglar", "פורץ"],
  ["infancy", "ינקות"],
  ["stunt", "פעלול"],
  ["introduction", "הקדמה, מבוא, היכרות"],
  ["miracle", "נס, פלא"],
  ["consolation", "נחמה"],
  ["fastidious", "דקדקן, אנין טעם, בררן"],
  ["wander", "להסתובב, לשוטט"],
  ["elephant", "פיל"],
  ["repudiate", "להתכחש, לגנות, להתנער מ..."],
  ["propel", "להניע, לדחוף"],
  ["prestigious", "יוקרתי"],
  ["consolidate", "לאחד, לגבש"],
  ["resourceful", "בעל תושייה"],
  ["sensations", "חדשות מרעישות"],
  ["dawdle", "להתבטל"],
  ["reproduce", "להתרבות, לשכפל"],
  ["independence", "עצמאות"],
  ["daydream", "לחלום בהקיץ"],
  ["observation", "אבחנה"],
  ["decorate", "לקשט"],
  ["skyrocket", "להאמיר"],
  ["hospitable", "מסביר פנים"],
  ["whistle", "משרוקית, לשרוק"],
  ["lumber", "גזע עץ"],
  ["irrigation", "השקיה"],
  ["omission", "השמטה, הזנחה"],
  ["heresy", "כפירה"],
  ["allowable", "חוקי, מותר"],
  ["unfair", "לא הוגן"],
  ["situation", "מצב, סיטואציה"],
  ["indigenous", "ילידים, מולד"],
  ["absorbent", "בעל כושר ספיגה"],
  ["entertain", "לשעשע, לבדר"],
  ["joyous", "שמח, עליז"],
  ["shepherd", "רועה צאן"],
  ["preside", "לנהל"],
  ["blanket", "שמיכה"],
  ["pervasive", "מתפשט, מחלחל"],
  ["craftsmen", "אומן, בעל מלאכה"],
  ["pinch", "לצבוט"],
  ["printer", "מדפסת, דַּפָּס"],
  ["groom", "חתן, לטפח, לטפל"],
  ["bandage", "תחבושת"],
  ["corollary", "תוספת, תולדה"],
  ["veracity", "יושר, הגינות"],
  ["famine", "רעב קשה"],
  ["unbearable", "בלתי נסבל"],
  ["disciplined", "ממושמע, חינך, העניש"],
  ["drip", "לטפטף"],
  ["apposite", "מתאים מאד, הולם"],
  ["confrontation", "עימות"],
  ["inquire", "לתשאל"],
  ["surrender", "להיכנע"],
  ["fundamentalist", "מאמין בתורה שבכתב, בלי פרשנויות"],
  ["motif", "מוטיב"],
  ["fungus", "פטרת"],
  ["subconscious", "תת מודע"],
  ["seafood", "פירות ים"],
  ["examination", "בחינה, בדיקה"],
  ["benefactors", "נדבנים, תורמים"],
  ["dimension", "מידה, כמות, היקף, מימד"],
  ["sundown", "שקיעה"],
  ["elastic", "גמיש, אלסטי, גומיה"],
  ["prescription", "מרשם"],
  ["shrewdly", "בפיקחות"],
  ["condone", "לסלוח, למחול"],
  ["enroll", "להירשם"],
  ["reputation", "שם, מוניטין"],
  ["Gulf War", "מלחמת המפרץ"],
  ["languish", "הולך ונחלש, נוטה לאפיסת כוחות"],
  ["depict", "לצייר, לתאר, להציג, לשרטט"],
  ["coop", "לכלוא, לול"],
  ["handicap", "נכה"],
  ["toes", "בהונות"],
  ["grapes", "ענבים"],
  ["cigarette", "סיגריה"]
] as const;
