export default [
  ["despise", "לתעב"],
  ["dessert", "קינוח"],
  ["preventive", "מונע, מניעתי"],
  ["rubber", "גומי"],
  ["transformation", "שינוי"],
  ["circumstance", "מצב, נסיבות, תנאי"],
  ["[to] anguish", "לסבול"],
  ["elderly", "זקן, מבוגר מ..."],
  ["fatigue", "לעייף, עייפות, תשישות"],
  ["syndrome", "תסמונת"],
  ["flatter", "להחמיא, שטוח יותר"],
  ["ambivalent", "בעל משמעויות סותרות"],
  ["tin", "בדיל, עשוי מפח"],
  ["dim", "לעמעמם"],
  ["consequent", "בא כתוצאה"],
  ["juice", "מיץ"],
  ["mention", "להזכיר, לאזכר"],
  ["skillful", "מיומן"],
  ["fetus", "עובר (ברחם), עובר"],
  ["silk", "משי"],
  ["sweep", "לטאטא"],
  ["prevention", "מניעה"],
  ["accomplishment", "הישג, השלמה"],
  ["whale", "לוויתן"],
  ["compulsive", "כפייתי"],
  ["biblical", "תנ\"כי"],
  ["illusory", "חמקמק, מטעה"],
  ["invaders", "פולשים"],
  ["skimp", "להתקמצן"],
  ["tent", "אוהל"],
  ["norm", "נורמה, תקן"],
  ["courageous", "אמיץ"],
  ["heed", "לשים לב"],
  ["skyscraper", "גורד שחקים"],
  ["preferable", "עדיף"],
  ["chauffeur", "נהג"],
  ["conclusive", "מכריע"],
  ["align", "להסתדר בשורה"],
  ["silently", "בשקט"],
  ["objection", "התנגדות"],
  ["consciousness", "הכרה, מודעות"],
  ["descendent", "צאצא"],
  ["tempt", "לפתות"],
  ["suffocate", "להיחנק"],
  ["avert", "להפנות, להסיט, למנוע"],
  ["solitary", "מבודד"],
  ["translate", "לתרגם"],
  ["emergence", "היווצרות, הופעה הדרגתית"],
  ["diary", "יומן"],
  ["leadership", "מנהיגות"],
  ["clash", "התנגשות"],
  ["inherit", "לרשת"],
  ["vanish", "להיעלם"],
  ["visualize", "לדמיין"],
  ["radically", "באופן קיצוני"],
  ["slender", "רזה"],
  ["damp", "לח"],
  ["stuntman", "פעלולן (בסרטים)"],
  ["vacant", "ריק, פנוי"],
  ["contention", "מחלוקת"],
  ["agenda", "סדר יום"],
  ["theater", "בית קולנוע, תיאטרון"],
  ["coma", "תרדמת"],
  ["newscaster", "מגיש חדשות"],
  ["variation", "וריאציה, שינוי"],
  ["sober", "פיכח"],
  ["promotion", "קידום"],
  ["oppression", "דיכוי"],
  ["detection", "מלאכת האיתור, גילוי"],
  ["hasty", "מהיר, בהול"],
  ["evacuation", "פינוי"],
  ["enlightened", "נאור"],
  ["mobilize", "לנייד, להניע"],
  ["ascertain", "לוודא, לברר"],
  ["relic", "שריד, שארית"],
  ["admirable", "ראוי להערצה, נערץ"],
  ["bargain", "עסקה, מציאה, להתמקח"],
  ["disqualify", "לפסול, לשלול"],
  ["weapon", "נשק"],
  ["fairy", "פיה"],
  ["apparatus", "מנגנון"],
  ["petulant", "קצר רוח, חסר סבלנות"],
  ["enhance", "להעצים, להגביר"],
  ["candy", "ממתק"],
  ["buffoon", "ליצן"],
  ["confusion", "בלבול"],
  ["inclusion", "שיתוף"],
  ["fishing", "דיג"],
  ["spider", "עכביש"],
  ["vertebrae", "חוליות עמוד השדרה"],
  ["malfunction", "ליקוי, כשל"],
  ["illustrate", "להדגיש, להמחיש"],
  ["frivolous", "טפשי, קל דעת"],
  ["diversify", "לגוון"],
  ["curtain", "וילון"],
  ["radicalism", "קיצוניות"],
  ["desolate", "נטוש, הרוס, שומם"],
  ["shoulder", "כתף"],
  ["conceive", "לחשוב על..., להרות, להרהר, לעבר"],
  ["reinforce", "לחזק, לתגבר"],
  ["wedding", "חתונה"],
  ["torment", "להציק, סבל רב, לגרום סבל רב, לענות (בעינויים), עינוי"],
  ["illness", "מחלה"],
  ["hid from", "התחבא מ-"],
  ["exert", "להפעיל, להתאמץ"],
  ["convene", "לכנס"],
  ["disciples", "תלמידים"],
  ["utter", "לבטא, להגות"],
  ["myriad", "הרבה, רב"],
  ["formula", "נוסחה, פורמולה"],
  ["resigned", "התפטר"],
  ["bass", "בס (במוזיקה)"],
  ["spotlight", "זרקור"],
  ["transmitter", "משדר"],
  ["plead", "לעתור, להתחנן"],
  ["passion", "תשוקה"],
  ["equates", "להתאים, להשוות"],
  ["discourage", "לשכנע שלא לעשות משהו"],
  ["disguise", "תחפושת"],
  ["revert", "לחזור לשיטה הקודמת"],
  ["testify", "להעיד"],
  ["script", "תסריט"],
  ["cotton", "כותנה"],
  ["olive", "זית"],
  ["visibility", "ראות"],
  ["enclosure", "סגירה, כיתור, שטח מגודר"],
  ["vulnerable", "פגיע, פגיעות, רגיש"],
  ["desirable", "נחשק, רצוי"],
  ["refined", "מעודן, מלוטש"],
  ["immoral", "לא מוסרי"],
  ["divorce", "גירושין"],
  ["deceive", "להונות"],
  ["withstand", "להתמודד, לעמוד ב-, לעמוד נגד לחץ"],
  ["nut", "אגוז"],
  ["durable", "מאריך ימים, מתמשך, יציב, מחזיק מעמד"],
  ["clay", "חימר"],
  ["authenticity", "אמיתיות, אותנטיות"],
  ["shy", "ביישן"],
  ["outdated", "מיושן"],
  ["reconcile", "להתפייס, להשלים"],
  ["suspend", "לעכב, להשעות, להשהות"],
  ["construct", "לבנות"],
  ["barn", "אסם"],
  ["liver", "כבד"],
  ["assertive", "החלטי"],
  ["stabilize", "לייצב"],
  ["momentary", "רגעי, בכל רגע ורגע"],
  ["hospitality", "הכנסת אורחים"],
  ["limb", "איבר, קצה, גף"],
  ["recordings", "הקלטות"],
  ["tormented", "לייסר, לענות"],
  ["mimic", "לחקות"],
  ["decipher", "לפענח"],
  ["genesis", "בראשית, היווצרות, ספר בראשית, התהוות"],
  ["contentious", "מעורר מחלוקת"],
  ["awe", "יראת כבוד"],
  ["presume", "להניח"],
  ["duplicate", "לשכפל"],
  ["rhythm", "קצב, קצב"],
  ["plausible", "סביר, מתקבל על הדעת"],
  ["representation", "ייצוג"],
  ["exhibit", "מוצג, להציג"],
  ["prolific", "פורה, שופע"],
  ["intense", "אינטנסיבי, מעמיק, עז, רב עצמה, ניכר"],
  ["consideration", "התחשבות, עיון"],
  ["cheerful", "שמח, עליז"],
  ["[to] intrigue", "לסקרן"],
  ["faint", "קלוש, להתעלף"],
  ["masterpiece", "יצירת מופת"],
  ["fulfill", "להגשים, להשיג מטרה, להשלים"],
  ["[to] bridle", "לרסן"],
  ["witness", "להעיד, עד"],
  ["cancel", "לבטל"],
  ["wagon", "עגלה"],
  ["delusions", "אשליות, הזיות"],
  ["frequency", "תדירות, תדר, שכיחות"],
  ["[to] brighten", "להבהיר"],
  ["frustrate", "לתסכל"],
  ["vegetarian", "צמחוני"],
  ["thriller", "מותחן"],
  ["actress", "שחקנית (בהצגה או סרט)"],
  ["induce", "לייצר, לגרום"],
  ["loyalty", "נאמנות"],
  ["intellectual", "אינטלקטואלי"],
  ["distraction", "הסחת דעת, מסיח"],
  ["magical", "קסום"],
  ["skinned", "פשט עור"],
  ["incomprehensible", "לא מובן"],
  ["certify", "להצהיר, לאשר"],
  ["monarch", "מלך"],
  ["Dutch", "הולנדי"],
  ["appreciation", "הערכה"],
  ["insanity", "אי שפיות"],
  ["gratitude", "הכרת תודה"],
  ["buttress", "משען, לתמוך, תימוכין, לחזק"],
  ["conception", "תפיסה"],
  ["invention", "המצאה"],
  ["endanger", "לסכן"],
  ["cave", "מערה"],
  ["spice", "לתבל, תבלין"],
  ["endangered", "בסכנת הכחדה"],
  ["historian", "היסטוריון"],
  ["rat", "עכברוש"],
  ["maze", "מבוך"],
  ["continuation", "המשך"],
  ["chariot", "מרכבה"],
  ["department-store", "חנות כלבו"],
  ["spicy", "פיקנטי"],
  ["adaptable", "שאפשר להתאימו"],
  ["gasoline", "בנזין"],
  ["nowadays", "כיום, בימינו"],
  ["fancy", "מגונדר, מחבב"],
  ["lend", "להלוות, להשאיל"],
  ["dispatch", "לשגר"],
  ["inanimate", "דומם"],
  ["irregular", "לא רגיל"],
  ["dedication", "הקדשה"],
  ["evolutionary", "התפתחותי"],
  ["bald", "קרח"],
  ["description", "תיאור"],
  ["puzzle", "תצרף, פאזל, חידה"],
  ["swallow", "לבלוע"],
  ["satisfactory", "משביע רצון"],
  ["adaptation", "הסתגלות, התאמה"],
  ["mediate", "לתווך, לגשר"],
  ["overtake", "להשיג, לעקוף"],
  ["dye", "לצבוע, צבע"],
  ["singer", "זמר"],
  ["manners", "נימוס"],
  ["stratum", "שכבה, רובד"],
  ["snap", "במהירות (סלנג), להישבר"],
  ["differentiate", "להבדיל, להבחין"],
  ["lone", "בודד, יחיד"],
  ["[to] arouse", "לעורר"],
  ["pest", "מזיק (חרקים), מטרד, מפגע"],
  ["amass", "לצבור, לערום"],
  ["stain", "כתם"],
  ["blade", "להב"],
  ["occurrence", "התרחשות"],
  ["hobby", "תחביב"],
  ["establishment", "מוסד"],
  ["exclude", "לגרש, להרחיק, למנוע, לשלול"],
  ["dull", "סתום, עמום, משעמם"],
  ["flexibility", "גמישות"],
  ["propagate", "להתרבות"],
  ["terrify", "להבעית, להפחיד"],
  ["horrific", "איום"],
  ["replica", "העתק מדויק"],
  ["timid", "ביישן"],
  ["inactivity", "חוסר פעילות"],
  ["compress", "לדחוס"],
  ["restaurant", "מסעדה"],
  ["unconscious", "מחוסר הכרה"],
  ["persevere", "להתמיד"],
  ["copper", "נחושת"],
  ["straightforward", "ישיר"],
  ["declaration", "הכרזה, הצהרה"],
  ["treaty", "הסכם, אמנה, חוזה"],
  ["celebrate", "לחגוג"],
  ["suspense", "השהיה, מתח"],
  ["dread", "אימה, פחד, לחשוש, לפחד"],
  ["ridiculous", "מגוחך"],
  ["[to] enlighten", "להסביר"],
  ["erupt", "התפרץ, להתפרץ (בעיקר הר געש)"],
  ["container", "מיכל, קונטיינר"],
  ["ammunition", "תחמושת"],
  ["notion", "נטיה, מושג, דעה, רעיון"],
  ["reservoir", "מאגר"],
  ["conscience", "מצפון"],
  ["overlooked", "העלים עין"],
  ["dote", "לחבב יתר על המידה, \"לחנוק באהבה\""],
  ["scales", "קשקשים (של דג)"],
  ["echo", "הד"],
  ["verdict", "פסק דין, פסיקה"],
  ["rodent", "מכרסם"],
  ["incorporate", "לכלול, לשתף, לאגד"],
  ["avarice", "תאוות בצע"],
  ["renovate", "לשפץ (בניין), לשפץ, לחדש"],
  ["scorch", "לחרוך, לצרוב"],
  ["undertaker", "קברן"],
  ["underline", "להדגיש"],
  ["intrigued", "מסוקרן"],
  ["satisfaction", "שביעות רצון, סיפוק"],
  ["brick", "לבנה"],
  ["correspond", "להיות תואם, להתאים, להתכתב"],
  ["comprehension", "הבנה"],
  ["prevalent", "שכיח, נפוץ, רווח"],
  ["entrance", "כניסה"],
  ["transparent", "שקוף"],
  ["reprimand", "לנזוף"],
  ["detract", "להפחית, לגרוע"],
  ["baggage", "מטען, מזוודה"],
  ["pledge", "להתחייב"],
  ["annoy", "להציק, להרגיז"],
  ["subscribe", "לעשות מנוי"],
  ["filter", "מסנן, פילטר"],
  ["invoke", "לזמן, לעורר"],
  ["wonderful", "נפלא"],
  ["prejudice", "דעה קדומה"],
  ["auction", "מכירה פומבית"],
  ["prosperous", "מצליח, משגשג, פורח"],
  ["Equator", "קו המשווה"],
  ["flexible", "גמיש"],
  ["blew", "פוצץ, נשב (רוח), ניפח"],
  ["provoke", "להתגרות, להסית"],
  ["fury", "זעם"],
  ["oven", "תנור בישול"],
  ["monster", "מפלצת"],
  ["significance", "משמעות, חשיבות"],
  ["excavate", "לחשוף באמצעות חפירה"],
  ["exile", "לגרש, להגלות"],
  ["pardon", "חנינה, לחון, סליחה, מחילה, לסלוח"],
  ["symbolize", "לסמל"],
  ["bee", "דבורה"],
  ["extension", "שלוחה, הרחבה, הארכה"],
  ["pad", "לרפד"],
  ["foreseeable", "צפוי מראש, שניתן לחזותו מראש"],
  ["prosper", "לשגשג"],
  ["luggage", "מזוודות"],
  ["hive", "כוורת"],
  ["guidance", "הכוונה, הנהגה, הנחיה"],
  ["revise", "לשפר, לתקן"],
  ["envy", "לקנא, קנאה"],
  ["eagle", "נשר"],
  ["fork", "מזלג"],
  ["exhaust", "לעייף, צינור מפלט, פליטה, אגזוז, להתיש"],
  ["collaboration", "שיתוף פעולה"],
  ["cough", "שיעול, להשתעל"],
  ["counterpart", "עמית, בן-זוג, בעל תפקיד מקביל"],
  ["unjust", "לא צודק"],
  ["inspiration", "השראה"],
  ["regulate", "לווסת"],
  ["negotiation", "משא ומתן"],
  ["circulate", "להפיץ, לנוע במחזוריות"],
  ["stagger", "להתנודד, ללכת לא יציב"],
  ["overly", "יותר מידי"],
  ["appetite", "רצון עז, תיאבון"],
  ["conversation", "שיחה"],
  ["signature", "חתימה"],
  ["expedition", "מסע, משלחת חקר"],
  ["urine", "שתן"],
  ["garbage", "זבל"],
  ["bridle", "לרסן, לשים רסן על..., רסן"],
  ["eruption", "התפרצות"],
  ["achievable", "ניתן להשגה"],
  ["publicized", "פורסם"],
  ["excessively", "בצורה מוגזמת"],
  ["fool", "טיפש, לשטות במישהו"],
  ["heartless", "אכזר, קשה לב"],
  ["deviant", "סוטה"],
  ["arrogant", "יהיר, שחצן"],
  ["inevitable", "בלתי נמנע"],
  ["remedy", "תרופה"],
  ["prey", "לטרוף, טרף"],
  ["starve", "לרעוב"],
  ["unavoidable", "בלתי נמנע"],
  ["blur", "לטשטש, טשטוש"],
  ["influence", "להשפיע, השפעה"],
  ["tongue", "שפה, לשון, ניב"],
  ["sword", "חרב"],
  ["disgrace", "בושה"],
  ["candidly", "בכנות"],
  ["pupil", "תלמיד"],
  ["convict", "אסיר בכלא, אסיר, להרשיע"],
  ["translator", "מתרגם"],
  ["polite", "מנומס"],
  ["precious", "יקר"],
  ["hazardous", "מסוכן"],
  ["folk", "עממי"],
  ["slander", "להשמיץ, השמצה"],
  ["nocturnal", "של הלילה, לילי"],
  ["[to] memorize", "לשנן"],
  ["commute", "להמיר, נסיעה משותפת מפרברים לעבודה בעיר, להמתיק (עונש), לנסוע בקביעות לעבודה, להחליף"],
  ["disappoint", "לאכזב"],
  ["defiance", "סירוב בתוקף, מרי"],
  ["distinctive", "מיוחד"],
  ["compulsory", "חובה, מהווה חובה, של חובה"],
  ["tale", "מעשייה, סיפור, אגדה"],
  ["relieve", "להקהל, לגרום הקלה, להקל"],
  ["catastrophic", "הרה אסון"],
  ["academic", "אקדמי"],
  ["insist", "להתעקש"],
  ["flavor", "לתבל, טעם"],
  ["shadow", "להאפיל, צל"],
  ["transplant", "לשתול"],
  ["distinguish", "להבחין, להפריד, להבדיל"],
  ["knot", "קשר"],
  ["vegetable", "ירק"],
  ["intact", "ללא פגע, שלם"],
  ["[to] broaden", "להרחיב"],
  ["triple", "פי 3"],
  ["blink", "למצמץ"],
  ["limitation", "מגבלה"],
  ["snake", "נחש"],
  ["adhere", "לדבוק ב-, לדגול ב-"],
  ["mailman", "דוור"],
  ["handicapped", "מוגבל, נכה"],
  ["berry", "גרגרי יער"],
  ["lip", "שפה"],
  ["probe", "לחטט, לגשש, לברר"],
  ["refund", "החזר"],
  ["depression", "דיכאון"],
  ["accustomed", "מורגל"],
  ["repugnant", "מבחיל"],
  ["thief", "גנב"],
  ["afflict", "לייסר"],
  ["pregnant", "הרה (בהריון)"],
  ["horn", "צופר, קרן (של בע\"ח)"],
  ["[to] ascertain", "לוודא"],
  ["carpet", "שטיח"],
  ["aggression", "תוקפנות"],
  ["twins", "תאומים"],
  ["assimilate", "להיטמע, לספוג"],
  ["fertile", "פורה"],
  ["relapse", "הישנות, הדרדר"],
  ["footage", "קטע צילום"],
  ["sperm", "זרע"],
  ["barrack", "לצעוק ולצחוק בגסות"],
  ["interface", "ממשק"],
  ["determination", "קביעה, נחישות"],
  ["contribution", "תרומה"],
  ["peek", "להציץ"],
  ["concise", "תמציתי, תכליתי"],
  ["mentor", "מדריך רוחני"],
  ["inn", "פונדק"],
  ["soccer", "כדורגל"],
  ["petition", "עצומה, עתירה, לעתור"],
  ["languid", "נרפה"],
  ["poverty-stricken", "מוכה עוני"],
  ["legislate", "לחוקק"],
  ["curiosity", "סקרנות"],
  ["ingenious", "גאוני"],
  ["weaken", "להחליש"],
  ["oversee", "לפקח"],
  ["petroleum", "נפט"],
  ["solely", "רק, בלבד"],
  ["eloquent", "רהוט"],
  ["attire", "לבוש"],
  ["stubborn", "עקשן"],
  ["proportion", "מידה, שיעור"],
  ["makeup", "איפור"],
  ["ignorance", "בורות"],
  ["verbal", "מילולי, ורבלי"],
  ["permeate", "להתפשט, לחדור"],
  ["trigger", "דבר המעורר תגובה עזה, לעורר, להפעיל, הדק"],
  ["bail", "ערבות, לשחרר בערבות"],
  ["[to] certify", "לאשר"],
  ["fluent", "שוטף"],
  ["stroke", "ליטוף, שבץ, מכה, אירוע מוחי"],
  ["hike", "הליכה, טיול"],
  ["nationalize", "להלאים"],
  ["advertise", "פרסום, לפרסם"]
] as const;
